# El método fácil {#el-metodo-facil}

El objetivo de este libro es darte otra mentalidad. Contrario al método usual, donde solo tienes que detener tu consumo — con el cual, a su vez, empiezas con el sentimiento de estar escalando el Everest, mientras pasas las próximas semanas anhelando y sintiéndote privado — empiezas de inmediato con un sentimiento de entusiasmo, como si te hubieras curado de una terrible enfermedad. A partir de ahí, mientras más avances con tu vida, estarás mirando constantemente a este período de tiempo y te preguntarás cómo pudiste empezar a usar porno en primera instancia. Verás a cualquier otro usuario de porno con pena, lo opuesto a verlos con envidia.

Siempre y cuando no seas alguien que nunca se volvió adicto (alguien que está leyendo este libro para ayudar a un ser querido) o alguien que ya dejó el porno (o que está en los días de ayuno de una dieta pornográfica), es necesario que sigas usando pornografía hasta que hayas acabado el libro entero. Esto parece ser una contradicción, y esta instrucción de seguir masturbándote con porno causa más objeción que ninguna otra, pero ten en cuenta que mientras sigas leyendo, tu deseo de usarlo irá gradualmente reduciendo. **Tómate esta regla en serio: intentar dejarlo temprano no te va a beneficiar.**

Muchos no terminan el libro porque sienten que tienen que sacrificar algo a cambio, con algunos incluso leyendo deliberadamente una línea por día para posponer el fatídico evento. Pero mejor, velo de este modo: ¿qué tienes que perder? Si no te detienes para el final del libro, no serás peor de lo que eres ahora. Es, por definición, una _apuesta de Pascal_; una apuesta tomada en un contexto donde no tienes nada que perder, con probabilidad de ganancias más altas.

Aunque eso sí, si no has visto porno por algunos días o meses, pero no estás seguro si eres un usuario, un ex-usuario o un no-usuario, entonces no hagas uso del porno mientras lees. De hecho, ya eres un no-usuario, solo tenemos que hacer que tu cerebro se ponga al corriente con tu cuerpo. Para el final del libro, serás un no-usuario feliz. EasyPeasy es el completo opuesto del método normal, donde uno lista las considerables desventajas del porno y dice: 
_"si puedo seguir lo suficiente sin usar porno, el deseo eventualmente desaparecerá y podré disfrutar de mi vida de nuevo, libre de la esclavitud"_.
Es la forma lógica de hacerlo, con muchos usuarios dejando el porno todos los días usando este método. Sin embargo, es difícil tener éxito con este método debido a las siguientes razones:

**Parar el PMO no es el verdadero problema.** Cada que terminas una sesión de PMO, ya has dejado el porno. Y puede que tengas un par de poderosas razones en tu primer día de dieta pornográfica de _'cada-cuatro-días'_ para decir _"No quiero usar porno, o incluso masturbarme nunca más"_. Todos los usuarios lo hacen, y sus razones son mucho más poderosas de lo que imaginas. El problema viene el 2do, 10mo o 100mo día, cuando en un momento de debilidad tendrás _"solo una miradita"_, querrás otra y de pronto, eres un adicto de nuevo. 

**Ser consciente de los problemas de salud genera más miedo, haciendo que sea más difícil parar.** Dile a un usuario que está destruyendo su virilidad y lo primero que hará será buscar algo que le genere su dopamina, sea un cigarro, alcohol, o entrar a su navegador para ver porno de nuevo.

**Todas las razones para detenerse lo hacen más difícil.** Esto se debe a dos razones. Primero, somos continuamente obligados a renunciar a nuestro _'amiguito'_ o nuestro apoyo, vicio o placer (como sea que el usuario lo visualice). Segundo, crean un _'punto ciego'_. No nos masturbamos por las razones por las que deberíamos parar. La verdadera pregunta es, ¿Por qué queremos o necesitamos masturbarnos?

Con EasyPeasy, (inicialmente) olvidamos las razones por las que nos gustaría parar, enfrentamos el problema del porno y nos preguntamos lo siguiente:

* ¿Qué es lo que el porno está haciendo por mí?
* ¿Realmente lo disfruto?
* ¿En verdad necesito ir por la vida saboteando mi mente y mi cuerpo?

La verdad es que _el porno_ no hace absolutamente nada por ti. Dejémoslo en claro, no es que las desventajas de ser un usuario superen las ventajas, es que hay _**cero**_ ventajas en ser un usuario de pornografía.

Muchos usuarios encuentran la necesidad de racionalizar el por qué usar porno, pero las razones a las que llegan son puras falacias e ilusiones. 

Entonces, primero removemos las falacias e ilusiones. De hecho, pronto te darás cuenta de que no hay nada a lo que renunciar. No solo eso, sino que hay maravillosas y positivas ganancias de dejar de ser un adicto, siendo el bienestar y la felicidad propia dos de esas ganancias. Luego de que la ilusión de que la vida no será tan disfrutable sin usar porno sea removida — dándote cuenta de que la vida es, de hecho, infinitamente más disfrutable sin usarlo — y una vez que los sentimientos de privación o de _'estarse perdiendo de algo'_ sean erradicados, volveremos a reconsiderar un mayor bienestar y felicidad — y las mil y una razones más por las que dejar la pornografía. Estas comprensiones se volverán un aditamento positivo para ayudarte a alcanzar lo que realmente deseas: ¡disfrutar de una vida libre de la esclavitud que la adicción al porno te impone!
