# ¿Por qué es difícil parar? {#por-que-es-dificil-parar}

Todos los usuarios sienten que los ha poseído algo malévolo. Los primeros días, es una cuestión de _"pararé algún día, pero no será hoy"_, para eventualmente progresar a creer que aún no tienen suficiente 'fuerza de voluntad' para parar, o que hay algo inherente en el porno que necesitamos para poder disfrutar de la vida. La adicción al porno puede ser comparada con la idea de estar arañando tu camino para salir de un pozo resbaladizo: al llegar a la cima, puedes ver la luz del sol — pero tan pronto llegas, empiezas a bajar mientras tu estado de ánimo baja. Eventualmente vuelves a abrir tu navegador, y mientras te masturbas, te sientes terrible y te preguntas por qué lo volviste a hacer.

Pregúntale a un usuario, _"¿si pudieras volver a un tiempo antes de engancharte con el porno, con el conocimiento que tienes ahora, habrías empezado de nuevo?"_

_"¡DE NINGÚN MODO!"_ sería la respuesta.

Pregúntale al empedernido usuario, aquel que defiende el uso de pornografía y no cree que realmente le cause alguna lesión al cerebro o baja regulación de los receptores de dopamina: _"¿animarías a tu hijo a usar porno?"_

_"¡DE NINGÚN MODO!"_ es la respuesta, de nuevo.

El porno es un enigma extraordinario. Como se mencionó antes, el problema no es explicar por qué es fácil parar, sino explicar por qué es difícil. El verdadero problema es explicar por qué alguien sigue masturbándose _después de_ enterarse de los daños neurológicos. Parte de la razón por la que iniciamos es por las decenas de personas que ya están sumergidas, a pesar de que cada una de estas personas desean no haber iniciado en primer lugar, diciéndonos que es como _'vivir la vida en segunda velocidad'_. No podemos creer que en verdad no lo estén disfrutando. Asociamos esto con libertad o estar _'sexualmente educado'_ y trabajamos duro en engancharnos nosotros mismos, solo para poder pasar el resto de nuestras vidas diciéndoles a otros que no lo hagan, tratando de dejar el hábito nosotros mismos.

También pasamos una considerable proporción de nuestro tiempo sintiéndonos miserables y desesperanzados. Educarnos con este estímulo supranormal hace que prefiramos y anhelemos esas frías imágenes, ¡incluso cuando hay parejas, vividas y reales a nuestro alcance! Con el constante aumento y caída de dopamina inducido por el PMO, nos sentenciamos a una vida de irritabilidad, enojo, estrés, fatiga y disfunción sexual. Al usar porno, con la ausencia de las mejores partes referentes al sexo y la conexión de dos personas, terminamos sintiéndonos miserables y culpables.

¡De hecho, leer acerca de las capacidades adictivas y destructivas del porno por aquí y por allá nos hace sentir muchísimo más nerviosos y desesperanzados! ¿Qué clase de hobby es aquel en el cual, mientras lo haces, deseas no estar haciéndolo, y cuando no lo haces, anhelas hacerlo? Los usuarios se desprecian cada vez que leen acerca de la hipofrontalidad y la desensibilización, cada vez que usan porno a las espaldas de sus parejas, cada vez que no tienen el ánimo para hacer ejercicio después de una 'paja matutina'. Un ser humano cualquiera, que por lo demás es inteligente y racional, termina por pasar sus días en desprecio de sí mismo. Pero lo peor de todo, ¿qué es lo que un usuario gana por soportar una vida entera con estas _sombras_ detrás de su cabeza? **¡Absolutamente nada!**

Quizá pienses _"eso está muy bien, lo sé, pero en el momento en el que te enganchas con estas cosas es muy difícil detenerte"_. ¿Pero por qué es tan difícil? Algunos dicen que es por los poderosos síntomas de abstinencia, pero como pronto llegarás a descubrir, los síntomas de abstinencia son tan leves que deberías preocuparte por los adictos que vivieron y murieron sin saber que eran drogadictos.

Algunos dicen que, dado que el porno es gratuito, la raza humana debería reclamar esta bonanza biológica, pero es una forma incorrecta de verlo — es adictivo y funciona justo como cualquier otra droga. Pregúntale a un usuario que disfruta de un género como la _'erótica'_, como el de las revistas de Playboy, si alguna vez ha cruzado la línea de 'porno seguro'. Y te aseguro que, de ser completamente honesto, te confesaría de las veces que inconscientemente racionalizó hacerlo, en vez de no usarlo bajo ninguna circunstancia.

El disfrute no tiene nada que ver tampoco: disfruto de comer cangrejo, pero no he llegado a un punto en el que deba de comer cangrejo todos los días. Así como con otras cosas en la vida, las disfrutamos mientras las hacemos, pero no nos la pasamos sintiéndonos privados cuando no las hacemos.

Algunos dicen:

_"Es educativo"_ Muy bien. ¿Y cuándo te gradúas?

_"Es satisfacción sexual"_ ¿Entonces por qué hacerlo solo en vez de buscar una pareja, guardando ese deseo y energía para dicha?

_"Es un sentimiento de liberación"_ ¿Liberación del estrés de la vida real? El porno no removerá la fuente de dicho estrés, pero te aseguro que te dará aún más estrés.

Muchos creen que el porno alivia el aburrimiento, lo cual también es otra falacia. El aburrimiento es un estado de ánimo. El porno te habitúa a la búsqueda de novedad en poco tiempo, ocasionando que te aburras cada vez más hasta el punto de tener que buscar por el video perfecto, causando a su vez que estés más obsesionado con buscar cualquier cosa que te genere novedad, emociones fuertes y eventualmente, un sentimiento de shock muy profundo.

Algunos dicen que lo hacen porque sus amigos y todos los demás hacen. Si es así, ¡reza por que tus amigos no se empiecen a cortar la cabeza para curar un dolor de cabeza! Otros terminan llegando a la conclusión de que es un hábito. Esto no es realmente una explicación, pero habiendo descontado ya todas las usuales, irracionales explicaciones, parece ser que es la única excusa que queda. Desafortunadamente, es igual de irracional. Todos los días estamos cambiando hábitos, algunos de los cuales son muy disfrutables. Pero ya hemos sido engañados para creer que el PMO es un hábito, y que los hábitos son difíciles de romper.

¿En verdad, los hábitos son algo difícil de romper? Los conductores en Estados Unidos tienen el hábito de conducir en el carril derecho de la calle, y, aun así, cuando viajan en carretera, pueden romper ese hábito sin mucho problema. Es claramente una falacia que los hábitos sean difíciles de romper. Creamos y rompemos hábitos todos los días. ¿Así que por qué encontramos difícil romper un hábito que nos hace sentir privados cuando no lo tenemos, culpables cuando lo tenemos, que amaríamos romper de todos modos, y que lo único que tenemos que hacer es _dejar de hacerlo_?

La respuesta es que el porno no es un hábito, **¡es una adicción!** Es por eso que nos parece tan _difícil dejar de hacerlo_. Muchos de los usuarios no entienden el concepto de adicción y creen que obtienen genuino placer o apoyo del porno. Creen que están haciendo un genuino sacrificio si lo dejan. 

La hermosa verdad es que, una vez entiendas la naturaleza real de la adicción al porno, y las razones por las que lo usas, dejarás de usarlo, _así no más_. Dentro de tres semanas, ¡el único misterio será por qué encontraste necesario usar pornografía todo el tiempo que la usaste, y por qué no puedes persuadir a otros sobre _lo bien que se siente no ser un adicto!_ 

## La siniestra trampa

El porno de internet es la trampa más sutil y siniestra que el hombre y la naturaleza han podido idear. Es la única trampa en la naturaleza cuya configuración no requiere mucho esfuerzo. Algunos de nosotros incluso están al tanto de los riesgos, pero no podemos creer que aquellos adictos realmente no lo estén disfrutando. ¿Pero qué es lo que nos atrae en primer lugar? Típicamente, muestras gratis de amateurs o profesionales que comparten su material en redes o en cualquier otro medio. Así es como la trampa se activa. Tu primer 'vistazo', esa foto, ese video, o incluso, ese _'thumbnail'_ tiene _"manchas y hoyos"_, siendo que este material tiende a ser de calidad _'amateur'_ o está hecho en casa por modelos desconocidas, material que puede llegar a resultarnos novedoso, aunque un poco repugnante. Aunque claro, que en el caso de que tu primer vistazo tuviera bellezas angelicales, modelos demasiado voluptuosas, las alarmas comenzarían a sonar en tu cerebro, cuando ese sentimiento de novedad es activado con mayor impacto.

Sin embargo, y debido a esta discrepancia entre contenido, nuestras jóvenes mentes están ilusoriamente seguras de que nunca podrán engancharse con dicho material, pensando que, debido a que no lo disfrutamos en primera instancia, podremos parar en cualquier momento. No es hasta que, luego de trabajar tanto en engancharse, y como seres humanos inteligentes que somos, entendemos por qué la mitad de la población adulta era sistemáticamente adicta a algo que reducía su potencial para replicar lo que estaban viendo. La curiosidad terminó por llevarnos más cerca de las puertas de la adicción, aun sin que realmente hayamos dado clic en esos _thumbnails_, con miedo a enfermarnos. E incluso en caso de haber dado clic, contraemos una sensación de repugnancia, haciendo que queramos salir de esa página lo más rápido posible.

De ahí en adelante, gastamos el resto de nuestras vidas intentando entender por qué lo seguimos haciendo, diciéndole a nuestros hijos y compañeros que no lo hagan, mientras intentamos escapar nosotros mismos. Pero la trampa está diseñada de tal forma que nosotros solo intentaremos detener nuestro consumo debido a un 'incidente', sea un pésimo desempeño sexual, la pérdida de tu carrera o pareja, la repentina escasez de deseo sexual o simplemente por contraer un sentimiento similar al de un leproso. Pero tan pronto nos detenemos, desarrollamos mucho más estrés debido a los dolores de abstinencia, sin contar con el método que usábamos para poder remover dicho estrés.

Después de unos días de tortura, llegamos a la conclusión de que escogimos el momento equivocado para poder dejarlo, y tomamos la decisión de esperar por períodos en donde no nos estresemos, los cuales, al llegar, remueven la razón por la cual habíamos parado inicialmente. Aunque por supuesto, este período nunca va a llegar, debido a que internamente creemos que nuestras vidas tienden a volverse más y más estresantes. Estrés como el de dejar la protección de nuestros padres, el estrés del trabajo, el estrés de ser un 'ama de casa', las hipotecas, los bebés, casas más grandes, y más bebés ocupando esa casa. Esto no es cierto, es una ilusión, ya que la verdad es que las etapas más estresantes en la vida de cualquier ser vivo son la niñez temprana y la adolescencia.

El problema es que tendemos a confundir la responsabilidad con el estrés. La vida de un usuario — así como la de un drogadicto — se vuelve automáticamente más estresante porque el porno no relaja o aligera el estrés, como algunos te quieren hacer creer. Es justo lo contrario, causando que te estreses más mientras más lo usas, _'poniendo más peso a la espalda del camello'_. Incluso los usuarios que pudieron dejar el hábito (algunos haciéndolo una o más veces en su vida) pueden tener vidas perfectamente felices y aun así engancharse de nuevo. Deambulando cada vez más por el 'laberinto pornográfico', nuestras mentes experimentan más 'bruma' y pasamos el resto de nuestras vidas tratando de escapar. Algunos lo consiguen, solo para recaer en la trampa más adelante.

La adicción al porno es un complejo y fascinante rompecabezas, y similar al 'Cubo Rubik', prácticamente imposible de resolver. Pero si tienes la solución, ¡es simple y divertido! EasyPeasy contiene la solución a este rompecabezas, guiándote fuera de este laberinto, para no deambular nunca más. Todo lo que tienes que hacer es seguir las instrucciones. Sin embargo, recuerda que, de tomar una vuelta equivocada, el resto de las instrucciones serán inútiles.

Cualquiera puede encontrar sencillo dejar la pornografía, pero debemos establecer primero los hechos. No, no hechos diseñados para asustarte, ya hay suficiente información al respecto. Si esos hechos fueran a pararte, ya lo habrían hecho. ¿Pero por qué encontramos difícil parar? Responder a estas preguntas requiere que sepamos las razones reales por las que seguimos usando porno, resumido en dos factores:

* La naturaleza del porno.
* El lavado de cerebro.

Los usuarios son seres humanos inteligentes y racionales. Saben que están tomando grandes riesgos a futuro, así que pasan la mayoría del tiempo tratando de racionalizar su hábito. Pero los usuarios de pornografía saben en el fondo que son unos tontos, sabiendo que no tenían ninguna necesidad de usarla antes de engancharse. Algunos recuerdan que 'su primer vistazo' fue una combinación de repugnancia y novedad. Recuerdo que se pierde, tan pronto se especializan en localizar, filtrar y 'añadir a sus marcadores' dichas páginas, tratando fuertemente de engancharse.

Más molesto aún, los usuarios incluso llegan a tener la noción de que los no-usuarios — siendo la mayoría mujeres, gente mayor y gente viviendo en lugares donde el porno no está disponible debido a sus servicios de internet — no se están perdiendo de nada, encontrando dicha situación graciosa. Desmantelando esos factores en los siguientes capítulos, ¡tú también entenderás esta siniestra trampa!
