# ¿A qué estoy renunciando?

**¡A absolutamente a nada!** Es difícil dejar el porno por el miedo a ser privados de nuestro placer o “apoyo”. Por el miedo a que ciertas situaciones placenteras nunca volverán a ser las mismas. Miedo a que serás incapaz de lidiar con situaciones estresantes. En otras palabras, es difícil de dejar el porno gracias al efecto del lavado de cerebro, engañándonos para creer que el sexo — y por lo tanto el orgasmo — es una necesidad para todas las personas. Más aún, también se debe a la creencia de que hay algo inherente en el porno que necesitamos, y que cuando dejemos de usarlo nos estaremos negando dicho apoyo a nosotros mismos, generando a su vez un vacío.

Hazte a la idea de una vez: **¡El porno no llena ningún vacío, _crea un vacío_!**

Nuestros cuerpos son los objetos más sofisticados del planeta. Así creas en el diseño inteligente, en la selección natural, o en una combinación de ambos conceptos, ¡nuestros cuerpos son miles de veces más efectivos que el hombre en sí mismo! Somos incapaces de crear con nuestras propias manos la más pequeña célula viviente, o los milagros de la vista, la reproducción y alguno de los varios sistemas entrelazados presentes en nuestros cuerpos o cerebros. Si nuestro creador hubiera tenido la intención de que manejáramos un estímulo supranormal como lo es el porno, nos habría proporcionado entonces un sistema de recompensa diferente en nuestro sistema nervioso. Nuestros cuerpos están provistos con mecanismos de alarma a prueba de fallos, el cual como empedernidos usuarios que somos ignoramos bajo nuestro propio riesgo...

## No hay nada a lo que renunciar

Una vez que purgas ese pequeño monstruo de tu cuerpo y el lavado de cerebro (el gran monstruo) de tu mente, ya no buscaras ni masturbarte con mucha frecuencia ni usar porno para ello. Hay muchos hechos e incógnitas en cuanto a adicción al porno se refiere, con muchos en la comunidad médica sin tener el concepto ni la voluntad de cuestionar o determinar a alguien como un adicto al porno. Incluso, muchos de los síntomas del adicto están mal etiquetados bajo otras causas. Y no es que los usuarios sean generalmente gente estúpida; recuerda, es solo que son miserables sin el porno. Atrapados entre la espada y la pared, se abstienen y terminan sintiéndose miserables porque no pueden usar porno, o terminan sintiéndose culpables y despreciándose a sí mismos. Cuando tienen síntomas como dolor en la espalda baja o disfunción sexual, sus mentes se dividen entre aceptar la responsabilidad o mirar a otra parte.

Otra analogía de fumador: todos nosotros hemos visto fumadores que desarrollan excusas para escabullirse por una _calada_ y vemos la verdadera adicción en acción. Los adictos no hacen esto por placer, en cambio lo hacen porque son miserables sin ello.

Para muchos su primera experiencia sexual termino en un orgasmo, y así adquirieron la creencia de que no se puede disfrutar del sexo sin uno. Para los hombres, el porno es vendido como un aditamento al sexo, a veces incluso como una forma de educarlos para entrar en confianza durante el acto. Cosa que no cobra sentido, ya que condicionarse a este estímulo supranormal solo hará que tu confianza sea reducida. 

No solo tienes nada que perder, sino que también tienes muchos beneficios a obtener. Cuando los usuarios contemplan dejarlo, tienden a concentrarse en aspectos de salud y virilidad. Estas son razones válidas e importantes, pero personalmente creo que los mayores beneficios son psicológicos:

* El regreso de tu confianza y coraje.
* Libertad de la esclavitud.
* No más horribles sombras detrás de tu mente, y no más desprecio hacia ti mismo.

## Oh, el vacío, el vacío, ¡el hermoso vacío!

Imagina que tienes un herpes en el rostro, así que vas a la farmacia y te dan un ungüento gratis, para que lo pruebes. Te pones el ungüento y el herpes desaparece de inmediato. Una semana después reaparece, así que vuelves a la farmacia preguntando si tiene más ungüento. El farmacéutico dice “claro; solo conserva el tubo, puede que lo necesites luego”.

Aplicas el ungüento y _presto_, el herpes desaparece de nuevo. Pero cada vez que regresa el herpes, se vuelve más grande y doloroso, con los intervalos en que aparece siendo cada vez más y más cortos. Eventualmente, el herpes cubre todo tu rostro y es extremadamente doloroso, y está regresando cada media hora. Sabes que el ungüento lo removerá temporalmente, pero estás muy preocupado. ¿Se esparcirá eventualmente en todo tu cuerpo? ¿Desaparecerá el intervalo por completo? Vas con tu doctor y resulta que no puede curarlo, así que intentas otras cosas, pero nada ayuda además del ungüento.

Para entonces ya eres completamente dependiente del ungüento, nunca sales sin estar seguro de que lo llevas contigo. Si sales por varios días, te aseguras de llevar varios tubos contigo. Además de la preocupación por tu salud, el farmacéutico te está cobrando cien dólares el tubo. Y no tienes más opción que pagar.

Sin embargo, de casualidad te topas con un artículo discutiendo esto y descubres que no te está pasando solo a ti, mucha más gente sufre el mismo problema. De hecho, la comunidad médica ha descubierto que el ungüento no cura el herpes, sino que solo desaparece el herpes de la superficie de la piel. Es el ungüento lo que causó el crecimiento del herpes, así que todo lo que tienes que hacer para deshacerte del herpes es dejar de usar el ungüento; y el herpes desaparecerá con el tiempo.

¿Seguirías usando el ungüento? ¿Tomaría fuerza de voluntad no usar el ungüento? Si no creyeras lo que dice el artículo puede que habría algunos días de aprehensión, pero una vez te des cuenta de que el herpes comienza a mejorar, la necesidad o deseo de usar el ungüento se irá. ¿Serás miserable? ¡Claro que no lo serás! Tenías un problema que creíste era incurable pero ahora has encontrado la solución. Incluso si tomara un año en que se fuera el herpes, cada día que mejorará pensarías en cuan maravilloso te sientes. Esta es la magia de dejar el porno.

El herpes no son los dolores corporales, la falta de deseo, disminución de la excitación sexual, el perder el tiempo en imágenes bidimensionales y menospreciando a la gente que te descubrió o peor aún, menospreciándote a ti mismo. Todos estos síntomas son adicionales al herpes.

El herpes nos hace cerrar nuestra mente a todas estas cosas; el herpes es ese sentimiento de pánico por buscar una dosis. Los que no consumen porno no sufren de ese sentimiento. Lo peor que podemos padecer como usuarios es ese miedo, y la mayor ganancia que podemos obtener es librarnos de ese miedo. Librarnos de ese miedo causado por tu primera sesión, el cual es posteriormente intensificado y causado por cada sesión subsecuente.

Algunos usuarios son “felices”, cegados por su astuto y pequeño monstruo, continuando así en la misma pesadilla, poniendo falsos argumentos para tratar de justificar su estupidez.

_¡Es tan agradable ser libre!_
