# Ahorrando tu tiempo {#ahorrando-tu-tiempo}

Cuando los usuarios tratan de detenerse, las principales y usuales razones por las que quieren detenerse son por salud, religión y estigmas que tienen sus parejas, dado que tengan una. Y una parte del lavado de cerebro que el porno genera se basa en la absoluta esclavitud que te impone; el hombre ha luchado por siglos para abolir la esclavitud en varias partes del mundo — y, aun así, el usuario pasa su vida sufriendo de una esclavitud autoimpuesta. Son inconscientes de que cuando se les permite usar porno desearían ser no-usuarios. Y de que el único momento en que el porno se vuelve preciado es cuando “tratamos” de limitarlo o abstenernos, o cuando la abstinencia nos es forzada.

No puedo dejar de repetirlo; el lavado de cerebro hace difícil dejar el porno, y entre más lo disipemos antes de iniciar, más fácil encontrarás alcanzar tu meta. Usuarios autoconfesos, los cuales tampoco creen que el porno tenga un efecto negativo en su salud (disfunción eréctil inducida por el porno, hipofrontalidad, etc.) y que no sufren de una ‘guerra mental’ son normalmente gente joven, o solteros con una pareja sexual ocasional. En estos casos, normalmente la retroalimentación interna (y la idea de que ver porno no les cause daño) se pierde debido a la naturaleza de su juventud; sus vidas están demasiado ocupadas o es muy poca habitual como para ser observada y registrada.

Un buen argumento para convencer a un usuario joven es el tiempo que invierten, diciendo _“no puedo creer que no estés preocupado del tiempo que estás invirtiendo en porno.”_ Generalmente sus ojos se encienden, sintiéndose en desventaja si son atacados en ámbitos de salud o de estigma social, pero justo a tiempo... _“oh, pero me puedo dar el lujo, son solo ‘x' horas a la semana y creo que lo vale, es mi único vicio.”_

_“Aun así, no puedo creer que no te preocupe. Supongamos que usas media hora diaria en promedio, que incluye el drenado físico de dopamina, por lo cual estarías desperdiciando cerca de un día de trabajo entero, cada quincena. Estoy seguro de que coincides conmigo en que media hora diaria es un estimado bastante justo. ¿Pero has pensado cuánto tiempo desperdiciarás a lo largo de tu vida? ¿Qué haces en ese tiempo? ¿Consigues relaciones reales? No, tu estrella porno favorita no tiene simpatía por ti, y no la tendrá solo porque pases tanto tiempo en sus videos — ¡estas tirando tu tiempo a la basura! No solo eso, estás usando ese tiempo para arruinar tu salud física, destruir tus nervios y confianza, ¿y para qué? Una vida de esclavitud, dolor, melancolía y mal humor. Seguro que eso te preocupa, ¿verdad?”_

Es aparente en este punto — especialmente con usuarios más jóvenes — que nunca lo consideraron una adicción de por vida. Ocasionalmente, ellos calculan el tiempo que desperdician en una semana y eso ya es bastante preocupante. Y muy ocasionalmente, y solo cuando piensan en parar, ellos estimarán cuánto desperdiciarán en un año, lo cual es alarmante — ¿pero en toda una vida? Impensable. Sin embargo, en un argumento así el usuario impulsivamente dirá _“puedo costearlo, es un tanto a la semana”_ sacando una tanda de ases bajo la manga para convencerse a sí mismos.

¿Rechazarías una oferta de trabajo que te ofrece tu salario anual y que además te da un mes de descanso PAGADO al año? Cualquier persona firmaría sin pensarlo y se ocuparía en encontrar ofertas para vacacionar en lugares exóticos. Encontrar la manera de pasar ese tiempo sería el problema más grande que tendrían. Sin embargo, en toda discusión que he tenido con un usuario (y por favor ten en mente que no es alguien como tú que planea detenerse) nadie me ha aceptado esa oferta. ¿Por qué no?

A menudo, este usuario me contesta algo así como, _“mira; la verdad es que dinero no me hace falta ahora...”_ Solo piensa en esas líneas y pregúntate porque no le preocupa. ¿Por qué en otros aspectos de tu vida tomarías ofertas ridículas para ahorrar unos dólares aquí y allá, pero cuando hablamos de tu adicción gastarías miles de horas matando tu felicidad?

Cualquier otra decisión que tomes en tu vida será el resultado de un proceso analítico, valorando ventajas y desventajas para llegar a una decisión racional. Puede que sea la decisión incorrecta, pero será el resultado de una deducción racional. Así pues, cuando cualquier usuario tantee las ventajas y desventajas de seguir usando porno siempre llegará a la misma conclusión: _“¡DEJA DE USARLO! ¡ERES UN TONTO!”_ Por lo tanto, podemos deducir que todos los usuarios lo están usando no porque ellos quieran o decidan, sino porque no pueden parar. Ellos **tienen que consumir porno**, y así lavarse el cerebro ellos mismos, manteniendo sus cabezas en la arena.

Los usuarios que desean parar deben de tener en mente que la situación solo empeorará exponencialmente; más estudios están saliendo a la luz y más gente está hablando de los dañinos efectos del porno. Hoy, es gente no-relacionada a la medicina quien discute los efectos, y quien sabe; mañana quizá esté en la lista de diagnóstico de tu doctor. Atrás quedaron los días donde el usuario podía esconder sus ‘bajones de ánimo’ tras el estrés del trabajo, para posteriormente ser cuestionados por su pareja, quien estará preguntando por qué siempre está en su laptop a altas horas de la noche. Gracioso, el pobre usuario — ya sintiéndose miserable — ahora estará buscando que el suelo se lo trague.

Lo más extraño es que mucha gente pagaría buen dinero por una membresía en el gimnasio y entrenadores personales para hacer músculos y lucir esculpido, y algunos, en su imaginaria (y real) desesperación, incluso intentando tratamientos como aumentar sus niveles de testosterona, con dudables y peligrosos efectos secundarios. Y, de todas formas, hay bastante gente en este grupo que saben lo mucho que les beneficiaría detener una práctica que destruye sistemáticamente los sistemas de relajación de sus cerebros. ¿Por qué muchos no lo pueden ver así?

Esto es porque aún piensan con la mente de un usuario cuyo lavado de cerebro es demasiado fuerte. Limpia la arena de tus ojos por un momento. El porno es una reacción en cadena y una cadena de por vida, y si no rompes esta cadena seguirás como usuario por el resto de tus días. Calcula cuánto tiempo crees que pasarás en el porno por el resto de tu existencia; obviamente la cantidad variará de persona a persona, pero asumamos que usaras un aprox. de un año y medio de horas de trabajo. Y ahora, imagina que habrá un boleto de lotería por un año y medio de tu salario debajo de tu alfombra el día de mañana. Estarías bailando de emoción, ¡así que empieza a bailar! ¡Estás a punto de recibir esos beneficios!

Ya, ya. Pero si crees que es una manera engorrosa de verlo, aún te estás engañando a ti mismo. Solo medita: ¿cuánto tiempo habrías ahorrado si nunca hubieras echado ese primer vistazo desde el principio?

Pronto, estarás tomando la decisión de tener tu última sesión (aún no, ¡por favor recuerda las instrucciones!), manteniéndote como un no-usuario al no caer en la trampa de nuevo. Todo lo que tienes que hacer para mantenerte como no-usuario es no usar porno y evitar el ‘echar una miradita.’ Recuerda que, si lo haces, te costará cualquiera sea la ganancia de tu salario.

Si estás instruyendo a alguien por su adicción al porno, diles que conoces a un idiota que rechazó una oferta de trabajo que le daba su salario anual junto con un mes de descanso pagado. Y cuando pregunte quien es el idiota, dile, **“¡TÚ, TÚ ERES EL IDIOTA!”** Es maleducado, pero a veces necesitas llegar al punto de una manera menos amable.
