# Salud {#salud}

Esta es el área donde el lavado de cerebro es más fuerte con los usuarios, — particularmente con los más jóvenes y las personas solteras — quienes creen que están conscientes de los riesgos de salud, sin estarlo realmente. Muchos se engañan a sí mismos diciendo que están preparados para aceptar las consecuencias. Pero si tu Reuter de Internet tuviera una alarma que sonara cada vez que entras a un sitio pornográfico, y dijera _“Advertencia - te has salido con la tuya esta vez, pero si te quedas un minuto más en ese sitio tu cabeza explotará.”_, ¿te hubieras quedado? Si estás dudando de tu respuesta, trata de buscar un acantilado, pararte en el borde con los ojos cerrados, e imaginar que tienes que tomar la decisión de dejar el porno o dar un paso adelante. 

No hay duda sobre cuál decisión tomarías, pero no lograrás nada si solo _escondes tu cabeza en la arena_, esperando que despiertes una mañana sin querer ver porno nunca más. Los usuarios no pueden permitirse a sí mismos pensar en los riesgos de salud, porque si lo hacen el disfrute ilusorio de su adicción desaparecería. Esto explica porque las terapias de shock son ineficaces en las primeras etapas para dejar el porno, ya que solo son los no-usuarios los que se pueden permitir leer acerca de los destructivos daños cerebrales. 

Toma como ejemplo esta conversación, típica con los usuarios más jóvenes:

**Yo:** _“¿Por qué quieres dejar el porno?”_

**Usuario:** _“Leí en el blog de un ‘artista de ligue’ que es bueno dejarlo por unos días para poder mejorar la confianza en mí mismo.”_

**Yo:** _“¿Entonces no te preocupan los riesgos de salud?”_

**Usuario:** _“No. La verdad es que me da igual si un autobús me atropella mañana.”_

**Yo:** _“Ok... ¿Pero dejarías que un autobús te atropelle deliberadamente?”_

**Usuario:** _“Claro que no.”_

**Yo:** _“Volteas a los dos lados cuando cruzas la calle, ¿verdad?”_

**Usuario:** _“Obvio que sí.”_

Exactamente. Los usuarios se esmeran tanto en no dejar que los atropelle un autobús, aun cuando las chances de que eso pase son de una en un millón. Y, sin embargo, se arriesgan ante la cercana certeza de ser lisiados por su adicción, cosa que parece pasar inadvertida para ellos. Es tanto el poder del lavado de cerebro, que el porno de internet pasa a ser un lobo con disfraz de oveja. ¿No te parece extraño que, si supiéramos que el avión al que nos vamos a subir tuviera una falla, no nos subiríamos a él - incluso cuando las chances de que pase algo son de una en un millón - y que, aun así, tomamos una certeza de uno-de-cada-cuatro al usar pornografía, siendo aparentemente inadvertidos a esta probabilidad? ¿Otra vez, qué es lo que el usuario obtiene de esto? **¡Absolutamente nada!**

Otro mito común es la depresión o el mal humor. Muchos jóvenes no se preocupan por su salud en general porque no sufren de depresión o melancolía de ningún tipo. La depresión o el estrés no son la enfermedad en sí, son síntomas. Los usuarios más jóvenes no sienten irritabilidad o depresión gracias a la habilidad natural de su cuerpo para poder crear dopamina constantemente. Pero a medida que crecen o sus vidas enfrentan severos contratiempos, sus ya usados recursos estarán sobrecargados, lo que los hará tener síntomas más severos. Cuando los usuarios más viejos se sienten más estresados, deprimidos o irritados de lo común, es porque sus mecanismos naturales, a prueba de toda falla, están protegiendo el sistema nervioso de una inundación excesiva de dopamina, cortando los receptores de dicha. Así, el usuario desarrolla otro tipo de cambios neurológicos que lo mantienen en el mismo carril de su adicción.

Trata de verlo de esta manera. Imagina que tienes un carro demasiado bueno, el cuál dejas que con el tiempo se oxide sin hacer nada para evitarlo. Eso sería algo tonto, ¿no lo crees? Rápidamente, se convertiría en un montón de óxido inamovible, incapaz de poder transportarte a ningún lado. Sin embargo, no sería el fin del mundo ya que solo es una cuestión de dinero. ¿Pero qué tal con tu cuerpo? ¿Con el único vehículo que te lleva por la vida? Todos decimos que nuestra salud es nuestra mejor cualidad, pregúntale a cualquier millonario enfermo. Muchos de nosotros podemos mirar a un punto de nuestra vida, donde un accidente o enfermedad nos tenía rezando para poder recuperarnos. Siendo un usuario, no sólo estás dejando que el óxido entre a tu cuerpo sin hacer nada, sino que también estás destruyendo el único vehículo que te puede llevar por la vida.

Date cuenta. No tienes que dejar que tu cuerpo se oxide, porque recuerda: el PMO no está haciendo absolutamente nada por ti. Saca tu cabeza de la arena por un momento y pregúntate: A sabiendas de que tu próxima sesión iniciará un proceso que te haría completamente insensible a alguien a quien amas profundamente, ¿tomarías el riesgo? Tomando de ejemplo a aquellos a los que les está sucediendo, ellos no pensaban que les pasaría tampoco, y lo peor de esto no es esta cruel enfermedad en sí, sino saber que se lo buscaron ellos mismos. Trata de imaginar cómo es que las personas que han podido presionar el botón mágico se sienten cuando el lavado de cerebro por fin acaba. Pasan el resto de sus vidas pensando: _“¿Por qué me engañe a mí mismo por tanto tiempo para pensar que necesitaba masturbarme? ¡Oh, si tuviera la oportunidad de regresar en el tiempo...!”_

Deja de engañarte, tienes esa oportunidad **ahora**. Es una reacción en cadena, si empiezas la próxima sesión, esta te guiará a la siguiente sesión, y a la que sigue. Esto ya está sucediendo. E EasyPeasy te prometió que no habría tratamiento de shock, así que si ya has decidido qué vas a parar, lo que sigue no será _shockeante_ para ti. Si no lo has decidido aún, _sáltate el resto de este capítulo_ y regresa cuando hayas acabado el resto del libro.

Volúmenes sobre volúmenes de investigación ya han sido escritos, los cuales hablan sobre el daño que causa la pornografía a nuestras vidas sexuales y nuestro bienestar general. El problema es que, hasta que deciden parar, los usuarios no quieren saber nada de esto. Los foros y grupos de mentores son una pérdida de tiempo porque el porno no quita la venda de nuestros ojos. Y si se llegan a leer inadvertidamente los riesgos, la primera cosa que un usuario hará será abrir su sitio de preferencia. Los usuarios tienden a pensar en la felicidad, el estrés y el sexo como una especie de juego de azar, similar a pisar una mina terrestre.

Entiende de una vez; está sucediendo justo ahora. **Cada vez** que abres tu sitio pornográfico estás activando la inundación de dopamina y opioides en tu cerebro. Los toboganes de agua neuronales son engrasados y la bajada te lleva directamente a los siguientes pasos, con tu cerebro sabiendo perfectamente cómo hacerlo según el guion. El sistema nervioso ahora está repleto de dopamina y ya que es la enésima vez, los receptores de dopamina se cierran y el pequeño monstruo utiliza estos bajos niveles de placer y novedad como excusa para poder conducirte más allá de la línea roja; a géneros de porno o comportamientos más intensos para poder liberar más dopamina. Más novedad, más dopamina y el pequeño monstruo diciéndote que lo sigas alimentando. Tantos videos y tantas imágenes en una sola sesión desencadenan un estímulo supranormal, inyectando más químicos al cerebro y haciendo que sigas repitiendo este proceso.

Todo el tiempo, tus receptores están recibiendo información para poder apagarse en respuesta a la excesiva cantidad de estímulo. El orgasmo solo incrementa este efecto y te lleva a practicar la abstinencia. Sin embargo, negarte a estos efectos no inhibirá al pequeño monstruo, quien ansía su dosis sin remordimiento alguno. La amenaza de tener disfunción eréctil aterroriza a muchos, por lo cual bloquean esta idea de sus mentes y la opacan con el miedo de tener que dejar de ver porno o masturbarse. No es que el miedo sea muy grande, pero parar es inmediato e instantáneo. ¿Por qué verlo por el lado negativo? Quizá no desarrolles disfunción eréctil, y podrás dejar el porno para cuando pase de todas formas.

También tendemos a pensar en la pornografía como un juego de jalar la cuerda, por un lado, está el miedo: _“No es sano, es asqueroso y esclavizador”_. Por el otro lado: _“Es MI placer, mi amigo, mi apoyo”_. Pero nunca se nos ocurre que este último lado también se trata de miedo; no es que disfrutemos del porno, es que tendemos a ser miserables sin él. Los adictos a la heroína, sin heroína son miserables, pero imagínate lo alegres que son cuando finalmente pueden inmersar una aguja en sus venas y terminan con esa terrible ansia. Trata de imaginar cómo es que alguien puede creer que realmente obtiene placer de introducir una jeringa hipodérmica en sus venas. Los no-adictos a la heroína no sufren de este sentimiento de pánico, y la heroína no lo alivia, lo causa.

Los no-usuarios no se sienten miserables si no se les permite usar porno — son solo los usuarios los que sufren de ese sentimiento. Y el porno de Internet no alivia este sentimiento, lo causa. El miedo a las consecuencias negativas no ayuda a los usuarios a dejarlo, solo hace que asimilen este sentimiento con el de caminar en un campo minado. Si te sales con la tuya, está bien, pero si hoy no tuvieras la misma suerte ya habrías pisado una mina y enfrentado las consecuencias. Y si hubieras sabido de los riesgos y estuvieras preparado para asumirlos, ¿de quién más sería la culpa? Los adictos en este estado típicamente desarrollan este tipo de tácticas evasivas:

_**“Eventualmente envejecerás y perderás tu destreza sexual de todas formas...”**_

Claro que la perderás, pero la destreza sexual no es el punto focal en este caso — hablamos de esclavitud aquí.

_**“La calidad de vida es más importante que solo vivir.”**_

¡Precisamente! ¿Estás sugiriendo que la calidad de vida de un adicto es mejor que la de un no-adicto? ¿En serio crees que es así? Una vida basada en esconder la cabeza en la arena y ser miserable no suena placentera.

_**“Estoy soltero y no planeo asentarme con nadie en el futuro, ¿Así que, por qué no?”**_

Incluso si eso fuera cierto, ¿es una razón lógica para jugar con los mecanismos de control de impulsos neuronales de tu cerebro? ¿Acaso puedes concebir a una persona tan estúpida para hacer _bailes eróticos desnudo_ cuando está a solas, a pesar de cuán segura está de que nadie está viéndola? **¡Eso es justo lo que un usuario de pornografía hace!**

El agotamiento excesivo de nuestros circuitos de recompensa con estimulación excesiva, y hacer que dichos circuitos no sean capaces de lidiar con el estrés normal que la vida nos ocasiona no ayuda a disfrutar de tu vida con vigor y entusiasmo. El porno y la masturbación han reemplazado el apetito sexual natural, como una barra de chocolate reemplazando comida real. Y para sorpresa de nadie, muchos doctores y psicólogos están relacionando varios problemas mentales inducidos por la pornografía a causas externas o enteramente psicológicas. La comunidad médica _mainstream_ ha concluido que el porno no ha sido científicamente probado como la causa de algunos de los problemas que los propios usuarios confesos han dicho que tienen, pero ya que admitir la inhabilidad sexual de uno en público es un evento demasiado vergonzoso, ¿Por qué alguien haría eso a menos que estuviera demasiado consternado - encontrando la causa y eliminándola de su vida? ¿Es lógico que no buscaríamos ayuda a menos que el problema sea demasiado grande, no?

EasyPeasy te ayudará a deshacerte de la pornografía y convertirte en un ex-usuario feliz. Sin porno, masturbación usando pornografía, u orgasmos innecesarios. El único apoyo que podrías tener sería el toque, olor o esencia de tu pareja, en caso de tenerla. Como pan integral después de un bien desarrollado apetito, ya no querrás el jarabe de maíz con alto contenido de fructosa que el porno te ofrece. La evidencia es tan abrumadora que no necesitas de ninguna prueba; si martillo mi pulgar obvio que me dolería, no necesitas prueba de ello. El estrés al que te induce el porno tiene flujo en otros aspectos de tu vida, haciendo que muchos usuarios tengan que recurrir a drogas como los cigarros y el alcohol para poder lidiar con el estrés, y en algunas instancias incluso, considerar el suicidio.

El usuario también se hace ilusiones, como que los efectos del porno están exagerados. Cuando es todo lo contrario, ya que no hay duda de que el porno de internet es la mayor causa de disfunción eréctil y muchos otros problemas. ¿Cuántos divorcios crees que se han suscitado gracias al porno? No hay forma de saberlo, pero algunas búsquedas en foros de internet sugieren que el número de dichos divorcios está creciendo exponencialmente...

Hay un episodio de _Friends_ donde los chicos, quienes estaban recibiendo porno gratuito continuamente en su televisión, empezaban a preguntarse porque la chica que les llevaba la pizza no les preguntaba qué es lo que tenían en su ‘gran cuarto’. Cuando eres adicto, proyectas de forma invariable tus fantasías en mujeres reales. Imagina lo que una exposición descuidada o accidental a los lados más oscuros del porno de Internet podrían causarle a una persona que ya de por sí se encuentra en un punto de inflexión en su vida. Luchar contra estos pensamientos inducidos por porno será una forma muy grande de drenar su salud mental.

Aquí hay otro experimento; digamos que alguien viene hacia ti y dice que no necesariamente quiere tener un orgasmo, pero que realmente quiere tener sexo contigo, incluso tener una penetración. Quiere hacerlo por cuanto tiempo puedas y lo más que puedas hacerlo sin tener un orgasmo - aunque en caso de tenerlo, tampoco habría problema. Permíteme asegurarte que esta sería una experiencia sexual nueva y fenomenal, mil veces mejor que cualquier otra allá afuera. Que, por cierto, si te dan ese tipo de oferta, dale una oportunidad.

Pero te recuerdo, los efectos del lavado de cerebro nos hacen tender a pensar como aquel hombre que, al caer por un edificio de cien pisos, y mientras pasa por el piso cincuenta, es citado diciendo: _“¡Tan lejos, tan bien!”_ Pensamos que, ya que nos hemos salido con la nuestra por tanto tiempo, una sesión más no hará mucha diferencia. Velo de otra forma, el ‘hábito’ es una cadena continua de por vida, con cada sesión creando una necesidad por la siguiente. Cuando empiezas el hábito, enciendes una chispa en la mecha de una bomba. El problema es que _no sabes por cuánto tiempo más estará encendida_. Y cada sesión que tienes te acerca más a la explosión de esta bomba. **¿CÓMO SABES QUE LA PRÓXIMA VEZ NO EXPLOTARÁ?**

## Siniestras Sombras Negras

A los usuarios les resulta muy difícil de creer que la pornografía realmente cause esos sentimientos de inseguridad al salir de casa, después de un día contencioso en el hogar o en el trabajo. Los no-usuarios no sufren de estos sentimientos, es el porno el que causa esos sentimientos.

Otra de las grandes ventajas de dejar la pornografía es el poder librarnos de estas siniestras sombras negras en la parte trasera de nuestras mentes. Todos los usuarios saben que son tontos consigo mismos al cerrar sus mentes 	ante los enfermizos efectos del porno. Durante la mayor parte de nuestras vidas es algo automático, pero estas sombras siempre están acechando nuestras mentes subconscientes, por debajo de la superficie. Varios de los maravillosos beneficios de dejar el porno son conscientes, como lo son el dejar de perder el tiempo o la pura estupidez de dejar de hacerle el amor a una imagen bidimensional. 

Los últimos capítulos de este libro se encargan de dar una idea sobre las múltiples ventajas de ser un no-usuario, pero en aras de la equidad, es necesario nivelar la balanza. Así pues, la próxima página enlista las múltiples ventajas de ser un usuario, las ventajas de consumir pornografía.
