# El método de la fuerza de voluntad {#el-metodo-de-la-fuerza-de-voluntad}

La sociedad ya ha aceptado el hecho (o en este caso, la falacia) de que es muy difícil dejar de ver porno. Hay varios libros y foros que te aconsejan sobre cómo parar, recursos que generalmente comienzan diciéndote lo difícil que es. Pero la verdad es que es ridículamente fácil. Entiendo que llegues a cuestionar esta afirmación, pero considera esto primero. Correr un kilómetro y medio en cuatro minutos es difícil, y tendrías que pasar años de duro entrenamiento para conseguirlo. E incluso entonces puede que no tengas la capacidad física para hacerlo. 

Sin embargo, todo lo que tienes que hacer para dejar el porno es dejar de verlo y/o no masturbarte más. Nadie te obliga a masturbarte (aparte de ti mismo) y, a diferencia de la comida o el agua, no es necesario para sobrevivir. Así que, si quieres dejar de hacerlo, ¿por qué debería ser difícil? De hecho, no lo es. Son los usuarios los que se lo dificultan a sí mismos mediante el uso de la fuerza de voluntad o cualquier otro método que los obligue a sentir que están haciendo algún tipo de sacrificio. Vamos pues a considerar estos métodos.

Nadie decide convertirse en usuario, solo ‘experimentamos’ con revistas o sitios porno. Y ya que (dejando de lado nuestro clip favorito) dicho material es horrible (sí, horrible), estamos convencidos de que podemos parar cuando nos plazca. Al principio, vemos esos primeros clips ‘buenos’ cuando queremos y/o en ocasiones especiales. Y antes de que nos demos cuenta, no solo estamos visitando estos sitios regularmente y masturbándonos cuando queremos — nos masturbamos con ellos diariamente. El porno se ha convertido en parte de nuestras vidas, haciendo que nos aseguremos de que haya conexión a internet donde quiera que vayamos. Empezamos a creer que tenemos derecho al amor, al sexo, al orgasmo y a todas las propiedades del porno que alivian el estrés. Pero nunca caemos en cuenta de que el mismo clip y los mismos actores dejaron de proporcionar el mismo grado de excitación hace mucho, por lo que empezamos a luchar subconscientemente contra la línea roja para evitar el “porno malo.” Solo recuerda que, de hecho, la masturbación y el porno no mejoran nuestras vidas sexuales ni reducen el estrés, sino que más bien nos adecuan a creer que no podemos disfrutar de nuestras vidas ni manejar el estrés sin un orgasmo. 

Por lo general, toma mucho tiempo darse cuenta de que estamos enganchados porque tenemos la ilusión de que los usuarios ven porno porque les gusta — y no porque lo _**necesiten**_. Cuando no estamos “disfrutando” del porno que vemos (cosa que nunca podemos hacer a menos que no se añada novedad o valores de shock al video en sí, o que no escalemos en tipos de géneros), caemos bajo la ilusión de que podemos parar cuando queramos. Esta es una trampa de confianza: _“no me gusta el porno, así que puedo parar cuando quiera.”_ Una trampa extraña, ya que parece que nunca quieres parar.

No es hasta que intentamos detenernos que nos damos cuenta de que existe un problema. Los primeros intentos suelen ser prematuros — empiezan gracias a que conociste una nueva pareja y notaste que no es “lo suficiente” después de su primera cita, entre otros casos. Otra razón común es notar algún efecto extraño en nuestra salud.

Sea cual sea la razón, el usuario siempre espera una situación estresante, ya sea de salud o de sexo, para dejarlo. Tan pronto se detiene, el pequeño monstruo empieza a saciar su dosis. Es entonces cuando el usuario empieza a buscar algo que pueda bombear dopamina a su cerebro de nuevo, sean cigarrillos, alcohol, o su favorito – el porno en internet. Empieza a desear de nuevo su harem, el cual se encuentra a solo un clic de distancia. Ya no tienes que bajar al sótano por una revista, es virtual y accesible desde cualquier lugar. Sin embargo, es cuando su pareja o amigos están cerca, donde ya no tienen acceso a su harem virtual, lo que los hace sentirse aún más angustiados.

Además, si el usuario llega a toparse con material de índole científico o con comunidades en línea, empezará un juego de jalar la cuerda en su cabeza, resistiendo las tentaciones de un lado y sintiéndose privado del otro. A su vez, su forma de aliviar el estrés ya no está disponible, por lo que sufre de un golpe triple. El posible resultado después de este período de tortura es que se comprometa consigo mismo, y diga: _“lo voy a reducir”_ o _“he elegido el momento equivocado”_ o quizás _“esperaré a que el estrés se haya ido de mi vida.”_ Sin embargo, una vez que el estrés se ha ido de su vida, no hay razón para dejar el porno, por lo que el usuario decide posponer su intento de dejarlo hasta el próximo periodo de estrés que tenga.

Aunque obvio, no existe un momento adecuado para dejarlo, porque la vida, para la mayoría de la gente, se vuelve más estresante con el pasar del tiempo. Dejamos la protección de nuestros padres, nos asentamos por fin en nuestros hogares, llegan las hipotecas, engendramos hijos y conseguimos trabajos que requieren de más responsabilidad, etc. Sin embargo, la vida del usuario no puede volverse menos estresante porque lo que realmente hace el porno es causar más estrés. Cuanto más rápido cruce la línea roja, el usuario se vuelve más angustiado y adquiere una mayor dependencia (ilusoria) al porno.
	
De hecho, eso de que la vida se vuelve más estresante es incluso una ilusión. Es el porno — o cualquier otro apoyo similar — el que crea esa ilusión. Esto se discutirá con más detalle más adelante, pero después de estos fracasos iniciales, el usuario suele empezar a confiar en la posibilidad de que un día se despierte y no quiera masturbarse o usar porno, etc. Esta esperanza normalmente se enciende con las historias que escuchan de otros ex-usuarios: _“no me lo tomé en serio hasta que desarrollé disfunción, entonces no quería ver más porno y dejé de masturbarme.”_

No te engañes, solo indaga a fondo estos rumores y descubrirás que nunca son tan simples como aparentan. Por lo general, el usuario ya se había estado preparando para detenerse y simplemente utilizó ese ‘incidente’ como trampolín. Es normal encontrarse que, en el caso de las personas que se detienen _“así no más,”_ sufrieron de un ‘espanto’ primero; tal vez los descubrió su pareja, tal vez encontraron que se excitaban mucho más con material que no correspondía con el de su orientación sexual, o quizá se espantaron al descubrir que sufrían de disfunción sexual. _“¡Hey, pero es justo el tipo de persona que soy!”_ _**Deja. De. Engañarte.**_ Hazlo claro en tu mente, no vas a dejar la pornografía a menos que **TÚ** te lo propongas.

Ahora, indaguemos con mayor detalle sobre por qué el MFV lo vuelve tan complicado. Durante la mayor parte de nuestras vidas adoptamos el enfoque de _“me detendré mañana.”_ En momentos extraordinarios, algo va a desencadenar un intento de parar. Puede que sean preocupaciones sobre salud, sobre virilidad o por un rotundo autoanálisis, con el que nos damos cuenta de que en realidad no lo disfrutamos. Cualquiera que sea la razón, empezamos a considerar los pros y los contras del porno. El sexo está divido en tántrico (toque, olor, voz) y propagativo (orgasmo); **OJO**, esta es una de las claves principales para abrir nuestra mente. Sin esta importante distinción, habrá confusión, seguida de fracaso. Entonces, ya que evaluamos racionalmente estos detalles, descubrimos lo que hemos sabido toda nuestra vida, y llegamos a la misma conclusión de siempre: **“¡DEJAR DE VER PORNO!”**

Si te pusieras a contar las ventajas de dejar la pornografía, y las comparas con las ventajas de seguir consumiéndola, el conteo total de puntos para dejarlo superaría **con creces** cualquier “desventaja.” Solo compáralo con la apuesta de Pascal, al dejarlo no estás perdiendo nada, tienes más posibilidades de ganar y más posibilidades de no perder a lo grande. Pero claro, aunque el usuario sabe que estará mejor siendo un no-usuario, la creencia de que están haciendo un sacrificio los hace cuestionar bastante la decisión. Es una ilusión, pero una muy poderosa. No saben por qué, pero los usuarios tienen la creencia de que, durante los buenos y malos tiempos de la vida, las sesiones parecen ser de ayuda. Incluso antes de comenzar su intento, el lavado de cerebro social, reforzado por el lavado de cerebro de su propia adicción, se combina entonces con el lavado de cerebro más poderoso de todos, el que dicta lo difícil que es “renunciar a la pornografía.”

Hay demasiadas historias sobre personas que han dejado la pornografía durante varios meses y que todavía anhelan desesperadamente una sesión; relatos de gente que renuncia al porno de forma infeliz, y que pasan el resto de sus vidas en descontento, anhelando poder tener una sesión. Te estoy hablando acerca de usuarios que se detienen durante muchos meses o años, que viven vidas felices y que terminan por echar un vistazo al porno, enganchándose de nuevo. Es probable que muchos de estos usuarios recaídos conozcan a varios usuarios que se encuentren en las etapas más avanzadas de esta enfermedad, visiblemente destruyéndose a sí mismos y claramente no disfrutando de la vida — pero es curioso cómo, aun así, lo siguen utilizando. Vaya, es incluso probable que estos usuarios recaídos hayan pasado por esta tortura. 

Estos usuarios, en vez de empezar con una sensación de: _“¡Genial! ¿Has oído las noticias? ¡Ya no necesito ver porno!”_, empiezan con sentimientos de perdición y tristeza — como si trataran de escalar el Everest — creyendo erróneamente que una vez que el pequeño monstruo se engancha a ti, estás enganchado de por vida. Incluso, hay bastantes usuarios que comienzan este intento pidiendo disculpas a sus respectivas novias o esposas. _“Mira, estoy tratando de dejar el porno. Probablemente estaré irritable durante las próximas semanas, así que trata de tener un poco de paciencia conmigo.”_ Muchos de estos intentos están condenados a fracasar incluso antes de empezar.

Ahora, supongamos que el usuario sobrevive unos días sin tener una sesión, que están recuperando su excitación normal y están empezando a recuperarse. No han abierto sus sitios favoritos y consecuentemente, están experimentando dopamina por estímulos normales de los que previamente se habían perdido. Sin embargo, las razones por las que decidieron detenerse en primer lugar están desapareciendo rápidamente de sus mentes, como cuando ves un grave accidente de carretera mientras conduces. Quizá te haya retrasado por un tiempo, pero de todas formas pisas el acelerador a fondo y sigues con tu vida.

En la otra trinchera, está el pequeño monstruo, el cual todavía no ha sido alimentado. No hay dolor físico o algo similar a cuando empiezas a salir de un resfriado. No dejas de trabajar, ni te deprimes, te alegras. Sin embargo, el usuario le da cabida en su mente, y todo lo que sabe es que quiere una sesión lo más pronto posible. El pequeño monstruo lo sabe también, por lo que pone en marcha el gran monstruo del lavado de cerebro, haciendo que la misma persona que unas horas o días antes estaba enumerando todas las razones para detenerse, ahora busque desesperadamente cualquier excusa para empezar de nuevo. El usuario empieza a decir cosas como:

* _“La vida es demasiado corta, podría estallar una bomba, un autobús me puede atropellar mañana. Y, de todas formas, puedes generar una adicción a cualquier cosa hoy en día.”_
* _“He elegido el momento equivocado.”_
* _“Debí de haber esperado hasta después de Navidad; después de mis vacaciones / exámenes; después de este evento estresante en mi vida.”_
* _“No puedo concentrarme, me estoy poniendo irritable y de mal humor, y ni siquiera puedo hacer mi trabajo adecuadamente.”_
* _“Mi familia y amigos no me quieren de todas formas. Acéptalo de una buena vez, por el bien de todos, tengo que empezar de nuevo. Soy un adicto al sexo y no hay manera de que vuelva a ser feliz sin un orgasmo.”_
* _“Nadie puede sobrevivir sin sexo.”_ (Esto puede ser producto de la influencia de buenas personas que no conocen la diferencia entre el sexo tántrico y propagativo)
* _“Sabía que esto iba a pasar, ahora mi cerebro está “desensibilizado” debido a mi consumo excesivo de pornografía en el pasado. La desensibilización “nunca” podrá ser removida del cerebro.”_

En esta etapa, el usuario suele ceder ante sus deseos. Enciende el navegador, y su esquizofrenia aumenta. Por un lado, se siente tremendamente aliviado de terminar con el antojo, después de que el pequeño monstruo finalmente consigue su dosis; pero, por otro lado, el orgasmo se siente terrible y el usuario no puede entender por qué lo está haciendo. Es por esto por lo que el usuario piensa que carece de fuerza de voluntad, pero no es por falta de voluntad, todo lo que ha hecho es cambiar de opinión y tomar una decisión perfectamente racional usando la información que tiene a la mano.

_“¿Cuál es el punto de ser saludable o rico si eres miserable?”_

¡Absolutamente ninguno! Es mucho mejor tener una vida agradable y corta que una larga y miserable. Afortunadamente, esto no es así para el no-usuario, ya que su vida es infinitamente más agradable que la de un usuario. La miseria que sufre el usuario no se debe a los dolores de abstinencia — aunque al principio son estos los que desencadenan su miseria — la verdadera agonía reside en el _tira-y-afloja_ mental causado por la duda y la incertidumbre. Debido a que el usuario comienza sintiendo que está haciendo un sacrificio, entonces empieza a sentirse privado, lo cual a su vez genera estrés.

Otro de los momentos más estresantes para los usuarios es cuando el cerebro les dice que _“tengan una miradita”_; haciendo que se quieran retractar de su decisión tan pronto como se detuvieron. Pero debido a que se detuvieron, no pueden tener esta ‘miradita,’ cosa que los hace sentirse aún más deprimidos y que comiencen el ciclo de nuevo. Otro factor que hace tan difícil dejar el porno es esperar a que algo suceda. Si tu objetivo es aprobar un examen de conducción, tan pronto como lo hayas aprobado, ya has logrado tu objetivo. Pero bajo el MFV la narrativa interna es: _“si puedo pasar el tiempo suficiente sin ver pornografía, la necesidad de verla eventualmente desaparecerá.”_ Puedes comprobarlo en foros en línea, donde los adictos hablan de sus rachas o días de abstinencia.

Como se ha dicho anteriormente, la agonía que sufre el usuario es mental y se debe a la incertidumbre. Aunque no hay dolor físico, esta incertidumbre tiene efectos poderosos. Ahora miserable e inseguro, el usuario está lejos de olvidar su adicción, lleno de dudas y temores:

* “¿Cuánto tiempo durará el anhelo por porno?”
* “¿Seré feliz otra vez?”
* “¿Podré levantarme de la cama en la mañana?”
* “¿Cómo voy a lidiar con el estrés en el futuro?”

El usuario está esperando que las cosas mejoren, pero mientras siguen deprimidos, su harem se está volviendo cada vez más preciado. De hecho, algo _está_ sucediendo, pero inconscientemente; si puede sobrevivir semanas sin abrir el navegador, el pequeño monstruo (el anhelo por dopamina) desaparecerá. Sin embargo, y como se dijo anteriormente, los dolores de abstinencia de dopamina y opioides son tan leves que el usuario ni siquiera es consciente de ellos. Durante ese periodo, muchos de los ya ex-usuarios sienten que lo han “dejado” por completo, y, por lo tanto, echan un vistazo para probárselo, enviándolos de vuelta por el tobogán de agua. Habiendo suministrado dopamina al cuerpo, ahora hay una pequeña voz en la parte trasera de su mente diciendo _“quieres otra.”_ Claro que lo dejaron, pero volvieron a engancharse.

De niño solías ver dibujos animados y, según la neurociencia, formaste vías neuronales (DeltaFosB) para ellos. Si deseas disuadir a un niño de ver caricaturas, estudiarías si esas vías neuronales todavía existen, y le preguntarías a los adultos por qué ya no les gusta ver sus dibujos animados favoritos de la infancia. En primera, para un adulto, hay entretenimiento más interesante y vasto disponible, y, en segundo lugar, los dibujos animados simplemente dejaron de retener la misma magia en ti. Con el MFV solo le estás negando al niño la caricatura, pero con EasyPeasy también te estás asegurando de que no vea ningún valor en ella. Y dime, ¿cuál es mejor?

El usuario no suele entrar en otra sesión de inmediato, pensando, _“¡no quiero engancharme de nuevo!”_ Así que permite que transcurran horas, días o incluso semanas antes de tener otra sesión. El entonces ex-usuario dice: _“bueno, no me enganché, así que puedo tener otra sesión con seguridad.”_ Y bueno, ha vuelto a caer en la misma trampa que cuando empezó y ya está en la pendiente resbaladiza.

Los usuarios que tienen éxito con el MFV suelen encontrarlo largo y difícil porque el problema principal es el lavado de cerebro. Mucho después de que la adicción física haya muerto, el usuario sigue deprimido. Al final, después de sobrevivir a esta larga tortura, empiezan a darse cuenta de que no van a ceder, dejan de deprimirse y aceptan que la vida continúa y que es más agradable sin el porno. Hay muchos más fracasos que éxitos, y algunos de los que tienen éxito pasan por su vida en estado de vulnerabilidad, con una parte del lavado de cerebro que les dice que el porno, de hecho, les da un estímulo positivo. Esto explica por qué muchos usuarios que lo han dejado durante mucho tiempo vuelven a empezar más tarde.

Muchos ex-usuarios se regalan a sí mismos una ‘sesión especial’ de vez en cuando, o a veces se someten a una sesión para convencerse de lo fuerte que es su autocontrol. Eso es exactamente lo que hacen — pero en cuanto terminan la sesión, la dopamina empieza a desaparecer y una vocecita en el fondo de su mente empieza a empujarlos a tener otra. Si deciden participar, parece que todavía están bajo control, no se someten a ningún material shockeante, no escalan en géneros ni buscan algo novedoso, así que dicen: _"¡Maravilloso! Aunque no lo estoy disfrutando, no me voy a enganchar. Después de Navidad / estas vacaciones / este trauma, lo dejaré."_ Poco saben ellos, que los toboganes de su cerebro se han engrasado aún más.

Demasiado tarde, ¡ya están enganchados! La trampa de la que lograron salir con mucho esfuerzo se ha cobrado de nuevo su víctima.

Como se ha dicho anteriormente, el disfrute no entra en juego. Nunca lo ha hecho. Si viéramos porno para nuestro disfrute, nos quedaríamos en los sitios de porno más tiempo aun después de tener un orgasmo. En cualquier caso, una mejor manera de autocomplacerse es a partir de nuestros recuerdos. Asumimos que disfrutamos del porno en internet solo porque no podemos creer que seamos tan estúpidos como para volvernos adictos si no lo disfrutamos. La mayoría de los usuarios no tienen ni idea sobre estímulos supernormales, sobre la búsqueda de shock o de novedad, e incluso después de leer sobre ello, no creen que su uso esté motivado por el cableado de sus circuitos de recompensa. Por eso, gran parte del porno es subconsciente, si fueras consciente de los cambios neurológicos y tuvieras que justificar la cantidad de tiempo y dinero que perderás en el futuro, incluso la ilusión de disfrute desaparecería.

Cuando intentamos bloquear de nuestra mente el lado malo, nos sentimos estúpidos. Pero si tuviéramos que afrontarlo, ¡sería intolerable! Si pudieras observar a un usuario en acción, verías que solo es felices cuando no es consciente de que está consumiendo. Una vez que es consciente, tiende a sentirse incómodos y a tener remordimiento. ¡El porno alimenta al pequeño monstruo, por lo que al purgarlo de tu cuerpo junto con el lavado de cerebro (el gran monstruo), no tendrás necesidad ni deseo de ver porno!
