# ¡Cuidado con reducir tu consumo! {#cuidado-con-reducir-tu-consumo}

Muchos usuarios recurren a la reducción como un paso anterior a dejar el porno, o como un intento por controlar al pequeño monstruo. Muchos incluso recomiendan la reducción o las "dietas pornográficas" como un alivio ante su lucha. Pero utilizar la reducción como paso previo para dejar el porno es _**fatal**_. Son estos intentos de reducción los que nos mantienen en la trampa durante el resto de nuestras vidas. Y por lo general, reducir tu consumo trae consigo una inminente derrota en todo intento por dejarlo. Tras varias horas o días de abstinencia, los usuarios dicen algo como:

> "No puedo afrontar la idea de irme a dormir sin visitar mi harem, así que a partir de ahora solo consumiré porno una vez cada cuatro días o purgaré mi colección de 'porno malo.' Si puedo seguir esta dieta pornográfica, podré mantener mi consumo así de corto, o reducirlo aún más."

Solo para que les sucedan cosas terribles:

* Están atrapados entre lo peor de ambos mundos: siguen siendo adictos a la pornografía en internet, mientras mantienen vivo al monstruo no solo en su cuerpo, sino en su mente.
* Se quedan a la espera de la siguiente sesión durante el resto de su vida.
* Anterior a reducir su consumo, cada vez que querían visitar su harem, encendían su navegador y aliviaban parcialmente sus dolores de abstinencia. Ahora, además de los tirones de la vida, se infligen a sí mismos los dolores de abstinencia, los cuales tendrán que sufrir durante la mayor parte de sus vidas, lo que los hace aún más miserables y malhumorados.
* Mientras seguían complaciéndose constantemente, no llegaban a disfrutar de la mayor parte de las sesiones, y tampoco se daban cuenta de que estaban utilizando estímulos supernormales. Se convirtió en algo automático, ya que la única visita al harem que se disfrutaba era una después de un periodo largo de abstinencia. Y ahora que esperan una hora más para cada visita al harem, "disfrutan" mucho más de cada una. Cuanto más tiempo se espera, más "agradable" parece ser cada sesión, ya que el "disfrute" de una sesión no radica en la sesión misma, sino el fin de la agitación causada por el deseo de tener una sesión. Cuanto más largo sea el sufrimiento, más "agradable" será cada sesión.

La principal dificultad para dejarlo no radica en la adicción neurológica, la cual es fácil de vencer. De hecho, los usuarios dejarán de hacerlo sin dificultad en varias ocasiones: la muerte de un ser querido, asuntos familiares o laborales, etc. Podrían pasar, digamos, diez días sin acceso y no les molestaría. Pero si pasaran los mismos diez días cuando podrían haber tenido acceso a su harem, ya se habrían arrancado todos los pelos de su cabeza.

Muchos usuarios incluso tendrán oportunidades para ver porno durante su jornada laboral y se abstendrán sin problema: podrían pasar por un Victoria's Secret, a través de piscinas y demás sin mayor inconveniente. Se abstendrán si tienen que dormir en el sofá temporalmente para hacer espacio a una visita, o si ellos mismos están de visita. Incluso en los bares _"tabledance"_ o en las playas nudistas no ha habido problemas. El hecho es que los usuarios estarán casi encantados de que alguien o algo les diga que no pueden ver porno. De hecho, los usuarios que quieren dejarlo obtienen un placer secreto al pasar largos periodos sin visitas a su harem con este método, lo que les da la esperanza de que quizás algún día no quieran ver porno nunca más.

Pero el verdadero problema al dejar de consumirlo radica en el lavado de cerebro; en la ilusión de que el porno en internet es una especie de apoyo o recompensa y que la vida nunca será igual sin él. Lejos de alejarte de tu adicción, lo único que consigue la reducción es dejarte inseguro y miserable, convenciéndote de que lo más preciado en esta tierra es el nuevo video que te perdiste, y de que no hay forma de que vuelvas a ser feliz sin verlo.

No hay nada más patético que el usuario que intenta reducir su consumo. Sufriendo la ilusión de que cuanto menos porno vean, menos querrán visitar los sitios porno. Al contrario, cuanto menos porno vean, más longevos y fuertes serán los dolores de abstinencia que lleguen a sufrir, y más "disfrutarán" del alivio que les produce esa sesión especial. Sin embargo, al final se darán cuenta de que su género favorito ya no les gusta. Pero eso no los detendrá, si los sitios porno se dedicaran a una sola estrella o género, ningún usuario iría más de una vez.

¿Difícil de creer? ¿Cuál es el peor momento de autocontrol que un usuario de dieta pornográfica siente? Esperar cuatro días para tener un orgasmo. Y ahora, ¿cuál es el momento más preciado para la mayoría de este tipo de usuarios? Así es, ¡el mismo orgasmo después de esperar cuatro días! ¿Realmente crees que te masturbas para disfrutar del orgasmo, o por la explicación más racional: porque necesitas aliviar los dolores de abstinencia con la ilusión de que tienes derecho a ello?

Remover el lavado de cerebro es esencial para eliminar las ilusiones sobre el porno antes de extinguir tus deseos con esa última sesión. A menos que hayas eliminado la ilusión de que lo disfrutas antes de cerrar la ventana de incógnito, no hay manera de que puedas comprobar que no necesitas del porno sin volver a engancharte. Cuando pases a través de tu barra de marcadores y tu galería, pregúntate dónde está la gloria en hacerlo. Tal vez creas que solo ciertos videos son de buen gusto, como los géneros habituales o tus videos favoritos. Si es así, ¿por qué molestarse en ver otros videos o géneros entonces? ¿Solo porque adquiriste el hábito? ¿Vamos, por qué alguien habría de ensuciar su cerebro con porno de forma habitual, desperdiciando su capacidad cognitiva? Nada es diferente después de un mes, ¿por qué debería ser diferente con un vídeo porno?

Puedes probar esto tú mismo: encuentra y ve ese increíble vídeo que viste el mes pasado para probar que es diferente. Luego, establece un recordatorio y ve el mismo video después de un mes sin porno. Va a tocar (casi) los mismos puntos que tocó la vez pasada. El mismo video será diferente solo después de un evento social en el que seas rechazado o después de salir con una potencial pareja. La razón es que el adicto nunca podrá ser plenamente feliz si el pequeño monstruo permanece insatisfecho.

¿Dónde queda la satisfacción entonces? Los usuarios se sentirán miserables si no pueden aliviar sus síntomas de abstinencia. La diferencia entre ver o no ver porno es la diferencia entre ser feliz o miserable. Por eso el porno en internet parece ser mejor. Incluso los usuarios que entran en sus sitios a primera hora de la mañana para ver porno son miserables, tanto si lo ven como si no.

La reducción no solo no funciona, sino que es la peor forma de tortura. No funciona porque inicialmente el usuario espera que al reducir el hábito con el que ven porno, reducirá su deseo de ver porno. Pero no es un hábito, sino una adicción. Y la naturaleza de cualquier adicción es querer más y más, no menos y menos. Por lo tanto, para reducir su consumo, el usuario tiene que ejercer su fuerza de voluntad y su disciplina por el resto de su vida. Por lo que dejar de ver porno significa fuerza de voluntad y disciplina para siempre. Dejarlo de tajo es mucho más fácil y menos doloroso, y hay decenas de miles de casos en los que la reducción ha fracasado.

El problema de dejar el porno no es la adicción a la dopamina, que es fácil de sobrellevar. Es la creencia errónea de que el porno da placer, provocada inicialmente por el lavado de cerebro recibido antes de empezar a consumir, reforzado además por la adicción real. Lo único que hace la reducción es reforzar aún más la falacia, hasta el punto de que el porno domina sus vidas por completo y les convence de que lo más preciado del mundo es su adicción.

El puñado de casos que han tenido éxito con este método lo han conseguido gracias a un periodo relativamente corto de reducción, seguido de un largo y tortuoso periodo de abstinencia. Estos usuarios lo dejaron a pesar de la reducción, no a gracias a ella. Todo lo que hicieron fue prolongar la agonía, además de que sus intentos fallidos los dejaron destrozados por los nervios y aún más convencidos de que estaban enganchados de por vida. Esto suele ser suficiente para que vuelvan a su página favorita como recompensa o como un apoyo, o, mejor dicho, a empezar otro largo intento por dejar la pornografía por completo.

A pesar de todo esto, el recortar tu consumo ayuda a ilustrar la inutilidad del porno, ya que ilustra claramente que las visitas al harem no son tan agradables después de largos periodos de abstinencia. Todo lo que estás haciendo es golpear tu cabeza contra un muro de ladrillos (sufriendo dolores de abstinencia) solo para sentir el alivio por dejar de hacerlo. Por lo que al final, te quedas con estas opciones:

1. Recortar tu consumo de por vida (que de todos modos no podrás hacer) y sufrir una tortura autoimpuesta.
2. Torturarte cada vez más, hasta la muerte. Lo cual no tiene sentido.
3. O ser amable contigo mismo, y solo dejar de ver porno.

El otro aspecto que demuestra la reducción es que no existen las visitas ocasionales. El porno en internet es una reacción en cadena que durará el resto de tu vida, a menos que hagas un esfuerzo positivo por romperla.

**Recuerda: recortar tu consumo solo te hará miserable, para siempre.**
