# Es solo una “miradita”... {#es-solo-una-miradita}

Tener “solo una miradita” es un mito que debes sacar de tu cabeza:

* Es _“solo una miradita”_ la que nos hace iniciar en primer lugar.
* Es _“solo una miradita”_, la cual usamos para levantarnos en una situación difícil o en una ocasión especial, lo que da por terminados nuestros intentos por dejar el porno, incluso antes de iniciar. 
* Es _“solo una miradita”_ la que, después de haber derrotado la adicción, nos hace volver a la trampa de nuevo.

Los efectos posteriores a la adicción al porno son horribles si no se detiene de la forma correcta, pero estos efectos convencerán de forma ilusoria al usuario de que no podrá engancharse de nuevo - sin embargo, y con esa _miradita_, ya es algo seguro; volverán a engancharse. El usuario siente que algo que lo hace sentir tan miserable y culpable no debería tener el poder de volver a hacer que se enganche, pero lo hace. ¿Por qué?

Es esa idea de tener ‘una sesión especial’ la que ocasionalmente previene a los usuarios de detenerse por completo; esa sesión que tienes después de tu largo viaje de negocios, después de un duro día en el trabajo, de esa pelea con tus hijos, o de ese incidente donde tu pareja rechazo tener sexo contigo. Ten esto **firme** en tu mente, no hay tal cosa como ‘solo una miradita’. Es una reacción en cadena que durará el resto de tu vida, a menos que la rompas. Es el mito de la sesión _inusual y especial_ la que mantiene a los usuarios deprimidos después de detener su adicción. Así que, por favor, hazte ya el hábito de nunca ver este tipo de sesiones como algo ‘menor’ o especial, es una fantasía. Cuando pienses en porno, solo verás una vida asquerosa que se basa en gastar eones detrás de una pantalla, solo para tener el privilegio de autodestruirte mental y físicamente; una vida de esclavitud. No es un crimen si tus erecciones no son cien-por-ciento fiables, pero si lo es cuando decides sacrificar una vida de felicidad a largo plazo por una vida de placeres a corto plazo. 

Esta bien, es entendible que no se te ocurra nada que hacer para poder llenar ese vacío; siendo realistas, no es algo que se pueda solucionar siempre y en cada instancia por el resto de nuestras vidas. Podemos planear algo para sobrellevarlo en su mayor parte, pero a veces simplemente sucede. Y recuerda que con o sin porno, habrá buenos y malos momentos. Pero tenlo por seguro en tu cabeza, llenar ese vacío con porno no es una solución viable. En esos momentos, considera que te encuentras en una encrucijada y puedes escoger ir hacia una vida llena de miseria, o simplemente no hacerlo. Quítate la venda de los ojos por un momento; ¿no soñarías con tomar puro y crudo cianuro sólo porque te guste el sabor a almendras, o sí? Así que deja de castigarte con la ilusoria, ocasional sesión ‘especial’. Pregúntale a un usuario con problemas: _“Si tuvieras la oportunidad de volver a un tiempo antes de engancharte ¿Volverías a hacerlo?”_ Inevitablemente, la respuesta será y sigue siendo: _“¡Debes de estar bromeando!”_ Curioso porque, aun así, cada usuario puede tomar esa decisión todos los días de sus vidas. ¿Por qué no optan por ella? La respuesta es el miedo. Miedo a que no pueden parar o miedo a que la vida no será igual sin el porno. 

¡Deja de engañarte a ti mismo! Tú puedes hacerlo, cualquiera puede. Es ridículamente fácil, pero para poder hacerlo, hay ciertos fundamentos que aclarar primero: 

* No hay nada que perder, solo hay maravillosos beneficios.
* Nunca te engañes con esa sesión ‘especial’ o la idea de tener ‘solo una miradita’. No existe. En el porno, solo existe una vida de inmundicia y esclavitud. 
* Tú no eres un caso especial, es fácil dejar el porno y cualquier usuario puede dejarlo fácilmente también.

Muchos usuarios creen que son fuertemente adictos, o que tienen personalidades adictivas. Usualmente, esto pasa como resultado de leer cantidades excesivas de artículos relacionados a los aspectos neuro-cientificos del porno y las adicciones. Pero no existe tal cosa, nadie nace con la necesidad de masturbarse con porno antes de engancharse. Es la droga la que te engancha, no la naturaleza de tu carácter o personalidad. Es la naturaleza de los estímulos supranormales la que te hace creer que eso es así. Por eso es esencial remover esta creencia, porque si tú crees que eres un adicto, lo serás, y lo seguirás siendo incluso después de que el pequeño monstruo de tu cuerpo haya muerto. Por eso es esencial remover todo este lavado de cerebro primero. 
