# Los usuarios casuales {#los-usuarios-casuales}

Los usuarios más frecuentes tienden a envidiar al usuario “casual”. Ya sabes de cual hablo: _"No me molesta pasar toda una semana sin tener una sesión."_ Ojalá fuera así. Esto puede ser difícil de creer, pero ningún usuario disfruta de ser un usuario. Nunca olvides que: 

\  _Ningún usuario decidió convertirse en un usuario, en ningún tipo de usuario, por lo tanto_  
\  \  _Todos los usuarios se sienten estúpidos, por lo tanto_  
\  \  \  _Todos los usuarios tienen que mentirse a sí mismos y a los demás en un vano intento de justificar su estupidez._

Los fanáticos del golf se jactan de la frecuencia con la que juegan y quieren jugar, entonces, ¿Por qué los usuarios se jactan de lo poco que se masturban? Si ese es el verdadero criterio por el que se miden, seguramente no masturbarse en absoluto es el mayor logro, ¿No es así?

Si alguien te dijera: _“Puedo pasar toda la semana sin comer zanahorias y no me molesta en lo más mínimo”_, seguramente pensarías que estás hablando con un loco. Si yo disfrutara de comer zanahorias, ¿Por qué querría pasar toda una semana sin ellas? Y si no las disfrutase, ¿por qué haría tal declaración? Cuando un usuario hace un comentario sobre _sobrevivir_ una semana sin una sesión, está tratando de convencerse a sí mismo — y a ti — de que no tiene ningún problema. Pero no habría necesidad de hacer tal declaración si no tuvieran un problema.  Traducido, este comentario dice: _“Me las arreglé para sobrevivir una semana entera sin porno"_. Como todo usuario, lo dicen con la esperanza de que, después de esto, puedan sobrevivir el resto de sus vidas. ¿Te imaginas lo preciosa que debe ser esa sesión; aquella que estos usuarios casuales tienen después de haberse sentido privados durante toda una semana?

Esta es la razón por la cual los usuarios casuales están mucho más enganchados que los más frecuentes: no solo es mayor la ilusión de placer, sino que tienen menos incentivos para dejar el porno debido a que pasan menos tiempo consumiéndolo y, por lo tanto, son menos vulnerables a los riesgos de salud. Ocasionalmente, pueden llegar a experimentar disfunción sexual, pero como no están seguros de porque se origina, lo atribuyen a otros factores. Recuerda, el único placer que obtienen los usuarios se encuentra en la búsqueda de dopamina y el ciclo de abstinencia y alivio, como ya se ha explicado. El placer es una ilusión, solo imagina al pequeño monstruo como una comezón casi imperceptible de la que permanecemos inconscientes la mayor parte del tiempo.

Si tienes comezón, la tendencia natural es rascarte. A medida que los circuitos de recompensa se vuelven cada vez más inmunes a la dopamina y los opioides, la tendencia natural es que los usuarios lleven su orgasmo al borde, que escalen en géneros, empiecen a consumir más, busquen géneros y videos más nuevos e impactantes, etc. Sin embargo, hay cuatro factores principales que impiden que los usuarios empiecen a ver videos en cadena, que vean porno con más frecuencia, y que crucen la línea del _“usuario casual”_ al frecuente:

* **Tiempo:** La mayoría no puede permitírselo. No tienen el tiempo.
* **Salud:** Para aliviar la comezón, tenemos que consumir todo el material gratuito disponible, a veces un poco más.  Pero la capacidad para hacer frente a ese tipo de consumo varía con cada individuo, además depende de diferentes períodos y situaciones en sus vidas.  Esto actúa como una restricción automática; su cuerpo simplemente no aguanta toda la cantidad de contenido. 
* **Disciplina:** Impuestas por la sociedad, el trabajo del usuario, amigos y/o familiares; tal vez incluso por el propio usuario como resultado del tira-y-afloja natural que ocurre en la mente de cada usuario. Su mente conoce los riesgos, así que se contiene.
* **Imaginación:** La falta de imaginación minimiza el impacto, la novedad y otros valores del video que se ve, esto es subjetivo. El usuario simplemente no puede proyectarse en sus fantasías conforme al video y, por ende, su mente no valora al porno como un usuario frecuente. 

Es fácil pensar en los usuarios _'no-casuales'_ como débiles, incapaces de entender por qué otros pueden limitar su _'ingesta'_. Sin embargo, los usuarios frecuentes deben tener en cuenta que la mayoría de los usuarios casuales son simplemente incapaces de ver porno con tanta frecuencia, algo que requiere de mucha imaginación y resistencia.  Algunos de estos usuarios que consumen una vez a la semana, aquellos que los usuarios más empedernidos tienden a envidiar, son físicamente incapaces de hacer más, o porque su trabajo, la sociedad o su propio a volverse adictos no se lo permiten.

Sería prudente proporcionar algunas definiciones:

**El no-usuario:**

Alguien que nunca ha caído presa a la trampa, pero que no debe ser complaciente. No se han vuelto usuarios solo porque tienen suerte o por la gracia de Dios. Todos los usuarios estaban convencidos de que nunca se engancharían. Incluso, hay algunos no-usuarios que siguen teniendo una sesión de vez en cuando.

**El Usuario Casual:**

Del cual hay dos clasificaciones básicas:

* El usuario que ha caído en la trampa, pero no se ha dado cuenta — no envidies a estos usuarios. Simplemente están probando el néctar de la boca de la planta carnívora, y, con todo el peso de la probabilidad, pronto serán usuarios frecuentes.  Recuerda, así como todos los alcohólicos comenzaron como bebedores ocasionales, todos los usuarios comienzan de manera casual.
* El usuario que anteriormente era un usuario frecuente y que, por lo tanto, cree que no puede detener su consumo.  Estos usuarios son los más tristes de todos y se dividen en varias categorías, las cuales requieren ser comentadas por separado:

**El usuario de “una vez al día”:**

Si disfrutan de su derecho al orgasmo, ¿Por qué hacen uso del porno solo una vez al día?  Si pueden solo tomarlo o dejarlo, ¿Por qué molestarse en lo absoluto?  Recuerda, el 'hábito' es - en realidad – golpear tu cabeza contra una pared solo para sentir alivio al detenerte. Este usuario alivia sus dolores de abstinencia durante menos de una hora al día. Aunque sin saberlo, el resto del día lo pasa golpeando su cabeza contra una pared, haciendo esto durante la mayor parte de su vida. Lo consume una vez al día porque no puede arriesgarse a que lo atrapen, o a que su salud neurológica sea alterada. Es fácil convencer al usuario más empedernido de que no lo disfruta, pero es mucho más difícil convencer a uno casual. Cualquiera que haya intentado dejar la pornografía con su propia voluntad sabrá que es la peor tortura de todas, y hacerlo casi garantiza que te mantendrás como un adicto, por el resto de tu vida.

**El usuario rechazado:**

Este usuario exige su derecho al orgasmo, en todas sus formas, todos los días. Pero dado que su pareja sexual no siempre está feliz de cumplir con su petición, estos usuarios empiezan por usar pornografía para llenar este vacío. Sin embargo, al tomar este emocionante _'tobogán de agua'_ quedan atrapados en un ciclo de novedad, impacto, estímulos supranormales, etc. Lo más raro de todo es que están felices con el rechazo de su pareja, ya que proporciona una especie de excusa. Si la pornografía te hace más feliz que tu pareja, ¿Por qué molestarte en tener siquiera una pareja?  Esto los _‘libera’_ en su lugar. Hay ocasiones en las que buscan que su pareja les dé una excusa para aventurarse en los valles más oscuros de Internet.  

**El Usuario de la Dieta de Porno:**

También conocido como, _“Puedo parar cuando quiera.  ¡Lo he hecho miles de veces!”_

Si creen que hacer _dieta_ los pone de humor para ligar, ¿Entonces por qué siguen esa dieta, una vez cada cuatro días?  Nadie puede predecir el futuro, ¿Y si da la casualidad de que tu cita ocurra una hora después de tu sesión de porno programada? Además, si _'limpiar las tuberías'_ de vez en cuando es bueno para aliviar la tensión, ¿Por qué no limpiarlas todos los días? Se ha demostrado que la masturbación no es necesaria para mantener los genitales sanos, además de que la pornografía en Internet no es necesaria en absoluto. Incluso si ese es el caso, ningún _'gurú'_ o _‘artista del ligue’_ que haya leído sobre el daño neurológico recomendará una sobreestimulación con porno. La verdad es que todavía están enganchados. Aunque se deshicieron de la adicción física, todavía les queda el problema principal: el lavado de cerebro. Cada sesión, estos usuarios de dieta esperan que, al finalizar, se detengan de una vez por todas. Pero pronto vuelven a caer en la misma trampa. 

La mayoría de los usuarios envidian a este tipo de usuario, y piensan en la _"suerte"_ que tiene para poder hacer dieta, y para controlar su uso. Sin embargo, pasan por alto que la persona que hace dieta no está controlando su consumo; cuando lo está consumiendo, desearía no hacerlo. Pasan por el molesto proceso de detenerse, para luego comenzar a sentirse privados y caer en la trampa nuevamente, deseando no haberlo hecho. Obtienen lo peor de ambos mundos. Cuando uno lo analiza, esto es lo que viven los usuarios cada que tienen la oportunidad de tener una sesión – o sienten que se la merecen, o desean no merecerla. Es solo cuando uno se priva de su consumo, que la pornografía se vuelve preciada.  El síndrome de la 'fruta prohibida' es uno de los terribles dilemas que experimentan todos los usuarios. Nunca llegan a escapar de la trampa porque están deprimidos por un mito, una ilusión. ¡Solo hay una forma en que pueden escapar, y es dejando de preocuparse y entristecerse por la pornografía!

**El usuario que “Solo ve porno estático/manso/casero”:**

Sí, todo el mundo hace esto al principio, pero ¿No es sorprendente cómo el valor promedio de impacto en este tipo de contenido parece aumentar rápidamente y, antes de que nos demos cuenta, nos empezamos a sentir privados (generamos tolerancia)? Al porno estático solo le hace falta un valor de novedad más grande, así que pagamos al gaitero por una porción de grasa y así nos deslizamos por el tobogán de agua, directito al ciclo de resentimiento y culpa.  Lo peor que puedes hacer es usar las fotos de tu pareja (aun con su aprobación) para masturbarte. ¿Por qué?  Porque en el proceso estás reconfigurando a tu cerebro para que se induzca en la liberación de dopamina, impulsada con la búsqueda y variedad.  Químicamente, los toboganes de agua pornográficos en tu cerebro empiezan a acumular DeltaFosB, por lo que tendrás dificultades cuando estés con el/ella, en tiempo real.

La otra trampa que tiene esta categoría es la pornografía 'amateur' o 'casera'. La mayoría de este contenido es falso, planeado, y lo sabes. Además, no te detendrás a ver el primero que salte a la vista, sino que seguirás buscando, y buscando. Recuerda, no es solo el orgasmo lo que busca el cerebro; la novedad que experimentas durante la “caza” es lo que le da al tobogán de agua su chispa. El contenido pornográfico no es el problema, sea aficionado o profesional; son los sofocos de dopamina en el cerebro que provocan la acumulación de tolerancia y saciedad. La pornografía destruye el funcionamiento normal del cerebro, la masturbación confunde a la respuesta músculo-cerebral; el orgasmo inunda el cerebro con opioides y hace que el camino sea más fácil de seguir la próxima vez. Empiezas a buscar más dopamina, más opioides, y la adicción encuentra camino más fácilmente. 

**El usuario que "Ya se detuvo, pero que de vez en cuando se da el lujo":**

En cierto modo, estos usuarios son los más patéticos de todos. O pasan toda su vida creyendo que están siendo privados, o como acostumbra el usuario, ese vistazo ocasional se prolonga más de lo habitual. Se van deslizando de a poco en poco en el tobogán pornográfico, para que tarde o temprano se conviertan en usuarios más frecuentes. Han vuelto a caer en la misma trampa en la que cayeron en primer lugar.

 

Hay otras dos categorías de usuarios casuales. El primero es el tipo de usuario que se masturba con imágenes o clips de las últimas cintas sexuales o “nudes” de celebridades que aparecen en las noticias, o algo que _"se llevaron a casa"_ de su _"accidental"_ descuido en la escuela o el trabajo. Estas personas en realidad no son usuarios, pero sienten que se están perdiendo algo. Quieren ser parte de la acción, y es así como la mayoría de nosotros comenzamos. Así pues, la próxima vez, trata de observar como aquella celebridad que tanto te encantaba simplemente pierde la magia. Cuanto más _'inalcanzable'_ sea el objetivo de tu fantasía, más frustrante se vuelve la abstinencia al orgasmo.

La segunda categoría ha estado atrayendo más atención recientemente. Déjame explicarla con un caso compartido en línea.

Una mujer de profesión había estado leyendo historias pornográficas en Internet durante muchos años. Solía consumir este contenido con una frecuencia de más o menos una vez por noche. Ella era una dama de voluntad muy fuerte. La mayoría de los usuarios se preguntaban por qué querría detenerse en primer lugar, señalando alegremente que no había riesgo de desarrollar disfunción de cualquier tipo en su caso (esto es falso).  Ni siquiera estaba usando imágenes estáticas, las historias eran mucho más “dóciles” que cualquier material que ellos mismos usaran a diario.

Cometen el error de suponer que los usuarios casuales son más felices y tienen más control.  Pueden tener más control, pero ciertamente no son felices. En el caso de la mujer, no estaba satisfecha con su pareja ni con el sexo real, y el estrés y las tensiones diarias la irritaban mucho. Su más cercana y querida amiga no pudo entender qué le molestaba tanto.  Incluso si racionalizaba su miedo por no consumir porno y trataba de tener encuentros sociales con gente real, se encontraba a sí misma incapaz de disfrutar dichas relaciones que, invariablemente, involucran altibajos.  El centro de recompensas de su cerebro no podía hacer uso de los químicos desestresantes normales como resultado del derroche diario de dopamina. Esta regulación baja de los receptores de su cerebro la había vuelto melancólica en la mayoría de las circunstancias. Como todos, tenía un gran miedo al lado oscuro de la pornografía en línea, y al modo en que trataban a las mujeres en dicho contenido – al menos así fue antes de su primera vez. Eventualmente, fue víctima del lavado de cerebro social y probó su primer sitio. A diferencia de la mayoría de los que se enganchan a la primera y empiezan a ver videos en cadena - ella se resistió a seguir bajando por el tobogán, tan pronto como vio un video que se mostraba demasiado violento.

Lo único que disfrutas de consumir porno es terminar con el deseo que comenzó antes, ya sea el deseo físico casi imperceptible de tu cuerpo o la tortura mental de no poder rascarte la comezón. El porno en sí mismo es veneno, es por eso por lo que solo pareces disfrutar de la ilusión de placer tras varios días de abstinencia. De manera similar al hambre o la sed, cuanto más tiempo la sufras, mayor será el placer cuando finalmente se alivie. Al cometer el error de creer que la pornografía es solo un hábito, piensan: _“Si puedo mantener mi consumo en un nivel moderado o si solo lo uso en ocasiones especiales, mi cerebro y mi cuerpo podrán aceptar ese ritmo. Luego, puedo seguir consumiéndolo en esa frecuencia o reducirla aún más si así lo quiero”._

Hazte a la idea, el 'hábito' no existe. La pornografía es una droga adictiva, la tendencia natural de un adicto es aliviar los dolores de abstinencia, no soportarlos. Para mantener tu consumo en el nivel en el que te encuentras actualmente, sería necesario que ejercieras una enorme cantidad de disciplina y fuerza de voluntad por el resto de tu vida; a medida que el centro de recompensas de tu cerebro se vuelve inmune a la dopamina y los opioides, comienzas a querer más y más, no menos y menos.

Y a medida que la pornografía comienza a destruir gradualmente tu sistema nervioso, coraje, confianza y autocontrol, te vuelves cada vez más incapaz de evitar reducir el intervalo entre cada sesión. Es por eso qué, en los primeros días, podemos tomarlo o dejarlo.  Si recibimos una señal de que algo anda mal, mental o físicamente, simplemente nos detenemos. No envidies a esta mujer, cuando ves porno solo una vez cada veinticuatro horas parece ser la cosa más preciosa del mundo, convirtiendo la pornografía en una 'fruta prohibida'. Durante muchos años, esta pobre mujer había estado en el centro de un tira-y-afloja.

Se volvió incapaz de dejarlo, pero también le aterraba saltar de la lectura al video. Durante veintitrés horas y diez minutos de cada uno de esos días tuvo que luchar contra la tentación de inducirse en el tobogán, y la falta de sentimientos que tenía hacia su novio. Hizo falta una fuerza de voluntad tremenda para aguantar como lo hizo, hasta que finalmente la hizo llorar. Tales casos son raros, pero míralo lógicamente: O hay un placer genuino en la pornografía o no lo hay. Si lo hay, ¿Quién quiere esperar una hora, un día o incluso una semana? ¿Por qué deberías estar privado del placer mientras tanto?  Si no hay placer genuino, ¿Por qué molestarte en visitar tu harén en línea, entonces?

Aquí hay otro caso. Un hombre de que veía porno una vez cada cuatro días. Describe su vida de la siguiente manera:

> "Tengo cuarenta años, he sufrido DEIP (Disfunción Eréctil Inducida por la Pornografía) con mujeres reales e incluso cuando uso pornografía, que es la mayor parte del tiempo. Ha pasado un tiempo desde que tuve una erección completa. Antes de seguir la dieta pornográfica de “una-cada-cuatro”, solía dormir profundamente durante la noche después de mi sesión. Ahora me despierto cada hora de la noche y es todo en lo que puedo pensar. Incluso cuando duermo, sueño con mis clips favoritos. Los días después de mi sesión programada me siento bastante deprimido, la dieta consume toda mi energía. Mi pareja me deja en paz debido a mi mal temperamento, y si no puede irse, no me deja entrar a la casa. Aun si salgo a correr afuera, mi mente no lo deja, está obsesionada con la pornografía.  
El día programado empiezo a planificar mi sesión antes de que llegue la noche, y suelo irritarme mucho sí sucede algo que no va con mis planes. Incluso, me retiraría de cualquier reunión, o saldría temprano de mi casa o trabajo solo para llevar a cabo mi plan (solo para luego arrepentirme). No soy un tipo que discuta mucho, pero no dejo que cualquier tema o conversación banal me detenga. Además, recuerdo ocasiones en las que buscaba peleas tontas con mi pareja solo para que me dejara en paz.  Espero las diez de la noche, y cuando llega la hora indicada, mis manos empiezan a temblar incontrolablemente. No empiezo con el asunto de inmediato – en cada sesión que tengo, agregan contenido nuevo a la “tienda”, así que me doy el lujo de vagar un poco para encontrar lo que quiero.  Mi mente me dice que, dado que he pasado hambre durante cuatro días, merezco un clip "especial" que valga la pena el tiempo dedicado a buscar. Eventualmente me conformo con uno o dos videos, pero los dejo corriendo y prolongo el asunto para poder obtener el placer necesario para 'sobrevivir' durante los próximos cuatro días.”

Además de sus otros problemas, este pobre hombre no tiene idea de que se está premiando a sí mismo con veneno. Primero, sufre el 'síndrome de la fruta prohibida' y luego obliga a su cerebro a derrochar dopamina. En comparación, sus receptores de dopamina no están tan reducidos, pero está engrasando los toboganes pornográficos, buscando novedad, variedad, conmoción y ansiedad para sobrevivir los próximos cuatro días. Probablemente te imagines a este hombre como un patético imbécil, pero no es así. Solo se trata de un atleta retirado y exsargento de la marina que no quería volverse adicto a ninguna cosa. Sin embargo, al regresar de la guerra, se formó como técnico de TI (Tecnologías de Información) en un programa de rehabilitación para veteranos.

Cuando ingresó a la fuerza laboral civil, ya era un profesional de TI bien pagado que trabajaba en un banco, donde le dieron una computadora portátil para llevar su trabajo a casa. Esto ocurrió el mismo año en que famosas de la alta sociedad 'filtraron' sus videos porno en línea y se habló mucho al respecto. Fue entonces cuando se enganchó; firmo una sentencia para pasar el resto de su vida derrochando una cantidad excesiva de su tiempo y arruinarse física y mentalmente. Si fuera un bueno-para-nada, la sociedad lo habría sacado de su miseria hace mucho tiempo (Si, muy rudo), sin embargo, todavía permitimos que los jóvenes adolescentes, los seres con la mejor sanidad mental y física en el mundo, se enganchen. Puedes pensar que esta historia y las notas son exageradas, pero este caso — aunque extremo — está lejos de ser el único en su tipo. Hay decenas de miles de historias similares. ¿Qué tan seguro estas de que muchos de sus amigos y conocidos lo envidiaban por ser un hombre que consumía porno cada cuatro días?  Si crees que esto no te puede pasar a ti, **deja de engañarte**.

<span style = "font-size: x-large;">**YA ESTÁ PASANDO.**</span>

Al igual que otros adictos, los usuarios de pornografía son buenos mentirosos, incluso con ellos mismos. Tienen que ser así. La mayoría de los usuarios casuales se inducen en su placer muchas más veces y en muchas más ocasiones de las que admitirían. En muchas conversaciones con los llamados usuarios "dos-veces-por-semana", estos mismos admitirían que lo han hecho más de tres o cuatro veces esa semana. Metete al sub-reddit, _r/NoFap_, y trata de buscar aquellos posts sobre usuarios casuales publicados ahí. Descubrirás que, o están contando obsesivamente los días o están esperando fallar y dar una vuelta al tobogán. No necesitas envidiar a los usuarios casuales, tampoco necesitas ver pornografía, la vida es infinitamente más dulce sin ella. Analiza el siguiente post que encontré en _NoFap_:

> “Comenzó como un simple desafío de no ajusticiar mi ganso por un día. Y a pesar de las fallas, ya no pienso en masturbarme, ni siquiera se me pasa por la cabeza. Eso es posible, te lo prometo. Las riquezas que esperan a aquellos que pueden lograrlo, son increíbles”.

Los adolescentes son generalmente más difíciles de curar, no porque resulte más difícil detenerlos, sino porque no creen que estén enganchados o que estén en las etapas iniciales de la trampa. Generalmente sufren de la ilusión de que pueden detenerse cuando quieran antes de la segunda etapa.

Los padres de niños que detestan la pornografía en sí misma tampoco deberían sentirse tan seguros. Todos los niños detestan los lados oscuros de la pornografía antes de volverse adictos. En un momento, tú también lo hiciste. Tampoco te dejes engañar por campañas de miedo, la trampa es la misma de siempre. Los niños saben que la pornografía en Internet es un estímulo supranormal, pero también saben que una 'visita' o 'miradita' no los va a matar.  En algún momento pueden ser influenciados por un amigo, un compañero de clase o de trabajo.

Por favor, no te vuelvas complaciente en este asunto. El fracaso de las sociedades para evitar que los adolescentes se vuelvan adictos a la pornografía en Internet y otras drogas es quizás la faceta más perturbadora de esta adicción. Los cerebros jóvenes son significativamente más plásticos y moldeables, y es necesario educarlos y protegerlos. Si no estás seguro de por dónde empezar, hay muy buenos recursos como el libro _YourBrainOnPorn_, el cual te puede informar sobre el aspecto neurocientífico de la pornografía.  Incluso si sospechas que tu hijo adolescente ya está enganchado, ese libro proporciona una comprensión fundamental para ayudar a alguien a escapar de la trampa. Si de lo contrario no puedes leerlo, ¡recomiéndale este libro!
