# El usuario de YouTube / Twitch / Instagram {#el-usuario-de-youtube-twitch-instagram}

Este tipo de usuario debería ser considerado como un usuario casual, pero los efectos de su hábito son tan insidiosos que amerita un capítulo entero dedicado a desglosar su estado. Solo toma la anécdota de este usuario del foro en línea 'NoFap', quien perdió el dominio de sí mismo y casi ocasiona una ruptura amorosa con su pareja:

> "En uno de mis intentos fallidos por detenerme, solo pude abstenerme por unas 3 semanas; intento que a su vez fue incentivado por la preocupación de mi esposa en cuanto a mis erecciones nada fiables y mi falta de interés por tener sexo. Anterior a ello, solía decirle que no era ella, que solamente era la presión del trabajo. Pero una vez, ella me respondió: "Yo sé que has podido manejar la presión del trabajo anteriormente. ¿Pero cómo te sentirías si estuvieras en mi lugar, y tuvieras que observar a la persona que amas destruyéndose sistemáticamente?" Fue un argumento que encontré insoportable. Y por eso empecé ese intento de parar. Ella sabía que no le estaba siendo infiel, pero esto era peor que si lo fuera. El intento pues, duró 3 semanas, culminando en una acalorada discusión con un viejo amigo. No caí en cuenta hasta años después de que mi mente tortuosa deliberadamente ocasionó esa discusión; me sentía justificadamente agravado por las cosas que me reprochaba, pero he llegado a la conclusión de que no fue una coincidencia, ya que nunca había discutido con este amigo en particular, y ni siquiera he peleado con él desde entonces. Era sin duda, el pequeño monstruo en acción.  
A pesar de eso, tenía mi excusa. Necesitaba desesperadamente librarme de la tensión, y no sabía cómo. Mi esposa no estaba de buen humor así que sentí que 'estaba en mi derecho', y me convencí de que estaría bien si me "restringía" de entrar a sitios pornográficos y me quedaba en la "línea roja", mirando solamente videos de YouTube. Pero mi esposa terminó "viniendo a mí" al anochecer, y deseaba hacer el amor. Sin embargo, estaba cansado y sin 'combustible', así que me inventé un dolor de cabeza. No soportaba pensar en la decepción que esto le causó a ella. Así pues, y gradualmente, regresé a las viejas andadas, pero esta vez con YouTube volviéndose mi nuevo destino como harem. Recuerdo que me complacía en su momento, pensando que al menos así reduciría mi consumo. Sin embargo, y eventualmente, mi esposa me empezó a acusar de seguir ignorándola en la cama. No lo había notado hasta entonces, pero ella describió las veces que había ocasionado una discusión y salía enfurecido de la casa. E incluso, en algunas ocasiones, las veces en que me tomaba dos horas para comprar un artículo sin importancia o fingía esguinces. Hacía excusas tontas para evitar excitar a mi pareja, cosa que, al no tener un harem en línea de confianza o un sitio porno, se hacía más complicado."

Y lo peor de este usuario es que apoya en su mente la falacia de que está siendo privado. Cosa que, simultáneamente, causa grandes pérdidas de respeto por sí mismo; una persona honesta preferiría decepcionar a la persona que ama, en vez de seguir inventando excusas. Te ha pasado, quizá te siga pasando de alguna manera.

Los problemas que surgen con sitios como Twitch, Instagram, TikTok o Twitter (y la mayoría de las redes sociales) son impulsados en su mayoría por el concepto de suplementación. Impulsados por búsquedas de novedad y dopamina, los usuarios creen que están en un sitio seguro. Pero recuerda — la diversión está en la búsqueda, no en la ejecución, y al pequeño monstruo no le interesa de donde viene su dosis. Para este usuario, el contenido 'suave' recibido en varios de sus feeds en línea le da un alivio fugaz de los síntomas de abstinencia, dejándolo enganchado y expectante de la próxima sesión.

La modelo en la imagen/video es sin duda hermosa, y si la tuvieras a tu lado ahora mismo de seguro podría darte placer, pero la imagen no puede. Simplemente no es real. Tu cerebro es engañado como un toro corriendo hacia una capa roja, sin entender después por qué lo hizo. Uno podría pensar que puedes mirar esas imágenes sin que surja en ti la necesidad de masturbarte. Pero recuerda que el cerebro está enganchado en la búsqueda por novedad ilimitada, y al pequeño monstruo no le interesa de dónde viene su dosis. Es la misma trampa.

Habrás visto alguna vez la serie de televisión _'Columbo'_, donde la temática de cada episodio es similar. El antagonista, siempre un hombre de negocios acaudalado y respetado ha cometido aquello de lo que está convencido que es el asesinato perfecto y la confianza en su crimen, permaneciendo intacta, aumenta cuando descubre que el desarropado y aparentemente nada impresionable _'Detective Columbo'_ está a cargo del caso.

Columbo tiene esta frustrante práctica de cerrar la puerta después de terminar su interrogatorio, asegurando al sospechoso de que está a salvo. Pero antes de que la mirada de insatisfacción desaparezca de la cara del asesino, Columbo reaparece, diciendo _"solo un detalle, señor, el cual estoy seguro de que me puede explicar..."_ El sospechoso asesino empieza a tartamudear, sabiendo que, desde ese punto, Columbo lo va a descubrir. No importa qué tan atroz sea el crimen, es aquí donde un usuario como el de este apartado puede encontrar un poco de simpatía por el asesino.

Estos episodios de consumo son similares a la serie de Columbo: la tensión de no tener permitido cruzar la línea roja para tener la dosis de porno "justamente merecida", y luego preguntarse dónde está el placer después de terminar el acto. Aunado a el miedo de cruzar la línea, perder el control y regresar a la cama, solo para ser acosado por el miedo de que tu pareja quiera tener sexo. Hazte a la idea, los videos "seguros" de YouTube no te pueden satisfacer debido a tu desensibilizado cerebro, la falta de novedad en esos videos, y la certeza de que tarde o temprano visitarás tu sitio porno favorito de nuevo. Y todo esto, solo para culminar en sentimientos de vergüenza y humillación, que se consiguen cuando esta certeza se convierte en un hecho; cuando regresas a tu racha de ver videos porno, uno tras otro.

_**¡OH, LAS VENTAJAS DE SER UN ADICTO!**_
