# ¿Un hábito social? {#un-habito-social}

La salud mental y corpórea son las razones principales por las que _deberíamos_ querer detenernos — aunque de hecho siempre lo han sido. En realidad, no necesitamos de investigaciones científicas o conocimientos en neurociencia para concluir que la pornografía es adictiva y que puede destruir nuestras vidas potencialmente. Nuestros cuerpos son los objetos más sofisticados del planeta, y cualquier usuario sabe, desde la primera sesión, que el estímulo puede ser excesivo y volverse venenoso.

La única razón por la cual nos involucramos más y más con el porno es por la sobreposición del ciclo de PMO con nuestra programación evolutiva. La pornografía en internet tiene alta disponibilidad, es gratis, y está en transmisión las veinticuatro horas del día. El porno era considerado inofensivo, pero eso era cuando las imágenes eran estáticas, y los videos se conseguían con un viaje a la tienda local, en cintas de VHS.

Hoy, está generalmente considerado — incluso por los mismos usuarios — que la pornografía es un estímulo supranormal y que forma una adicción. En los viejos tiempos, aquel hombre que se consideraba como alguien fuerte no admitía que se masturbaba, considerando a aquellos que sí lo admitían como un _'puñetero'_, de manera despectiva. Y en cada cantina, antro o bar, la mayoría de los hombres estarían orgullosamente buscando llevarse a una mujer a su casa para tener sexo. Pero hoy en día, la posición ha sido completamente volteada para el adicto al porno, y el hombre moderno empieza a sentir que no necesita de una mujer para satisfacer su necesidad sexual. Uniéndose con otros en línea, discute experiencias sexuales, inventa estrategias y explora opciones. Y como consecuencia, el hombre que hoy se considera como alguien fuerte no quiere depender de las drogas. Y gracias a la revolución social, todos los usuarios están pensando seriamente en dejar el porno y la masturbación. Los usuarios de hoy en día consideran el porno una actividad dañina e inútil.

La tendencia más significativa, observada en foros en línea, es el creciente énfasis en los aspectos antisociales de la pornografía, revisitando los días en que un hombre presumía de tener sexo y orgasmos todos los días, los cuales están siendo lentamente reemplazados con la notoriedad de la esclavitud que impone el monstruo pornográfico.

La única razón por la cual la gente continúa viendo porno a pesar de saber lo esclavizante que es, es debido a que no han podido detenerse o están muy asustados para intentarlo. Hay un espectro muy amplio de interés en el tema, teniendo a algunos usuarios de un lado, absteniéndose completamente del porno, la masturbación y el orgasmo — con o sin parejas. Mientras que del otro lado, hay usuarios que se abstienen y prueban prácticas que separan las partes tántricas y propagativas del sexo como la retención del semen y _Karezza_, prácticas que son discutidas y adoptadas en manada. Muchos de los fracasos antes mencionados terminan siendo en realidad caídas hacia adelante, que benefician de cierta manera a la gente que pone en práctica los métodos ya mencionados. Una vez que inicies tu cruzada por evitar el PMO, encontrarás la mejor opción que se aplique a tu vida, por lo que se recomienda idear tu propio plan de orgasmos después de entender y practicar la separación sexual. Cualquiera que sea tu ruta, encontrarás valor en limitar el número de veces que sofocas tu cerebro con químicos a través del orgasmo, y sin ver de nuevo porno, también encontrarás valor en el sexo y el orgasmo, viéndolos como un placer o apoyo no para tu pequeño monstruo, sino para tu ser emocional.

Varias comunidades populares en línea fundadas por no-usuarios están dedicadas a dejar no solo la pornografía, sino también la masturbación. Estos sitios son últimamente benéficos para aquellos que están escapando, pero lamentablemente muchos artículos que comparten recomiendan probar el MFV. La consecuencia de esta obsesión con las rachas de abstinencia y otras medidas similares terminan siendo el autodesprecio y la falta de ánimo. Recuerda, mucho del lavado de cerebro sigue vivo y coleando. Y eventualmente, alguien _'se quebrará'_ y un efecto dominó tomará lugar, mientras que muchos usuarios descubren que no son los únicos que desisten. Sin embargo, sus esfuerzos no son en vano, están cayendo hacia adelante, aunque con bastante autotortura, ya que cerraban sus navegadores, pero no su deseo y necesidad de seguir consumiendo. Por fortuna para ti, EasyPeasy funciona de la manera contraria, apagando primero el deseo y la necesidad antes de cerrar el navegador. Cada día más y más usuarios dejan el barco hundiéndose y aquellos que se quedan temen ser los últimos.

**¡NO PERMITAS QUE ESTE SEAS TÚ!**
