# Escoger el momento adecuado {#escoger-el-momento-adecuado}

Descartando el hecho de que el porno no te está haciendo ningún bien y que el mejor momento para dejarlo es ahora, es de recalcar que debes hacerlo en el momento más adecuado. La sociedad de ahora ni siquiera se toma en serio la pornografía, tomándola como un hábito ligeramente desagradable el cual no destruye ni tu integridad física ni mental. Esto no es cierto, es una drogadicción, una enfermedad y un destructor de relaciones sociales. Lo peor que ha pasado en la vida de un usuario ha sido el haberse enganchado con esta horrible droga. Y sabemos que entre más enganchados se queden, peores cosas le pasan. Por lo tanto, dejarlo en el momento más adecuado es importante, así te das la oportunidad de obtener una _cura apropiada_.

Lo primero que tienes que hacer es identificar esas ocasiones en las que el porno parece ser tan importante para ti. Si eres una persona de negocios que lo utiliza para la ilusoria descarga de estrés — entonces debes escoger un período relativamente flojo, tranquilo, o algún período vacacional para dejarlo. Si lo usas cuando estás aburrido o en períodos de relajación, lo opuesto aplica para tu caso. No importa que pase, toma este intento como algo serio y conclusivo, y haz de esta tarea la cosa más importante en tu vida.

Ahora, trata de buscar un período de 3 semanas que se empalme con este tipo de ocasiones opuestas, y anticipa cualquier evento que conlleve tu derrota. Eventos como lo son los viajes de negocios, que tu pareja se encuentre fuera de tu estado, etc. No te verás en la necesidad de desistir cuando esos eventos pasen, dado que ya has anticipado dicho evento y no sientas que serás privado de tu dosis. Tampoco trates de cortar tu consumo mientras tanto, ya que esto creará la ilusión de que ser negado tu consumo es algo disfrutable. De hecho, es incluso dañino, ya que esto ayudará a reforzar la idea de que tienes que ver lo más que puedas y tener la mayor cantidad de sesiones posibles antes de tener tu última sesión. Y mientras estés teniendo esa última sesión, trata de concientizar lo más que puedas los sentimientos que se experimentan con la descarga seminal. Concientiza tus incumplidas expectativas, los dolores físicos, los efectos de la abstinencia, el mal humor y la melancolía que la descarga seminal conlleva. Y posteriormente, piensa lo maravilloso que será cuando puedas dejar de usar pornografía, y librarte de todos estos sentimientos.

**PERO HAGAS LO QUE HAGAS, NO CAIGAS EN LA TRAMPA DE SOLO DECIR "LO HARÉ LUEGO" Y OLVIDARTE DE HACERLO. TRATA DE FORMULAR TU HORARIO <span style="text-decoration:underline">AHORA</span> Y PONERTE A TRABAJAR.**

Recuerda, _no estás renunciando a nada_. Por el contrario, estás a punto de recibir maravillosos beneficios.

Por años, la profesión médica ha visto a la pornografía como algo inofensivo, sin siquiera saber la diferencia entre el _dócil_ y estático porno de antaño y la más novedosa experiencia de realidad virtual pornográfica del día de hoy. El problema es que, a pesar de que cada usuario consume pornografía meramente para aliviar esa necesidad de dopamina causada por el porno en sí, no es la adicción a este químico lo que lo engancha, sino el lavado de cerebro que resulta de esta adicción. Una persona inteligente podría caer ante la astucia de un estafador, pero solo un tonto seguiría cayendo por la misma estafa aun conociendo cómo funciona. Por fortuna, muchos usuarios no son tontos, solo creen que lo son. Cada uno de los usuarios tiene su propio lavado de cerebro. Por eso parece que hay un rango extenso de los tipos de usuarios, reforzando aún más el misterio de la adicción misma...

A pesar de que el objetivo primordial del libro original era dejar la nicotina (una de las más adictivas y rápidas drogas que el hombre ha conocido) fue agradablemente sorprendente el hecho de saber que el mismo método aplica para este caso. El reto que Allen Carr y yo cargamos es el de _cómo_ transmitir este conocimiento a otros. Y el hecho de que YO sepa que cada usuario puede no solo encontrarlo fácil, sino de que también puede encontrar divertido dejar esta adicción, no solo carece de sentido, sino que también resulta frustrante si es que el usuario no puede caer en cuenta de ello. En el libro original, Carr explica:

> "Mucha gente me ha dicho: _'Tú dijiste que "siga fumando hasta que acabe el libro". Esto tiende a hacer que el fumador tarde una eternidad en acabar el libro, o que simplemente no lo acabe. Punto final. Por lo tanto, debes cambiar esa instrucción.'_ Esto suena lógico, pero sé que si la instrucción fuese: _'para de inmediato'_, algunos fumadores ni siquiera empezarían a leer el libro. Hubo uno de estos que me consultó en los primeros días. Él decía: _'Me molesta mucho tener que buscar su ayuda. Sé que tengo una fuerte voluntad. Tengo el control en cualquier otra área de mi vida. ¿Por qué otros fumadores dejan el cigarro usando mera voluntad, pero yo tengo que venir con usted?'_ Él continuó, _'creo que podría hacerlo por mi cuenta, si tan solo pudiera seguir fumando mientras lo dejo'_."

La sociedad hoy en día dice que dejar de fumar es increíblemente difícil. ¿Y qué es lo que un fumador necesita en tiempos difíciles? Su pequeño amigo, su apoyo. Dejar de fumar parece un golpe doble, ya que no solo tienes una difícil tarea que cumplir, sino que aparte, ese apoyo al cual recurrías para este tipo de ocasiones no está disponible. Quizás el aspecto más bello de este método es que no tienes que _'renunciar'_ mientras avanzas en el proceso. Primero te deshaces de todos los miedos y las dudas, así para cuando acabes tu última sesión saborearás por fin la libertad.

Por lo tanto, este _'hackbook'_ mantendrá esta instrucción intacta. No importa cuántas veces se mencione lo fácil y disfrutable que es dejar la pornografía, seguirá habiendo una vasta mayoría que no se pueda permitir verlo así debido al extenso lavado de cerebro que sufren referente a dejarlo.

Este capítulo es el único que realmente me hace cuestionar seriamente el método que propone Allen Carr. Sobre todo, esa parte en la que nos dice que escojamos períodos de tiempo que sean el total opuesto a las ocasiones que escogemos para consumir porno, para dejarlo. Esta no es la forma más fácil, cuando puedes escoger los momentos _más difíciles_ para ti. Sea el estrés, las obligaciones sociales, concentración, aburrimiento, etc. Una vez hayas probado que puedes lidiar con esos tiempos difíciles sin usar pornografía, cualquier otra ocasión será mil veces más disfrutable. ¿Pero de ser así, hubieras tomado el consejo?

Otra analogía: un día mi hermana y yo decidimos ir a nadar. Llegamos a la alberca al mismo tiempo, pero no llegamos a nadar a la par. La razón es que mi hermana prefiere ir metiéndose de poco a poco, introduciendo los dedos del pie primero, y entrando enteramente hasta una hora después. Eso es una tortura muy lenta, y yo sé que en algún punto, sin importar lo fría que esté el agua, tendrá que agarrar valentía y entrar a la alberca. Yo aprendí a hacerlo de la manera más fácil — saltando directamente. Ahora imagina si estuviera en esa posición donde tengo que convencerla de que, si no entra de un salto a la alberca, nunca podrá nadar. Si ese fuera el caso, sería obvio que entonces no nadaría para nada. ¿Puedes ver el problema ahora?

Gracias a la retroalimentación, pude notar que muchos usuarios usaron el consejo original, el de dejar el porno en el momento correcto, para retrasar lo que consideran es el _"malévolo día"_. Entonces pensé en usar una técnica similar a la del capítulo _"ventajas de ser un usuario..."_, haciendo algo así como — _"Escoger el período correcto es importante, así que en el próximo capítulo serás iluminado con el mejor momento para poder dejar de usar porno"_ y en la próxima página poner un masivo texto que diga _**"AHORA"**_. Ese es, de hecho, el mejor consejo que puedo darte, ¿pero lo tomarías? Quizás el aspecto más sutil de esta trampa es que, cuando tienes genuino estrés en tu vida no es el período correcto para dejar de usar porno, pero cuando estos períodos de estrés acaban, no hay necesidad para acabar con esta tortura. Pregúntate lo siguiente:

* ¿Cuando empezaste a usar porno por primera vez, realmente decidiste que continuarías dependiendo de él por el resto de tu vida sin siquiera poder dejar de usarlo? **¡Claro que no lo hiciste!**
* ¿Y seguirás el resto de tu vida sin poder dejar de usarlo? **¡Claro que no lo harás!**

¿Así que, cuándo vas a parar? ¿Mañana? ¿El próximo año? ¿O quizá, el año que sigue del siguiente? ¿No ha sido esto lo que te has estado preguntando desde que te diste cuenta de que estabas enganchado? ¿Realmente esperas que una mañana despiertes y simplemente seas libre de la adicción? Deja de engañarte, con cualquier adicción solo te vuelves progresivamente más adicto, no menos adicto. ¿En serio vas a esperar a que levantarte de la cama se sienta más complicado que masturbarte? Eso sería un verdadero sinsentido.

La verdadera trampa radica en la creencia de que ahora no es un buen momento — siempre será más fácil mañana. Creemos que nuestras vidas son verdaderamente estresantes, cuando en realidad no lo son. Las más genuinas formas de estrés han sido removidas de nuestras vidas. No sales de casa con el miedo constante de ser atacado por un animal salvaje. Algunos ni siquiera se preocupan por la fuente de su próxima comida, o de si algún techo estará sobre su cabeza esta noche. Piensa en la vida de un animal salvaje. Cada que un conejo sale de su madriguera, se está enfrentando a Vietnam por su supervivencia. Pero el conejo puede con ello, gracias a su sistema de adrenalina y hormonas, así como nosotros. Y la verdad es que, los períodos más estresantes de nuestras vidas son nuestra niñez temprana y la adolescencia. Tres billones de años de selección natural nos han equipado para poder lidiar con el estrés, solo piensa en la gente cuya niñez fue estresante y que pueden vivir vidas normales sin problema.

Es un cliché decir _"sin tu salud, no eres nada"_ pero es que es absolutamente cierto. Cuando te sientes física y psicológicamente fuerte puedes manejar los bajos y disfrutar los altos. Muchos confunden la responsabilidad con el estrés, cuando la realidad es que la responsabilidad se convierte en estrés cuando no sentimos la fortaleza para lidiar con dicha. Lo que más nos destruye no es el estrés, el trabajo o la vejez, sino los ilusorios apoyos a los que volteamos para poder lidiar con nuestras vidas.

Míralo de esta forma. Ya has decidido que no te quedarás dentro de la trampa por el resto de tu vida. Y en algún punto — te sea complicado o no — tendrás que pasar por este proceso de liberación. El porno no es un hábito o un placer, es una adicción y una enfermedad. Hemos establecido ya que más que ser fácil mañana, tu adicción se volverá progresivamente peor. El momento para deshacerte de tu adicción es _**ahora**_ — o lo más cercano a ahora que puedas. Solo piensa en lo rápido que las semanas pasan en nuestras vidas, es todo lo que te tomará. Piensa en lo lindo que será disfrutar el resto de tu vida sin sombras alrededor de tu cabeza que se van acumulando. Y dado que sigas las instrucciones al pie de la letra, no tendrás que esperar ni cinco días o tres semanas. No solo verás que es fácil, ¡sino que **también es divertido dejar tu adicción!**
