# ¿Me perderé de la diversión? {#me-perdere-de-la-diversion}

**¡No!** Una vez que el pequeño monstruo esté muerto, una vez que tu cuerpo deje de saciar la dopamina, y una vez que los toboganes de pornografía en tu cerebro empiecen a desvanecerse debido a la falta de un correcto _engrasado_, todo lavado de cerebro que quede se desvanecerá también. No solo estarás mejor equipado física y mentalmente para lidiar con el estrés y las torceduras que te dé la vida, sino que también empezarás a disfrutar los buenos tiempos en su máximo esplendor.

Aunque solo hay un factor de riesgo que te puede traer de regreso a la trampa: la influencia que te ejercen aquellos que aún usan _el sexo_ como su placer o apoyo. _"El jardín del vecino siempre es más verde"_, es una frase que describe de forma ordinaria cualquier aspecto de nuestras vidas, y es una frase fácil de entender. ¿Pero por qué, cuando hablamos de porno — con las desventajas sobrepasando las ilusorias 'ventajas' — el ex-usuario tiende a envidiar a aquellos que constantemente usan el sexo y la pornografía como su apoyo?

Con todo el lavado de cerebro que se crea desde la infancia, es entendible que hayamos caído en la trampa. ¿Pero por qué entonces — después de darnos cuenta del insidioso juego que es el porno, y además haber podido _'dejar el hábito'_ — caminamos directamente hasta la trampa de nuevo? Se trata de la influencia del lavado de cerebro social, fusionando la idea de que el sexo y el porno son algo normal. **¡Es el ex-usuario sufriendo un dolor de abstinencia!** Ese vacío sentimiento que le genera al ex-usuario el estar soltero (cosa que no está mal de todas formas) le causa a la par sentimientos de ansiedad, cosa que los regresa directo al tobogán. Esto es de hecho, una curiosa anomalía, particularmente si se considera de esta forma — cada no-usuario en el mundo es feliz de serlo, pero cada usuario en el mundo incluso con su deformada, adicta y programadamente sufriendo el engaño de sentir disfrute o relajación, desearía no haberse enganchado en primer lugar. ¿Así que, por qué algunos ex-usuarios envidian esta situación?

* **Solo una miradita.** Recuerda, tal cosa no existe. Deja de verlo de forma aislada y adopta la visión de un usuario. Puedes envidiarlos, pero ellos ni siquiera aprueban su forma de ser. Los usuarios te envidian a ti. Si tan solo hubiera forma de ver clínicamente a un usuario. Esta visión de su caso sería un poderoso aditivo para poder _dejar el hábito_ por completo. Trata de visualizar lo rápido que un usuario abre demasiadas ventanas en su navegador. Adelantando el video, buscando las mejores partes, rápidamente aburriéndose de los videos y hojeando rápidamente a través de la amplia gama de géneros que producen novedad, shock, ansiedad, etc. Te das cuenta de que el acto incluso parece automático. Recuerda — no lo están disfrutando, sino que no pueden disfrutar sus vidas si no lo hacen. La mañana siguiente, despertando con una voluntad débil, sin energía y con los ojos nublados, tendrán que seguir torturándose para lidiar con el estrés y la tensión de sus vidas. Se están enfrentando a una vida de mugre, de salud mental débil y baja confianza en sí mismos — una vida entera de autodestrucción, utilizando las sombras que yacen detrás de sus cabezas para este fin. ¿Y para conseguir qué? ¿La ilusión de que estás obteniendo lo que mereces y un poco de maldito placer?
* La segunda razón por la que los ex-usuarios tienen estos dolores de abstinencia yace en el hecho de que el usuario tiene la posibilidad de hacer algo — masturbarse/ver porno — cosa que el no-usuario no puede, lo que lo lleva a **sentirse privado**. Hazlo claro en tu mente, no es el no-usuario el que está siendo privado, pero el pobre adicto el que se priva de:
    * Salud
    * Energía
    * Confianza en sí mismo
    * Paz mental
    * Coraje
    * Tranquilidad
    * Libertad
    * Respeto por sí mismo

Quítate el hábito de envidiar a los usuarios de encima, y empieza a verlos como las miserables y patéticas criaturas que son. Lo sé, yo también fui de lo peor. Pero tú estás leyendo este libro, y no aquellos que no pueden percatarse de su estado y deciden seguir engañándose.

No hay ningún aspecto por el cual puedas envidiar a un adicto a la heroína, y como con toda drogadicción la tuya se hará más fuerte con el tiempo. Cada año, se pondrá exponencialmente peor — si no disfrutas ser un usuario hoy, lo disfrutarás menos mañana. No envidies a los demás usuarios, ten pena por ellos. Créeme, **¡necesitan de tu pena!**
