# ¿Puedo compartimentar mi sexualidad?

Este mito es especialmente compartido por aquellos usuarios que tratan de detener su consumo usando su propia voluntad, los cuales también realizan _‘gimnasia mental’_ y comienzan para sí mismos una rutina de _‘Jekyll y Hyde’: ‘El porno es para mi alter-ego y el romance real para mí persona social.’_ A este punto, creo que no tengo que mencionar los hechos — es obvio que los toboganes pornográficos, el DeltaFosB y los cambios neurológicos VAN A INVADIR tus capacidades sociales, haciéndolas más indeseables. El Sr. Hyde va a hacer caso omiso a las instrucciones del Sr. Jekyll. 

Al consumir pornografía, estas entrenando a tu mente para adoptar el rol de _‘Voyeur’_, o para adoptar el hábito de dar click en algo que sea más excitante tan pronto tu dosis de dopamina baje. O, para el hábito de buscar la escena correcta para el mayor efecto posible. Adicionalmente, quizá te vayas a acostumbrar a una posición encorvada a la hora de masturbarte o estar en el celular a la hora de dormir, eventualmente adoptando un mayor deseo por esos estímulos digitales que a estímulos reales. El sexo se opone a casi todos los aspectos del harem en línea, así que no hay manera de compararlos. Las memorias que creas con el porno a una temprana edad son muy poderosas y longevas, así que romper esos toboganes neurológicos que crea y reconectar o crear nuevos te tomará más tiempo. Sin embargo, eso no quiere decir que sea más difícil. 

Cada que bajas por el ‘tobogán pornográfico’ lo estás engrasando, manteniendo esas vías neuronales frescas y listas para la acción. Solo velo de esta forma: cuando te estacionas cerca de una cadena de comida rápida, el olor de la freidora vuela hasta tus fosas nasales, vendiendo casi instantáneamente la idea de comprar algo. De la misma forma, los toboganes de agua pornográficos en tu cerebro siempre están listos para que los uses, y están abiertos 24/7. Cada señal o disparador que veas enciende tu sistema de recompensa con la promesa de sexo — aunque no sea precisamente sexo. Además, las células nerviosas solidifican estas asociaciones con la excitación sexual, brotando nuevas ramas nerviosas para reforzar estas conexiones. Entre más uses porno, más fuertes se vuelven estas conexiones nerviosas. El resultado final es que quizá, y en última instancia, _‘necesites’_ cumplir con el rol de _voyeur_, adoptando la necesidad de dar click a cualquier material que te cause novedad, necesitando de porno para dormir, o necesitando buscar el _‘final perfecto’_ para poder eyacular. 

Así como con cualquier sustancia o droga conductual, el cuerpo genera inmunidad y la droga cesa de aliviar esos dolores de abstinencia en su totalidad. Tan pronto como el usuario de pornografía cierra la sesión, quiere otra y rápidamente, el hambre permanente se mantiene insatisfecho, generando a su vez una inclinación natural a buscar una conducta que aumente la dosis de dopamina. Sin embargo, muchos usuarios son prevenidos de adoptar estas conductas por las siguientes dos razones: 

**Dinero:** No tienen el dinero para pagar una suscripción a sitios pornográficos.

**Salud:** El cuerpo tiene límites, hablemos de las oleadas de dopamina o de los orgasmos que una persona puede tener. Además, los orgasmos tienden a disparar químicos que cortan la cantidad de dopamina que es usada, de forma gradual. Tiene que hacerlo, así es como funciona el cuerpo humano. 

Una vez que el pequeño monstruo deja tu cuerpo, el horrible sentimiento de inseguridad se acaba. Tu confianza regresa, junto con un maravilloso sentimiento de respeto por ti mismo, dándote la seguridad de que puedes tomar control de tu vida y el poder de utilizar esa autoconfianza como trampolín para poder lidiar con otros problemas. Esta es una de las numerosas y grandiosas ventajas de librarse de muchas adicciones. 
 
El mito de la compartimentalización es uno de los muchos trucos que el pequeño monstruo utiliza para jugar con tu cabeza. Estos trucos hacen más difícil el poder dejar la adicción — debido a la imposible satisfacción de tu permanente hambre — causando que muchos lidien con su adicción utilizando el cigarro, el embriagamiento, o incluso drogas más fuertes para satisfacer este vacío. 

Los humanos somos seres que le dan valor a las cosas; nos valoramos a nosotros mismos y a los demás. Ver pornografía con tu pareja es insatisfactorio, ya que ambos valoran de forma diferente el sexo que tienen comparándolo con la narrativa del porno. ¿Te gustaría tener a Brad Pitt en tu cuarto, aunque sea en pintura? No hay persona que pueda igualar cada experiencia sexual real que tienen con la de una película porno, donde cada ‘experiencia’ ya está escrita, es actuada y dirigida por profesionales, y que está disponible las 24 horas del día.
