# ¡Evita los falsos incentivos!

Algunos de los usuarios que utilizan su fuerza de voluntad para dejar el porno también intentan incrementar su motivación a través de la construcción de falsos incentivos. Hay muchos ejemplos de esto, como la gente que se regala cosas a sí mismos después de no haber visto porno por un mes. Esto parece ser una forma lógica y un enfoque sensato para lidiar con tu adicción, pero, de hecho, es falsa; cualquier usuario que se respete a sí mismo y su estado prefiere seguir viendo pornografía que regalarse algo a sí mismos. Esto genera dudas en la mente del usuario, porque no solo tendrán que abstenerse por _30 días_, sino porque tampoco saben si disfrutaran de este período sin poder ver porno. ¡Su único amigo y apoyo ha sido arrebatado! Todo lo que esto ocasiona es aumentar el sentido de sacrificio que el usuario siente, convirtiendo el porno en algo preciado en su mente. 

Hay otros ejemplos:

* _“Voy a parar por este periodo, así me obligo a conseguir una vida social o sexo real con una pareja.”_
* _“Me detendré para que una especie de energía mágica despierte en mí, y me ayude a quitar del camino a todos los pretendientes que estorban entre la pareja que quiero y yo.”_
* _“Dejare el PMO, así no desperdicio mi energía y la guardo para poder crecer como persona.”_

Estos incentivos son reales, efectivos, y quizá te ayuden a conseguir lo que quieres - pero reflexiona por unos segundos. Si en verdad consigues lo que quieres, y una vez que la novedad y el entusiasmo se esfumen de tu cabeza, te sentirás privado de nuevo; y de no conseguirlo, te sentirás miserable. De cualquier forma, tarde o temprano volverás a caer en la trampa.

Relacionar la idea de dejar el porno con un falso incentivo solo incrementa las dudas, porque si no consigues tu incentivo (y aún si lo consigues) empezaras a cuestionarte cosas como: _“¿Renunciar a la pornografía realmente mejorara mi vida?”_ _“¿Si renuncio al porno y aun así no consigo lo que quiero, habré usado el método correctamente?”_ Pensamientos así incrementan el sentimiento de sacrificio y, por ende, crean dolores de abstinencia. 

Otro ejemplo típico son los pactos grupales hechos en foros de internet, los cuales tienen la ventaja de eliminar la tentación por un corto periodo de tiempo. Sin embargo, la gente falla por varias razones:

* **El incentivo es falso,** ¿por qué querrías parar solo porque alguien más lo está haciendo también? Todo lo que esto consigue es generar presión adicional e incrementar ese sentimiento de sacrificio. Está bien si todos los usuarios tienen la genuina intención de parar en algún punto - pero no puedes forzarlos a hacerlo, aunque secretamente desean hacerlo. Hasta que estén listos para parar, un pacto solo creará presión adicional, lo cual también incrementa el deseo de ‘echar una miradita’. Esto los hace ver porno en secreto, haciendo que crezca el sentimiento de dependencia a su vez. 
* **Depender de otros** mientras se está usando el método de la voluntad propia **produce una sensación de estar cumpliendo una penitencia**, donde todos esperan que el impulso por ceder desaparezca. Si uno cede, hay un sentimiento de derrota para todos. Y cuando todos usan el método de la voluntad, al menos un integrante está destinado a fallar, dando a los demás participantes la excusa que estaban esperando. “No es su culpa, ellos habrían resistido de no haber sido por ‘Fred’, quien cedió y los decepcionó a todos.” Aunque para ese entonces, es algo seguro que todos los integrantes ya habrán hecho trampa al menos una vez...
* **Compartir el crédito es lo opuesto a la independencia.** Hay una maravillosa sensación de logro en dejar de consumir porno y es más fuerte cuando se hace por tu cuenta, con los halagos de tus amigos y tus compas de internet siendo un tremendo ‘estímulo’ los primeros días. Sin embargo, cuando todos lo están haciendo al mismo tiempo, el crédito tiene que ser compartido y este ‘estímulo’ es consecuentemente reducido. 
* Otro clásico ejemplo es la **promesa de que te convertirás en un ‘gurú del sexo’**. Dejar el PMO te hará más feliz porque ya no estarás en este juego de ‘jalar la cuerda’, tu cerebro empezará a reconectarse y tendrás de vuelta el control sobre tus impulsos. Sin embargo, debes tener en mente que no te vas a convertir en un ‘dios del sexo’ o que consiguientemente ganes la lotería. A nadie <span style="text-decoration:underline">_más que a ti_</span> le importa en lo absoluto si dejas de consumir porno. No eres una persona débil si usas porno 3 veces al día, o una persona fuerte si eres un adicto y no lo haces. 

Deja de engañarte. Si la oferta de 10 meses de trabajo por 12 meses de salario anuales, el riesgo de inhabilitar la capacidad de tu cerebro de lidiar con el estrés del día a día, la idea de tener que jugar a la ruleta rusa a la hora de tener una erección, o la idea de sufrir una vida de tortura física y mental no te detiene, los incentivos que se presentaron arriba no harán la menor diferencia posible, y solo harán que el sacrificio se vea mucho más grande. 

En vez de eso, concéntrate y trata de ver el otro lado:

_“¿Qué es lo que estoy consiguiendo al masturbarme? ¿Por qué necesito ver porno?”_

O sigue mirando hacia el lado contrario, al lado donde estás jugando al jalar de la cuerda, y pregúntate qué es lo que el porno está haciendo por ti. _ABSOLUTAMENTE NADA._ ¿Por qué lo necesito? _NO LO NECESITAS. SOLO TE ESTAS CASTIGANDO A TI MISMO._ Es una apuesta de Pascal: no tienes nada que perder, tienes ganancias muy gordas (una completa y confiable excitación sexual, salud mental y bienestar) y ninguna chance de perder a lo grande. 

_“¿Ok, pero debería declarar a mis seres queridos que dejaré la pornografía?”_ Bueno, esto te hará un ex-usuario o un ex-adicto orgulloso de sí mismo, mas no un no-usuario exaltado o feliz. Quizá hasta asustes a tu pareja un poco, dado que vea esto como un esquema de manipulación para tener más sexo. O hasta se podría atemorizar de que te vuelvas una especie de máquina sexual; es difícil de explicar si la persona en cuestión no tiene una mente abierta. 

Cualquier intento de hacer que otros te ayuden a dejar la pornografía le da más poder al pequeño monstruo (¿Recuerdas el lavado de cerebro social?). Aunque, por otro lado, empujándolo de tu mente e ignorándolo por completo solo tendrá ese efecto de no pensarlo. (Si te digo que no pienses en un caballo blanco, ¿podrás hacerlo?). Mejor se consciente, tan pronto notes esos pensamientos, esos indicios (como tener casa sola o ver un comercial muy sexy) o esas ideas ausentes en tu cabeza, piensa entonces _“Genial, ya no soy un esclavo de la pornografía. ¡Soy libre y estoy feliz de saber la diferencia entre el porno y el sexo real!”_ Hacer esto les quita oxígeno a estos pensamientos y detiene esas ardientes ganas de ceder al impulso. En este aspecto, practicar meditación ‘Mindfulness’ también puede ser de mucha ayuda en la despersonalización de estos pensamientos...
