# La manera fácil de parar

Este capítulo contiene instrucciones referentes a la manera fácil de dejar la pornografía. Dado que sigas las instrucciones, ¡verás que dejar la pornografía varia de un rango entre fácil a disfrutable! Y dado que sigas las instrucciones de aquí abajo, será ridículamente fácil hacerlo. Todo lo que tienes que hacer es: 

* Tomar la decisión de que no volverás a ver pornografía nunca más. 
* No deprimirte por esto. _Alégrate, mejor._

Quizá te preguntes, _“¿Para qué sirve el resto del libro entonces? ¿Por qué no empezamos por esto en primer lugar?”_ Bueno, la respuesta es que eventualmente hubieras empezado a deprimirte por haber decidido dejar el porno, y consecuentemente hubieras replanteado la decisión de no hacerlo. Quizá ya lo hayas hecho muchas veces antes.

Como ya dije, el porno es una sutil y siniestra trampa. El principal problema de parar no es la adicción a la dopamina — la cual es ciertamente un problema — sino el lavado de cerebro. Por lo tanto, es necesario destruir todos los mitos e ilusiones primero. Entiende a tu enemigo, conoce sus tácticas y lo derrotarás fácilmente. Habiendo gastado varios trozos de mi vida sufriendo de una oscura depresión mientras intentaba dejarlo, y hasta que por fin pude escapar, mi consumo se redujo a cero sin tener ningún problema. Fue disfrutable incluso en el periodo de abstinencia, y nunca experimenté ningún dolor de abstinencia en absoluto. Por el contrario, fue una de las cosas más maravillosas que me han pasado. 

Mi último intento fue diferente. Como cualquier usuario de hoy en día, el problema acaparaba demasiado espacio en mi cabeza. Hasta ese último intento, tenía la rutina de consolarme a mí mismo con la idea de que sería más fácil la próxima vez. Pero hubo un punto en que llegué a preguntarme si esta rutina me acecharía toda la vida, cosa que me llenó de horror y me llevó a cuestionar severamente el tema.

En vez de encender el buscador subconscientemente, analice mis sentimientos y confirme lo que ya sabía. No estaba disfrutando del porno, y para entonces lo encontraba asqueroso y repudiable. Entonces empecé a ver a los no-usuarios que vivían en otras partes del mundo, o gente mayor que nunca conoció los sitios para adultos. Hasta entonces, siempre consideré a los no-usuarios como gente deseosa, asocial y quisquillosa. Sin embargo, y examinando la situación de los no-usuarios cuando uno se cruzaba en mi camino, se veían mucho más - a lo mucho que pude distinguir - fuertes y relajados. Se veían más preparados para lidiar con el estrés y la tensión de sus vidas y parecían disfrutar más de sus funciones sociales que los usuarios de pornografía. Ellos ciertamente parecían tener más ánimo y brillo que los usuarios. 

También empecé a hablar con ex-usuarios. Hasta ese punto, siempre consideré que habían sido forzados a dejar el porno por cuestiones de salud o religión, y que estaban secretamente deseando volver a sus ‘harems en línea’. Pero algunos me decían, _“De repente te dan esas punzadas extrañas, pero son tan pocas y distantes entre sí que ni siquiera puedes preocuparte.”_ Otros, por otra parte: _“¿Extrañarlo? ¡Debes estar bromeando! ¡La vida nunca se había sentido tan bien!_ Incluso las derrotas que tenían en sus vidas eran ventajosas para ellos, no se condenaban a sí mismos y en vez de eso aceptaban esas derrotas. Como un coach que acepta el error de un genuino jugador estrella. Hablar con ex-usuarios sirvió para destruir otro mito que siempre tuve en mi mente: el mito de que había una inherente debilidad en mí. No fue hasta entonces que caí en cuenta de que todos pasan por esta pesadilla privada. 

Básicamente, me decía a mí mismo _“Una tanda de miles personas está dejando el porno ahora y llevando vidas perfectas y felices. Nunca tuve que hacerlo antes de engancharme, y ahora que recuerdo perfectamente lo mucho que trabajé para engancharme así, ¿por qué tengo que hacerlo ahora? ¿Por qué seguir enganchado?”_ En cualquier circunstancia, no disfrutaba de la pornografía. Odiaba ese sucio ritual y no quería pasar el resto de mi vida siendo esclavo de esta asquerosa adicción. Entonces, me dije a mí mismo: 

_“Te guste o no, has completado tu última sesión”._

Sabía que, desde ese punto, no tendría otra sesión de nuevo. No esperaba que fuera fácil, sino todo lo contrario. En verdad creía que había firmado una sentencia para pasar meses de oscura depresión; para pasar el resto de mi vida con dolores de abstinencia ocasionales. Pero en vez de eso, ha sido absoluta felicidad desde el inicio.

Me tomó demasiado tiempo descubrir por qué me había resultado tan fácil y por qué no había sufrido de estos terroríficos dolores de abstinencia. La razón es que no existen, es la duda y la falta de certeza la que crea estos dolores. La hermosa verdad es que _**es fácil dejar la pornografía.**_ Es solo la falta de decisión y el deprimirte de este hecho lo que lo hace complicado. Incluso cuando son adictos, los usuarios pueden pasar periodos muy largos de tiempo sin consumir porno. Es solo cuando quieres, pero no puedes tenerlo, cuando sufres. 

Por lo tanto, la clave para hacerlo fácil es tomar el hecho de que lo vas a dejar como algo consciente, certero y final. No esperar, sino saber que lo has dejado, habiendo tomado la decisión. Nunca dudes o cuestiones tu decisión, de hecho, haz lo contrario - ¡siempre alegrándote! Si puedes estar seguro desde el inicio, será fácil. ¿Pero cómo puedes estar seguro desde el inicio? Es por eso por lo que el resto del libro es necesario. Hay ciertos puntos que son esenciales de entender antes de empezar:

* **Darte cuenta de que puedes hacerlo.** No hay nada diferente entre tú y la única persona que te obliga a ver pornografía; eres tú mismo. No aquella estrella porno, que ni en sus más salvajes sueños ha de haber pensado que sería usado para reducir la virilidad de las personas. 
* **No hay absolutamente nada a lo que renunciar.** Por el contrario, hay enormes ganancias aquí. No solo serás más saludable y fuerte, sino que también serás más feliz en tus mejores momentos y que podrás lidiar mejor con los malos.
* **No hay tal cosa como ‘una miradita’ o visita.** La pornografía es una adicción y una acción en cadena, el estar urgido por esa pequeña visita solo hará que te estés castigando de forma innecesaria. 
* **No veas al porno como un hábito ‘inherente a la hombría’ que quizá te perjudique, sino como una drogadicción.** Hazle frente al hecho de que te guste o no, **has contraído una enfermedad.** No se irá solo porque escondas tu cabeza en la arena. Recuerda que, así como todas las enfermedades crónicas, no solo durará de por vida, sino que se pondrá peor. El mejor momento para curarlo **es ahora.**
* **Separa la enfermedad — la adicción neurológica — de la mentalidad de ser un usuario o no serlo.** Todos los usuarios, si tuvieran la oportunidad de volver en el tiempo al momento anterior de haberse enganchado, tomarían esa oportunidad. ¡Tú tienes esa oportunidad ahora! Ni siquiera lo veas como si te estuvieras ‘rindiendo’. 

En el momento en que hayas tomado la decisión final de que has tenido tu última visita, ya serás un no-usuario. Un usuario es uno de esos pobres desgraciados que van por la vida destruyéndose a sí mismos con porno. Un no-usuario es alguien que no es así. Una vez que hayas tomado esa decisión final, ya habrás conseguido tu objetivo. Alégrate del hecho, no te sientes deprimido esperando a que la adicción química se vaya. Sal y ve a disfrutar de la vida inmediatamente. La vida es maravillosa incluso cuando eres adicto, poniéndose mucho más bella cada día cuando no lo eres. 

La clave para hacerlo más fácil es estar seguro de que vas a poder abstenerte completamente de forma exitosa durante el periodo de abstinencia (máximo, de 3 semanas). Si estás en la mentalidad correcta, lo encontrarás ridículamente fácil.

Para este entonces, si has abierto tu mente como se te pidió al inicio, ya habrás decidido que vas a escapar. Ahora deberías tener sentimientos de emoción, como un perro jalando de la correa, incapaz de esperar para romper los toboganes de DeltaFosB que el porno te creó. Por el contrario, si tienes sentimientos de perdición y oscuridad, debe de ser por una de las siguientes razones: 

* **Algo no se ha solidificado en tu mente.** Relee los 5 puntos enlistados arriba y pregúntate si realmente crees que sean verdaderos. Si dudas en algún punto, relee las secciones apropiadas de este libro. 
* **Temes a la derrota en sí.** No te preocupes, solo sigue leyendo y tendrás éxito. Todo el negocio de la industria pornográfica se basa en un truco de confianza de proporciones masivas. La gente inteligente puede caer por este truco una vez, pero solo alguien tonto, habiendo descubierto cómo funciona el truco, volvería a caer, engañándose a sí mismo. 
* **Estás de acuerdo con todo lo mencionado arriba pero aún te sientes miserable.** ¡No te sientas así! Abre tus ojos, algo increíble está a punto de suceder. Estás a punto de escapar de prisión, pero es esencial que empieces con la mentalidad correcta: _“¡Es maravilloso que ahora sea un no-usuario!”_

Todo lo que tienes que hacer ahora es mantenerte con esa mentalidad durante el periodo de abstinencia, y en los próximos capítulos vamos a lidiar con ciertos puntos específicos para permitirte hacer esto. Después del periodo de abstinencia no tendrás que pensar de esa forma, y empezarás a pensar con esa mentalidad de forma automática; para ese entonces el único misterio será por qué no lo habías visto de esa forma antes. Sin embargo, dos cosas importantes: 

* Retrasa tu plan para hacer tu última visita hasta haber acabado este libro. 
* El periodo de abstinencia de tres semanas ha sido mencionado varias veces, lo cual puede causar un malentendido. En primera instancia, puede que sientas subconscientemente que tendrás que sufrir por 3 semanas. **No tienes que sufrir.** Segundo, evita esa trampa de pensar _“De alguna forma, me tengo que abstener por 3 semanas y hasta entonces, estaré bien”._ Nada mágico va a pasar después de 3 semanas; no te sentirás de repente como un no-usuario, siendo que ellos no se sienten diferente a como se siente un usuario. Si te la pasas deprimido por el hecho de parar durante tres semanas, probablemente te la pases deprimido después de esas 3 semanas. En conclusión, si puedes empezar ahora diciendo _“Nunca más volveré a ver porno, ¿No es maravilloso?”_ después de 3 semanas la tentación se irá. Si por el contrario empiezas diciendo _“Si tan solo sobrevivo 3 semanas sin porno...”_ estarás ansiando una visita a tu harem después de esas 3 semanas. 

Piénsalo de esta forma — tu cerebro quiere que mantengas su estatus quo, así que, si estás bajo la creencia de que estás perdiendo algo bueno al dejar el porno, obviamente te sentirás muy mal. Es imposible forzarte a sentirte de cierto modo si tu cerebro no lo cree así. Es por eso por lo que es importante pasar por este proceso de remover la ilusión de que la pornografía siquiera te retribuye algo. Así es como sabes que no estás sacrificando nada. 

La disfunción sexual tiene mucho que ver con tu cerebro y tu mentalidad de las cosas. El porno configura tu sistema de recompensas y le da a tu cerebro una mentalidad dubitativa. Está duda de ti mismo te causará indudablemente disfunción sexual. Podrás tener todo el deseo en tu parte superior, pero no podrás excitar la parte baja. Te aseguro que es de los golpes más bajos que tu mentalidad puede recibir. La libido, yendo de la mano con el romance, es el elixir de la juventud del cual puedes disfrutar, hasta tu muerte. Tendrás probabilidades altas de evitar la disfunción si decides dejar el porno, pero esa no es la única ganancia. ¡Es tu liberación de esta esclavitud!
