# El periodo de abstinencia {#el-periodo-de-abstinencia}

Por hasta tres semanas después de tu última sesión, podrías estar sujeto a dolores de abstinencia. Los cuales consisten en dos distintos factores, separados entre sí:

* Dolores de abstinencia inducidos por dopamina. Los cuales se interpretan como un sentimiento vacío e inseguro, similar al del hambre. Los identificamos como 'deseos' o como un sentimiento de tener 'que hacer algo'.
* Señales meramente psicológicas que se desencadenan gracias a estímulos externos tales como comerciales, navegación en línea, conversaciones con amigos, series o películas, etc.

El no entender y diferenciar entre estos dos factores te llevará a la derrota si es que usas el método de fuerza de voluntad, y es la razón del por qué muchos de los que lo intentan terminan cayendo en la trampa otra vez. Aunque los dolores de abstinencia no causan dolor físico, no subestimes su poder. Decimos que tenemos un 'dolor de estómago' cuando pasamos un día entero sin comer; puede que tengas leves retortijones estomacales, pero el hambre no es física, como tal. Aun así, el hambre es una fuerza poderosa y es muy probable que nos pongamos irritables a falta de comida. Es similar a cuando nuestro cuerpo está ansioso por una dosis de dopamina, la diferencia es que nuestro cuerpo no pide comida, sino veneno. Teniendo una mentalidad correcta, los dolores de abstinencia son fácilmente superables y desaparecen muy rápido.

Después de abstenerte por unos días usando el MFV, las ansias por descargar dopamina en tu sistema desaparecen. Es el segundo factor — el lavado de cerebro — lo que complica todo. El usuario se ha hecho el hábito de aliviar sus dolores de abstinencia en ciertos períodos y ocasiones, lo que causa una asociación de ideas (_"Vaya, ha sido un día difícil, debería ver porno"_ o _"Estoy en la cama con mi laptop, debería tener una sesión antes de dormir para relajarme"_). El efecto es ilustrado mejor con este ejemplo: Imagina que vives en un lugar cuyo clima es demasiado frío. Te haces al hábito de tener que cerrar todas las ventanas y puertas de tu casa para evitar que se filtre el aire frío hacia adentro. Y puede que incluso después de mudarte a un país de clima árido, sigas teniendo la costumbre de cerrar todas las puertas de tu nuevo hogar, ya que tu cerebro ya asoció la idea de dejar una puerta abierta con la de sentir aire frío.

Detener tu consumo de porno es similar, durante los primeros días tu mecanismo de señales (las cuales te indican cuando descargar dopamina) operará en ciertas ocasiones específicas. Cada vez que esa señal se active, querrás tener una sesión. Por lo tanto, contrarrestar el lavado de cerebro es esencial desde el inicio, ya que, al contrarrestarlo, desaparecerán estas señales. Bajo el MFV, el usuario cree que está haciendo un sacrificio, por lo que se la pasa deprimido, a la espera de que sus incontrolables impulsos se vayan; no se preocupa por remover estos mecanismos de señales y, además, solo deja que se incrementen. De forma similar, cuando un usuario que está dejando la pornografía adopta la mentalidad de _gurú del sexo_, adopta el hábito de preguntarse cuándo irá a convertirse en un Dios, incluso forzándose a no tener pensamientos lascivos, lo cual pavimenta el camino para el autodesprecio, y lo encamina a fallar en su intento.

Un mecanismo de señal común es cuando uno se encuentra soltero, especialmente en eventos sociales con amigos. El ex-usuario que usa otros métodos para dejar el porno ya es miserable por sentirse privado de su ayuda o placer habitual. Por otro lado, sus amigos están actuando de forma íntima con sus parejas. El ex-usuario, o está soltero, o no está 'recibiendo' ningún afecto de su pareja, por lo que ahora no está disfrutando de lo que debería ser una salida con amigos placentera. Al final del día, terminan regresando a su harem de preferencia, cosa que es más fácil de hacer a comparación de excitar a su pareja, o de conseguir una. 

Debido a que el usuario siente que merece de sexo para su bienestar, termina por sufrir de un golpe triple, y el lavado del cerebro se incrementa. Si lo sobrepasan y pueden aguantar lo suficiente, eventualmente aceptarán su destino, y seguirán con su vida. Sin embargo, parte del lavado de cerebro aún sigue intacto; el segundo aspecto más patético de todo esto es que el usuario lo terminó dejando, pero incluso después de varios años aun anhela tener 'solo una última visita a su harem' en ciertas ocasiones. Están aferrados a una ilusión que solo existe en su mente, e innecesariamente, se torturan a sí mismos.

Aun bajo el 'EasyPeasy', responder a estos mecanismos de señal es el error más común. Los ex-usuarios tienden a considerar el porno como un tipo de placebo. Piensan: _"Sé que el porno no hace nada por mí, aunque me resulta de ayuda en ciertas ocasiones"._ Un placebo, a pesar de no tener ningún efecto físico, puede ser una poderosa ayuda psicológica para aliviar síntomas genuinos, y es, por tanto, benéfico. Sin embargo, el porno de internet y la masturbación no son placebos. ¿Por qué? El porno crea los mismos síntomas que alivia, y llegado a un punto, cesa de aliviarlos por completo.

Puede que encuentres más fácil de entender el efecto cuando lo relacionamos con un no-usuario, o con un usuario 'exitoso' que dejó el porno por varios años. Toma el caso de un usuario que tuvo una ruptura con su pareja, donde es bastante común que, con las mejores intenciones, le digan: _"Anda, dale una visita a esta página, te ayudara a calmarte"._ Si la oferta es aceptada, no tendrá ese efecto relajante ya que no el usuario no es adicto a la dopamina y, por lo tanto, no sufrirá el alivio y la relajación que aliviar los dolores de abstinencia te da. En el mejor de los casos, todo lo que hará es darle un momentáneo estimulo psicológico.

Pero incluso después de haber acabado, la tragedia original sigue ahí. De hecho, esta tragedia aumentara su efecto ya que la persona ahora también sufre dolores de abstinencia, dándole la elección de hacer que sus dolores perduren, o de aliviarlos constantemente mediante la repetición de su deslicé en los toboganes neuronales. Todo el porno que le fue provisto le dio un momentáneo estimulo psicológico, el mismo que pudo haber obtenido de haber leído un libro o de haber visto una película, incluso una mala. Varios no-usuarios y ex-usuarios terminan cayendo en la trampa como resultado de estos casos. Así que déjalo claro en tu mente: no necesitas una descarga de dopamina, y solo te estas torturando a ti mismo al continuar apreciando el porno como un tipo de apoyo o estimulo. No hay ninguna necesidad de ser miserable.

Los orgasmos no hacen buenas relaciones; a veces, incluso las arruinan. Además, recuerda que no porque algunas parejas se comporten íntimamente en eventos sociales significa que las disfruten más. De hecho, la intimidad se disfruta mejor en privado, donde las parejas pueden responderse sin vergüenza alguna. Si llegara a haber un roce íntimo con tu pareja, producto natural de una serie de eventos de la vida, está bien, pero trata de disfrutar la ocasión y la vida sin eso.

Después de abandonar el concepto de que el porno es algo placentero por sí mismo, varios usuarios llegan a pensar: _"Si tan solo hubiera algún género de porno limpio"._ Claro que hay porno limpio y suave, y cualquiera que lo prueba termina dándose cuenta de que es una pérdida de tiempo. Déjalo claro en tu mente, la única razón por la que has estado usando porno es por la descarga de dopamina. Una vez que te liberes del ansia por dopamina que te induce el porno, ya no tendrás necesidad de visitar tu harem en línea favorito.

Ya sea que tengas dolores a causa de la abstinencia por dopamina en sí, o por detonantes/mecanismos de señal, acéptalo. El dolor físico no existe, y con la mentalidad correcta, no será un problema. No te preocupes por la abstinencia, el sentimiento por sí mismo no es malo. Es la asociación de quererlo y no poder tenerlo lo que causa el problema. En lugar de abatirte por ello, concientízate: _"Ah, ya sé lo que es, son los dolores de abstinencia. Es lo que los usuarios sufren toda su vida y lo que los mantiene adictos. Los no-usuarios no sufren de estos dolores, es solo otro de los tantos males de esta adicción. ¡¿No es maravilloso que esté purgando estos males de mi cerebro?!"_

En conclusión, dentro de las siguientes 3 semanas, sufrirás de un pequeñísimo trauma, pero conforme pasan, sucederá algo maravilloso. Te estarás librando de una desagradable enfermedad, con los beneficios superando con creces el ligero trauma. Y sorprendentemente, disfrutarás de los dolores de abstinencia. Se volverán momentos de placer, un juego emocionante en el que tienes que matar de hambre el parásito pornográfico que vive dentro de tu estómago, mientras trata de engañarte para que bajes la guardia, y que lo mantengas vivo.

A veces, tratará de hacerte miserable. A veces, te atacará con la guardia baja. Recibirás una URL con porno o te toparás con algo en línea y olvidarás las razones por las que querías dejar el porno, sintiéndote privado cuando lo recuerdes. Prepárate para esos trucos con antelación, y cualquiera que sea la tentación, ten en mente que es el monstruo el que te induce a sentirla. Y cada vez que la resistes, has ganado otro golpe moral en la batalla.

Hagas lo que hagas, no trates de no pensar en porno. Esta es una de las cosas que producen horas de depresión en los usuarios que tratan de dejar el porno usando el MFV. Ellos lo intentan, y pasan cada día esperando que eventualmente lo olviden. Es como cuando eres incapaz de dormir - entre más te preocupas por ello, más difícil se vuelve. De todas formas, no serás capaz de olvidarlo, durante los primeros días el 'pequeño monstruo' te lo seguirá recordando y serás incapaz de evitarlo. Mientras haya laptops, Smartphone, y revistas cerca tendrás recordatorios constantes.

Además, el punto aquí no es olvidar el porno, así que nada malo está pasando. De hecho, algo maravilloso y sorprendente está ocurriendo, y va a ocurrir aún si estás pensando en ello miles de veces al día, así que **saborea cada momento, recuérdate a ti mismo cuán maravilloso es ser libre de nuevo. Trata de recordarte a ti mismo la inmensa alegría de no tener que torturarte a ti mismo.** Como dije previamente, encontrarás que estos dolores se vuelven momentos de placer, y te sorprenderás de lo rápido que te olvidas del porno.

Y hagas lo que hagas, _nunca dudes de tu decisión._ Si empiezas a dudar, comenzarás a deprimirte, y se pondrá peor. En cambio, usa ese momento de tristeza para convertirlo en uno de fortaleza. Si te deprimes por haber dejado el porno, entonces recuérdate a ti mismo que el porno estaba causando esa misma depresión. Si un amigo te envía un URL, siéntete orgulloso y di: _"Estoy feliz de decir que ya no necesito de porno nunca más"._ Eso les dolerá, pero cuando vean que no te molesta estarán a medio camino de unirse a ti.

**Recuerda: tenías razones increíblemente poderosas para detenerte en primer lugar.** Recuérdate a ti mismo los costos y pregúntate si realmente quieres arriesgar las funciones naturales de tu cuerpo, mente, y el simple hecho de que estarás viviendo bajo una ilusión por el resto de tu vida. Sé consciente de los esfuerzos del pequeño monstruo por minimizar los daños y por, sobre todo, recuerda que este sentimiento es temporal, y cada segundo que pasa estás más cerca de tu meta.

Algunos usuarios temen que tendrán que pasar el resto de su vida revirtiendo esas "señales automáticas" que residen en sus vías neuronales. En otras palabras, creen que tendrán que ir por sus vidas engañando a su sistema, diciendo que no necesitan de porno a través del uso de psicología. Esto no es así, recuerda que el optimista ve el vaso medio lleno y el pesimista medio vacío. En el caso de la pornografía, el vaso está vacío y el usuario lo ve lleno. El porno no te da ninguna ventaja. Es el usuario quien ha sido lavado del cerebro para creer que la hay. Y una vez que empiezas a decirte a ti mismo que no necesitas o que no quieres porno, ya no faltara tiempo para que ni siquiera necesites decirlo, terminarás viendo la verdad por ti mismo. Es la última cosa que necesitas hacer; asegurarte de que ver que no hay nada bueno en el porno no sea la última cosa que hagas.
