# ¿Solo UNA pequeña miradita?

Es “solo una miradita” la verdadera ruina de aquellos que utilizan su voluntad para detener el PMO. Podrán abstenerse tres o cuatro días, pero será en vano de haber tenido esta pequeña visita a su harem para levantar su ánimo. Estos usuarios no se dan cuenta de los devastadores efectos que este aspecto tiene en su moral. 

Para muchos usuarios, su primera “miradita” en un harem no parecía ser tan buena y divertida como el sexo real. Aquellos videos que vieron, los de aspecto aparentemente _pulcro_, parecen ser tan distantes entre sí, siendo que algunos videos parecen ser más ‘peligrosos’ que otros, cosa que le da confianza a su mente consciente de que no disfrutan de la pornografía. Estos usuarios piensan _“Bueno, eso no fue disfrutable en lo absoluto. Creo que perdí el apetito y ni siquiera me enganché con las cosas ‘fuertes’.”_ Pero tú ya lo sabes; de hecho, el caso es todo lo contrario. Tenlo claro en tu mente, el disfrute orgásmico no fue la razón por la que quisiste dejar el porno. Si todos los usuarios estuvieran ahí dentro solo para conseguir un orgasmo, no verían más de un clip en una sesión. La única razón por la que necesitas del porno es para alimentar al pequeño monstruo. Solo piensa en lo preciada que resulta esa inusual visita luego de dejar al pequeño monstruo hambriento por cuatro días. Tu mente consciente no se percata de ello, pero esa dosis corpórea de dopamina que tu cuerpo recibe se comunica a través del subconsciente. Estás dosis aisladas le darán voz al pequeño monstruo, quien, a pesar de toda lógica, te dirá que estas sesiones especiales son preciadas, y que quieres otra. 

Esta pequeña miradita tiene dos dañinos efectos:

* Mantiene al pequeño monstruo vivo en tu cuerpo. 
* Y peor aún, mantiene al gran monstruo vivo en tu mente. Si ya tuviste esa pequeña miradita, será más fácil tener la próxima, y la que le sigue. 

El porno es una trampa para ratones: el queso no es lo que aparenta ser, sino veneno. Al usar el MFV convences a tu cabeza de que no tienes que agarrar el queso, bajo ninguna circunstancia. Pero EasyPeasy hace que te percates de que no es queso, sino veneno. No tienes que ‘evitar’ tomarlo, solo no lo haces. 

Por sobre todas las cosas, recuerda:

<span style="text-decoration:underline">_Tener ‘solo una miradita’ es la primordial forma en la que muchas personas inician en primer lugar._</span>
