# ¿Será más difícil para mí? {#sera-mas-dificil-para-mi}

Hay una infinita cantidad de factores que pueden determinar qué tan fácil resulta para un individuo dejar la pornografía. Para empezar, cada uno de nosotros tiene su propio carácter, carrera laboral, circunstancias personales, metabolismo, etc. Ciertas profesiones quizá lo dificulten más que otras, pero ya que el lavado de cerebro sea removido, esto no tendrá que ser así. Toma los siguientes ejemplos:

Ocasionalmente, es más difícil para los miembros de la profesión médica. Pensamos que debería de ser más fácil para los doctores porque ellos están más conscientes de los efectos, pero a pesar de que su profesión les suministra razones más poderosas para dejarlo, no lo hace una tarea más fácil. Las razones son las siguientes:

* El estar constantemente consciente de los riesgos de salud solo crea miedo, una de las condiciones por las cuales tenemos que aliviar los dolores de abstinencia. 
* El trabajo de un doctor es excesivamente estresante, además de que son usualmente incapaces de aliviar los dolores de abstinencia mientras trabajan. 
* Tienen el estrés adicional de la culpa, el sentimiento de que ellos deberían estar poniendo el ejemplo para el resto de la población. Esto les pone más peso sobre sus espaldas e incrementa el sentimiento de privación. 

Después de un duro día de trabajo, y después de que el estrés del trabajo es momentáneamente aliviado por la pornografía, esa sesión se vuelve incorrectamente asociada con el sentimiento de alivio por el descanso. Y debido a esta mala asociación de ideas, el porno se queda con el crédito de toda la situación, convirtiéndose en algo preciado hasta que se intenta renunciar o hasta que el usuario empieza a tener dolores de abstinencia. Este es otro tipo de usuario casual, y se aplica en cualquier otra situación donde el usuario es forzado a abstenerse por largos periodos. Bajo el método de la voluntad, el usuario es miserable porque está siendo privado, y no puede disfrutar del cansancio y sueño extra que le da el letargo de cada sesión. Su sentimiento de pérdida es muy fuertemente incrementado. Sin embargo, si puedes remover el lavado de cerebro y la depresión por no poder ver porno primero, el descanso y el sueño se desasocian del porno, y se pueden seguir disfrutando incluso cuando el cuerpo está anhelando los transmisores de amine - serotonina, dopamina, norepinefrina. 

Otra situación complicada es la del aburrimiento, particularmente cuando es combinado con periodos de estrés. Ejemplos típicos son los de estudiantes o padres solteros, cuyos trabajos son estresantes y, aun así, monótonos. Mientras se intenta detener con su propia voluntad, la persona soltera tiene largos periodos en los que se deprime por su ‘pérdida’, lo cual a su vez incrementa los sentimientos de depresión. Pero, de nuevo, esto se puede sobrellevar si tu mentalidad es correcta. No te preocupes por los momentos del futuro en que experimentes dolores de abstinencia. Usa esos momentos para alegrarte del hecho de que te estás deshaciendo del malvado monstruo. 

Si tienes una mentalidad positiva, estos dolores de abstinencia se convertirán en momentos de placer. Recuerda, cualquier usuario, sin distinción de edad, sexo, inteligencia o profesión puede encontrar que dejar el porno es fácil y disfrutable, **dado que sigan todas las instrucciones.**

## Razones principales por las que puedes fracasar

Hay dos razones principales por las que se puede llegar al fracaso. La primera es la influencia de estímulos externos — un comercial, artículos de internet, búsquedas, etc. Los usuarios llegan a encontrarse a sí mismos en un momento de debilidad, o incluso se ponen celosos cuando ven intimidad en escenarios sociales como una fiesta o reunión. Este tópico ya ha sido discutido extensamente. Usa ese momento para recordarte que no hay tal cosa como una miradita o una visita. Y alégrate en el hecho de que ya has roto la cadena de esclavitud mental. Recuerda que es el usuario el que te envidia y que deberías de sentir pena por ellos, puesto que lo necesitan. 

La otra razón es el tener un pésimo día. Tenlo en mente antes de empezar, seas un usuario o no, vas a tener días buenos y malos. Llueve para el Papa como para el asesino. La vida es relativa y no puedes tener altos sin tener bajos. El problema con el método de la voluntad es que tan pronto el usuario tenga un mal día, van a empezar a ansiar una visita a su ‘harem’, lo que agrava aún más el problema. El no-usuario está mejor equipado para lidiar con el estrés, no solo física sino mentalmente. Si tienes un día duro durante el periodo de abstinencia tómalo por la barbilla; recuerda que los días malos existían cuando eras adicto, de otra forma no habrías tomado la decisión de parar. En vez de deprimirte, reconócelo: _“Okay, así que hoy no ha sido un buen día, pero el porno no lo va a curar. Mañana será mejor y al menos tengo un maravilloso bonus, he dejado esa terrible adicción”._

Cuando eres un usuario, tienes que bloquear tu mente de las negativas del porno. Los usuarios nunca tienen su mente nublada, solo están _‘un poco cansados’._ ¿Cuándo estás teniendo uno de los inevitables problemas de la vida y experimentas un deseo por ver porno, te pones feliz o contento? Claro que no. Una vez paras, la tendencia se vuelve culpar todo lo que va mal en el hecho de que hayas detenido tu consumo.

Si el trabajo te estresa, piensas, _“En tiempos así hubiera tenido una sesión”._ Esto es cierto, pero la cosa más importante que has olvidado es el hecho de que el porno no resolvió tu problema, y simplemente te estás castigando al deprimirte por apoyos ilusorios. Estás creando una situación imposible, siendo miserable porque no puedes ver porno para masturbarte, y aun así siendo más miserable si lo haces. _Sabes que has tomado la decisión correcta al dejar de hacerlo, ¿Así que por qué castigarte al dudar tus decisiones?_

Recuerda, un enfoque mental positivo es esencial — siempre. 
