# Sustitutos

Algunos ejemplos de sustitutos incluyen el restringir tu consumo a revistas pornográficas, imágenes, dietas pornográficas, etc. **NO USES NINGUNA DE ESTAS OPCIONES. ¡NINGUNA!** Solo harán que el dejar la pornografía te sea más complicado. Si llegas a tener un dolor de abstinencia y usas un sustituto para calmarlo, solo harás que se prolongue el dolor. Lo que realmente le estás diciendo a tu mente es que necesitas porno para saciar ese vacío. Sería como ceder ante un intento de secuestro, o a la rabieta de un niño, solo ocasionando que los dolores vayan y vengan, prolongando la tortura. Sea cual sea la situación, los sustitutos no aliviarán tus dolores. Tu ansia es por aminoácidos en el cerebro, y todo lo que va a ocasionar un sustituto es que sigas pensando en porno. Recuerda estos puntos:

* No hay un sustituto para el porno. 
* No necesitas de porno. No es comida, es veneno. Cuando los dolores lleguen, recuerda que son los usuarios los que sufren estos dolores, no los no-usuarios. Ve estos dolores por lo que son, otro mal producido por la droga. Velos como las patadas de ahogado de EL monstruo.
* El porno de Internet crea ese vacío; no lo cubre. Entre más rápido enseñes a tu cerebro que no necesitas del porno, más pronto serás libre. En particular, evita cualquier cosa que asemeje a la pornografía, como revistas para hombres, películas, novelas románticas, y comerciales. Esto no se trata de tener una mente cerrada; está bien hablar de sexo y romance, pero no de pornografía. Siempre hay una manera de encontrar donde y como discriminar. Es cierto que una pequeña porción de usuarios que tratan de dejar el porno viendo _softporn_ o dietas de porno pueden llegar a tener éxito (desde su propia perspectiva), y atribuyen este éxito a dicho consumo. Sin embargo, ellos dejan la pornografía _a pesar de_ su uso y no gracias a ello. Es desafortunado que muchos sigan recomendando estas medidas. 

Esto no es sorpresa para nadie, ya que de no entender en su totalidad la trampa del porno, una dieta o un sustituto más suave sonara como algo lógico para un usuario. Una creencia que a su vez está basada en la creencia de que cuando quieres vencer tu adicción, tienes dos grandes enemigos a vencer: 
	
* Romper el hábito.
* Sobrevivir a los terribles dolores físicos de abstinencia. 

Si tienes dos poderosos enemigos a vencer, es esencial que no pelees con ambos simultáneamente, sino uno a la vez. Así pues, esta teoría dicta que cuando tratas de dejar el porno por primera vez, lo tienes que dejar de consumir por una semana o lo tienes que sustituir por algo más suave. Solo así el hábito es roto, gradualmente reduciendo tu dosis, y por lo tanto tacleando cada enemigo por separado.

Esto suena lógico, pero está basado en información incorrecta e ilógica. El porno no es un hábito, sino una adicción a la dopamina, y el dolor físico de abstinencia en sí es casi imperceptible. Lo que tienes que conseguir a la hora de dejarlo es matar a ambos monstruos, en tu cuerpo y mente, al mismo tiempo. 	EasyPeasy hace fácil dejar el porno de inmediato, porque mata el lavado de cerebro antes de tener tu última sesión. El pequeño monstruo pronto estará muerto, e incluso mientras muere, no seguirá siendo un problema más allá de lo que era cuando eras un usuario.

Solo piénsalo, ¿Cómo es posible que puedas curar una drogadicción recomendando otra droga? Hay muchas historias en línea acerca de aquellos que han escapado de la adicción utilizando porno _Hardcore_, pero que terminan enganchados a géneros mucho _‘más suaves’_, habiendo caído en los caprichos de su pequeño monstruo. No seas ingenuo ante el hecho de que el porno ‘seguro’ no es tan malo - tampoco lo era ese primer clip de alta-velocidad que viste. Todos los sustitutos tienen exactamente el mismo efecto que cualquier otro recurso pornográfico. Algunos incluso empiezan a comer más, pero, aunque ese sentimiento vacío de querer una sesión es casi indistinguible del hambre alimenticio, uno no puede satisfacer al otro. De hecho, si hay algo que esté diseñado para hacerte desear aún más el porno, es llenar tu estómago de comida. Como se dijo previamente, las dietas pornográficas y el porno solo te pondrán en medio del juego de jalar la cuerda, donde poner resistencia a las tentaciones es algo tan molesto, que dicha molestia se aliviará solo si das una visita a tu harem de internet favorito. 

El mayor defecto de los sustitutos es que prolongan el verdadero problema, el lavado de cerebro. ¿Necesitas un sustituto para lidiar con la gripe cuando te curas? Claro que no. Al decir que necesitas de un sustituto, lo que realmente estás diciendo es que estás haciendo un sacrificio. La depresión asociada con el método de voluntad es causada por el hecho de que el usuario cree que está haciendo un sacrificio. Todo lo que se está haciendo es sustituir un problema por otro. No hay placer en llenar tu cuerpo de comida, de humo de cigarro o de alcohol. Solo te pondrás gordo, miserable y en poco tiempo estarás de vuelta en tu droga predominante. 

Los usuarios casuales encontrarán difícil el despedirse de la creencia de que están siendo privados de su pequeña recompensa, como aquellos a los que no se les permite entrar a Internet durante un periodo vacacional familiar, un evento social, etc. Algunos dicen _“No sabría cómo relajarme si no fuera por el porno”._ Eso prueba el punto, a veces los usuarios no toman ese descanso como debe de ser porque, en su estado de adicto — llamándolos por lo que son — necesitan deshacerse de _esa comezón_, de sus dolores de abstinencia. 

Recuerda, las sesiones de porno nunca serán recompensas genuinas. Son el equivalente de ponerse zapatos incómodos solo para poder sentir el placer de quitártelos. Así que, si sientes que debes de tener una pequeña recompensa, deja que ese sea tu sustituto; antes de ir a trabajar, ponte zapatos de una talla demasiado pequeña, y no te los quites hasta que tengas un descanso; solo entonces, experimentarás el maravilloso momento de relajación y satisfacción a la hora de quitártelos. Quizá pienses que eso es algo un poco estúpido. Estas absolutamente en lo correcto. Puede ser difícil visualizar esto mientras sigues en la trampa, pero eso es lo que los usuarios hacen. También es difícil visualizar que pronto no necesitarás de esa pequeña ‘recompensa’, y que pronto observaras a tus amigos que siguen en la trampa con genuina pena, y que empezarás a preguntarte porque no pueden verlo desde ese punto.

Sin embargo, si sigues engañándote a ti mismo con la idea de que una visita a tu _harem en línea_ es una verdadera recompensa, o de que necesitas un sustituto, te sentirás privado y miserable. Hay una probabilidad enorme de que termines cayendo en la asquerosa trampa de nuevo. Si en verdad necesitas de un descanso genuino como lo necesitan las amas de casa, los maestros, doctores, o como otros trabajadores necesitan, vas a empezar a disfrutar más estos descansos ya que no tendrás que volverte adicto de nuevo. Recuerda que no necesitas de un sustituto. Los dolores de abstinencia son tu anhelo por dopamina, los cuales pronto serán desvanecidos. Deja que esto sea tu apoyo por los próximos días, y disfruta de deshacer de tu cuerpo y mente la esclavitud y dependencia. 
