# ¿Debería evitar cualquier situación de tentación?

Cuando te aconsejamos que evites a toda costa el uso de sustitutos, te lo mencionamos más como una instrucción que como una sugerencia; consejo que está respaldado por varias, prácticas razones, las cuales están respaldadas a su vez por cientos casos de estudio. Sin embargo, con la pregunta de si evitar o no involucrarte con tu sexualidad, este no es el caso. Cada usuario debe tomar esa decisión por su cuenta. Sin embargo, podemos compartir dos buenas sugerencias para ayudarte a través de este proceso. Es el miedo a los dolores de abstinencia lo que nos mantienen usando pornografía, por el resto de nuestros días; y este miedo consiste de dos fases distintas:

_**Fase Uno: ¿Cómo podré sobrevivir sin porno?**_

El miedo que acabamos de mencionar es ese sentimiento de pánico que el usuario siente cuando está soltero o tiene una pareja asexual, desinteresada o no disponible en el momento. Y este miedo, a su vez, no es causado por los dolores de abstinencia en sí, sino por el miedo psicológico de tener dependencia, de ser incapaz de sobrevivir sin tener ni sexo ni orgasmos. El miedo llega a su máxima en el periodo en que se intenta dejar la pornografía, justo cuando tus dolores de abstinencia están en su más baja. Es miedo a lo desconocido, esa clase de miedo que la gente siente cuando empieza a aprender a hacer caída en picada hacia una piscina. 

La plataforma de salto está a medio metro de la piscina, pero parece estar a casi 2 metros. La profundidad de la piscina es de 2 metros, pero parece ser de medio metro. Requiere de coraje el poder saltar, y más aún si estás convencido de que vas a caer de cabeza al suelo. El salto es en sí la parte más difícil, pero si encuentras el coraje para hacerlo, ¡lo demás es fácil! Esta alegoría explica por qué muchos usuarios de fuerte voluntad nunca han intentado parar, o por qué no pueden sobrevivir más allá de unos cuantos días cuando se lo proponen. De hecho, solo hasta que deciden parar, algunos usuarios que a su vez decidieron usar una dieta de porno terminan por escalar rápidamente a géneros y videos mucho más fuertes de lo que hubieran visto de no haber decidido parar. Esta decisión les causa pánico, lo cual es estresante y desencadena a su vez una señal para volver a entrar a su sitio de preferencia. Pero claro, recuerdan que no pueden volver a entrar, se lo prometieron; cosa que a su vez les causa sentimientos de privación y estrés compuesto.

Sé que te has sentido así, pero no te preocupes. El pánico es solo psicológico. Es el miedo a que quizá, eres dependiente. La buena noticia es que no lo eres, ni siquiera cuando eres un adicto. No entres en pánico, lánzate directo a la piscina. 

_**Fase Dos: Miedo a los efectos a largo plazo**_

La segunda fase es a largo plazo, involucrando el miedo de que ciertas situaciones en el futuro no serán igual de disfrutables como antes, o de que no serás capaz de lidiar con el trauma sin poder ver porno. No te preocupes, si puedes dar _‘el salto a la piscina’_ encontrarás que la situación es todo menos eso. El evitar estas situaciones de tentación puede dividirse en dos categorías:

* _“Voy a intentar una dieta de porno, usándolo cada cuatro días. Me sentiré en confianza sabiendo que de todas formas puedo entrar a Internet si llego a fallar. Cosa que está bien. Si llega a pasar solo tengo que agregar más días a mi ciclo.”_  
La cantidad de gente que falla utilizando este método es **mucho más alta** que la de aquellos que dejan el porno en grupo. Esto se debe principalmente al hecho de que, si estás pasando por un mal momento durante el periodo de abstinencia, es fácil saltar directo al buscador y visitar tu harem sin excusa. Pero, si no tienes la dignidad para romper tus propias reglas como si se tratasen de finas ventanas de cristal y decides no premiarte con porno, será más fácil para ti poder sobrellevar la tentación. Sin embargo, la razón principal por la que la tasa de derrota en estos casos es tan grande es porque el usuario no se sentía tan comprometido a parar en primer lugar. Recuerda, hay dos cosas esenciales que necesitas para tener éxito:  
    * Certeza.
    * _“¿No es maravilloso que ya no necesito del porno?”_

    \   
    En cualquier caso, ¿Para qué necesitas una sesión? Si todavía sientes esa necesidad, 	vuelve a leer el libro primero. Hay ideas que aún no se solidifican. Tomate el tiempo 	para matar al monstruo que el lavado de cerebro crea. 

* *“¿Debería evitar situaciones de estrés o algún evento social en el periodo de abstinencia?*  
En el caso de las situaciones de estrés, sí. No tiene caso el ponerte presión de más. En el caso de los eventos sociales, como ir a un bar o a un antro, el consejo es a la inversa. Sal y diviértete, no necesitas del sexo o de la parte propagativa del mismo mientras eres un adicto para disfrutar de la vida. Sal y alégrate del hecho de que no necesitas del sexo, y verás rápidamente que la vida es bella sin tener este tipo de presiones en el pecho. Solo piensa en lo bien que te irá al haberte deshecho del pequeño monstruo, junto con todas las pequeñas necesidades y trucos que este conlleva.
