# El momento de la revelación

Usualmente, dado que haya pasado un lapso de 3 semanas después de haber dejado la pornografía, los ex-usuarios experimentan _el momento de revelación_. El cielo parece tornarse más brillante, y el lavado de cerebro por fin ha sido mitigado. Es cuando, en vez de decirte a ti mismo que no necesitas ver porno, de repente empiezas a darte cuenta de que el último hilo ha sido cortado, y que puedes disfrutar de tu vida sin necesitar de porno nunca más. También es en este punto donde empiezas a ver a los usuarios con pena de nuevo. 

Los que utilizan el método de la voluntad no suelen experimentar este momento porque a pesar de ser ex-usuarios felices, siguen yendo por la vida pensando que están haciendo un sacrificio. Entre más tiempo hayas pasado siendo un adicto, mucho más maravilloso será experimentar esta revelación y mayor será el tiempo que dure ese sentimiento. En tu vida van a haber muchas alegrías que te harán la vida más amena, alegrías que al final del día probablemente termines olvidando. Pero la alegría de no tener que consumir porno nunca más, es diferente; solo trata de recordar lo maravilloso que es no estar enganchado a esta droga cada vez que te sientas triste o deprimido. Hay algunos que incluso lo catalogan como el mayor logro de sus vidas. Y en algunos casos, incluso experimentan este momento de revelación no en 3 semanas, sino hasta algunos días después. 

En mi caso, pasó después de haber acabado mi última visita. Pero estoy seguro de que algunos lectores, incluso antes de haber acabado el libro habrán dicho ya: _“No digas ni una palabra más. Lo puedo ver claramente. Sé que no necesitaré del porno nunca más.”_ Basándome en la retroalimentación recibida, esto pasa frecuentemente. Y en teoría, dado que hayas seguido todas las instrucciones correctamente y entiendas la psicología del adicto por completo, esto debería pasarte casi de inmediato. 

Pero, aunque ya se ha dicho que te toma como cinco días para que la abstinencia física se haya ido, y como tres semanas para que el ex-usuario sea libre, esas pautas pueden llegar a causar dos problemas. El primer problema es que se sugestiona a los usuarios a pensar que tendrán que sufrir de cinco a tres semanas. El segundo es que los usuarios tienden a pensar _“Si puedo sobrevivir por cinco días y hasta tres semanas, podré notar un notable estímulo para cuando este período acabe.”_

Quizá tengan una tanda de cinco días muy placenteros, seguidos de una desastrosa tanda de días malos, los cuales no tienen nada que ver con la adicción, sino por otros factores. Es entonces cuando este ex-usuario, quien ha estado esperando este momento de revelación, experimenta un periodo de depresión a cambio. Esto podría destruir su confianza. Sin embargo, y por el otro lado de la moneda, si no hubiera una pauta, el ex-usuario entonces pasaría el resto de su vida esperando el momento de revelación. Cosa que suele pasar con aquellos que deciden usar su voluntad para parar. 

La gente suele preguntarme acerca del significado detrás de la pauta de ‘cinco días a tres semanas.’ ¿Acaso son periodos sacados de la nada? No, aunque no son fechas exactas, son sacadas a su vez de retroalimentación que fui acumulando durante los años. Es hasta después de cinco días cuando, usualmente, el usuario saca la adicción completamente de su cabeza. Muchos ex-usuarios experimentan la revelación alrededor de este periodo, generalmente en situaciones estresantes o situaciones sociales las cuales no habrían podido sobrellevar sin una visita a su harem. Y entonces te das cuenta de que no solo estás lidiando o disfrutando de la situación, sino que la sola idea del porno no ha llegado a pasar por tu mente. Es desde ese punto cuando se vuelve plenamente sencillo. Es cuando sabes que, por fin, eres libre. 

Es tanto mi experiencia como la de otros que intentaron parar usando su voluntad la que dicta que después de tres semanas es cuando los más serios intentos de parar son fallidos. Lo que usualmente pasa es que después de tres semanas sientes que has perdido las ganas de ver porno. Pero te lo tienes que probar, así que (irónicamente) haces la clásica ‘miradita’ y entras al modo incógnito. Se siente raro tener que probar que ya lo habías dejado. Pero en el proceso terminas engrasando los toboganes pornográficos con DeltaFosB gracias al subidón repentino de dopamina, eso por lo que tu cuerpo ha estado anhelando por tres semanas. Y tan pronto acabas, la dopamina se esfuma de tu cuerpo. Y un viejo amigo vuelve a aparecer, diciendo _“No lo has dejado, y quieres hacerlo de nuevo”._

Obvio que no te escabulles a tu harem de nuevo porque no quieres engancharte otra vez, así que dejas que un periodo corto pero seguro pase. Y cuando vuelves a ser tentado, dices _“Bueno, no me enganche otra vez y este período seguro prueba mi argumento. Así que, otra miradita tampoco me hará daño.”_ Y otra vez, de vuelta al tobogán. La cosa es que, la clave con el momento de revelación no es esperar el momento de revelación, sino darte cuenta de que una vez cierras tu buscador, ahí se acabó. Dejaste de ser un adicto. Has cortado el suministro de oxígeno del pequeño monstruo. Y no hay fuerza en la tierra que pueda prevenirte de que seas libre de su yugo, <span style="text-decoration:underline">_a menos que te la pases deprimido porque ya has parado o que te quedes esperando el momento de revelación._</span> Así que ve, disfruta de tu vida; lidia con ella desde el punto en que cierres el buscador. El momento llegará pronto. 
