# La última visita {#la-ultima-visita}

Habiendo decidido el momento adecuado, ya estarás listo para visitar tu harem por última vez. Pero antes de que lo hagas, considera estos dos elementos esenciales:

* ¿Te sientes seguro de que tendrás éxito?
* ¿Tienes algún sentimiento de perdición y oscuridad, o un sentimiento de emoción? ¿Sientes que estás a punto de lograr algo maravilloso?

Si tienes alguna duda, entonces vuelve a leer el libro primero. Recuerda que nunca decidiste caer en la trampa del porno, trampa que está diseñada para esclavizarte de por vida. Y para poder escapar, primero necesitas tomar la decisión positiva de que vas a parar, y de que tendrás tu última visita.

Recuerda, la única razón por la que has leído el libro hasta aquí es porque añoras dejar el porno. Así que toma esa decisión positiva, ahora. Realiza el solemne voto de que cuando cierres la _pestaña incógnita_ de tu navegador, ya sea que te parezca algo fácil o difícil, no volverás a visitar ese lugar nunca más. Quizás estés preocupado por haber hecho este voto varias veces en el pasado, y que sigas fallando, o porque tendrás que pasar por un trauma terrible a pesar de tomar el voto. No tengas miedo, la peor cosa que podría pasar es que fracases, y recuerda, no tienes absolutamente nada que perder, sino todo lo contrario.

Deja de pensar en el fracaso, la verdad es que no solo es ridículamente sencillo dejarlo, sino que incluso puedes disfrutar del proceso. ¡Esta vez vas a usar EasyPeasy! Todo lo que necesitas hacer es seguir estas simples instrucciones:

* Tomar el solemne voto de que dejarás el porno ahora, y tomarlo en serio.
* Ten una sesión consciente. Navega entre videos y clips tratando de buscar los intentos desesperados de los administradores de la página, actores e incluso de amateurs por aumentar en ti el sentimiento de shock, novedad y de naturaleza supranormal, y pregúntate dónde se supone que está el placer en su contenido.
* Cuando finalmente cierres el navegador, no lo hagas con la mentalidad de _"no debo visitar otra página porno de nuevo"_, o _"no tengo permitido visitar otro sitio como este"_, en vez de eso, hazlo con un sentimiento de libertad: _"¿No es genial? ¡Soy libre, ya no soy un esclavo de la pornografía! No tendré que visitar estos asquerosos sitios de nuevo."_
* Sé consciente de que, en los próximos días, habrá un pequeño saboteador de la pornografía en tu estómago. Puede que solo estés consciente de sentir el deseo de querer una sesión. Y a pesar de que nos hemos referido al pequeño monstruo de la pornografía como ese pequeño anhelo físico por dopamina, es una forma incorrecta de verlo y es importante entender por qué. Dado que toma unas tres semanas para que ese pequeño monstruo muera, los ex-usuarios creen que el pequeño monstruo les continuará demandando después de la última visita, y por lo tanto estos ex-usuarios sienten que tendrán que usar su fuerza de voluntad para resistirse a la tentación durante este período. Esto no es así, el cuerpo no anhela la dopamina inducida por pornografía — es el cerebro el que lo desea.

Si llegaras a sentir esas ganas por ver porno en los siguientes días, tu cerebro tendrá una decisión simple. Puede interpretar ese sentimiento por lo que en realidad es — un sentimiento vacío de inseguridad que empezó desde la primera visita a un sitio de porno, sentimiento que se va perpetuando más por cada sesión subsecuente — solo para que te digas a ti mismo: _**"¡ESTUPENDO! ¡YA NO SOY UN USUARIO!"**_

O, puedes seguir con el antojo de pornografía, y sufrirlo por el resto de su vida. Piensa por un momento. Seguir sufriendo sería increíblemente estúpido, ¿no? ¿Decir _"no quiero volver a ver porno"_, y entonces pasar el resto de tu vida diciendo a su vez _"me encantaría dar otra visita..."_? Eso es lo que el método de la fuerza de voluntad hace con estos usuarios, y no hay duda del porqué se sienten tan miserables. Pasan gran parte de sus vidas desesperadamente deprimidos por algo que desean desesperadamente y nunca tendrán. No hay duda de que pocos intentos dan resultados y que algunos de esos pocos usuarios exitosos nunca se sienten completamente libres.

> "Hágase esta imagen mental y hágala clara en su mente, ya que puede ser muy útil para superar el poder que los estímulos externos tienen sobre usted. Véase usted mismo sentado, callado, dejando que el teléfono suene, ignorando su timbre. Indiferente a su mandato. Aunque esté consciente del timbre, ya no le importa ni le obedece. A su vez, haga claro en su mente el hecho de que esta señal externa en sí misma ya no tiene poder sobre usted. No tiene el poder para moverlo. En el pasado le hubiera obedecido, le hubiera respondido, por pura fuerza de hábito. Pero ahora usted puede, si lo desea, formar un nuevo hábito: el de no responder.  
También tenga en cuenta que su éxito, el no contestar, no consiste en hacer algo, o en hacer un esfuerzo, ni en resistirse o pelear, sino en hacer absolutamente nada — consiste en la tranquilidad de no hacerlo. Usted simplemente descansa, ignora las señales y deja que la llamada sea desatendida. El timbre de un teléfono es una analogía simbólica a cualquier otro estímulo externo el cual puede que le haya dado control de forma habitual, y que en cambio decide alterar intencionalmente."  
- Maxwell Maltz, "The New Psycho Cybernetics" capítulo 12

Es solo la duda y el estar esperando a que pase algo lo que hace difícil dejar el porno. _**Así que nunca dudes de tu decisión.**_ Sabes que tomaste la decisión correcta. Si empiezas a dudarlo, te pondrás en una situación sin salida. Serás miserable por querer visitar ese harem en línea, sin poder a su vez, visitarlo. No importa qué sistema uses, ¿qué intentas lograr al renunciar a la pornografía? ¿No verlo nunca más? Muchos ex-usuarios hacen eso, pero terminan pasando el resto de sus vidas sintiéndose privados.

¿Cuál es la diferencia entre usuarios y no-usuarios? Los no-usuarios no tienen ninguna necesidad o deseo de ver pornografía, y no tienen las ganas ni la urgencia de ejercitar su fuerza de voluntad para no verlo. Eso es lo que intentas lograr y está completamente dentro de tu poder hacerlo. No tienes que esperar a que el deseo por ver pornografía se vaya o esperar a convertirte en un no-usuario, esto se consigue el momento en el que cierras esa última pestaña en tu navegador, cortando el suplemento de dopamina: **¡YA ERES FELIZMENTE UN NO-USUARIO!**

Y seguirás siendo un no-usuario feliz siempre que:

* Nunca dudes de tu decisión.
* No esperes a transformarte en un no-usuario. Si lo haces, solo estarás esperando a que no pase absolutamente nada, y crearás una fobia.
* No intentes _no pensar_ en porno (¿el caballo blanco?) y no esperes a que venga el "momento de la revelación", solo crearás un miedo irracional.
* No uses ningún sustituto.
* Veas a los usuarios como en realidad son y que sientas pena por ellos, en vez de tenerles envidia.

Ya sea que tengas días buenos o malos, no cambies tu vida solo porque has renunciado al porno. Si lo haces, estarás haciendo un sacrificio cuando no hay necesidad. Recuerda, no has renunciado a vivir. No has renunciado a nada. Por el contrario, te has curado de una terrible enfermedad y has escapado de una prisión insidiosa. Mientras los días pasen, y tu salud — tanto física como mental — mejore, los altos en tu vida serán más altos y los bajos cada vez menos bajos que cuando eras un usuario. Y siempre que pienses sobre el porno durante los siguientes días o por el resto de su vida, solo piensa para ti mismo:

**"¡ESTUPENDO! ¡SOY UN NO-USUARIO!"**

## Una última advertencia

Ningún usuario, dado que tuviera la oportunidad de volver en el tiempo a momentos antes de engancharse, y con el conocimiento que tiene ahora, optaría por comenzar. Miles y miles de personas, quienes satisfactoriamente dejaron el hábito después de muchos años, llevan vidas perfectamente felices, solo para ser atrapados por el porno una vez más. Confío en que este libro les ayudará a encontrar relativamente fácil el dejar el porno. Pero te advierto, los usuarios que encuentran sencillo dejarlo, les resulta recíprocamente sencillo empezar de nuevo. **No caigas en esa trampa.**

No importa por cuánto hayas parado o qué tan seguro estás de que no te engancharás nuevamente. Haz de esta regla una regla de por vida: no volverás a ver pornografía por ninguna razón. Resiste a las alusiones e insinuaciones de los medios (de comunicación), y recuerda cómo impulsan su propia imagen de "mente abierta", poniendo pornografía en todo contenido que sea _mainstream_, sin _"darse cuenta"_ de que la pornografía, el porno de internet y la masturbación compulsiva son asesinos de relaciones y del sentido personal de bienestar para un gran número de hombres y de algunas mujeres.

Recuerda, solo _una miradita_ o visita no hará nada por ti. Crearás dolores de abstinencia que aliviar y te hará sentir muy mal. Solo pondrás el placer por dopamina de vuelta en tu mente y en tu cerebro, además de darle paso al regreso de una pequeña voz en lo profundo de tu mente, que te estará diciendo que _quieres más_. Entonces tendrás la decisión de ser infeliz por un tiempo, o de empezar todo el mugriento ciclo de nuevo.
