# Retroalimentación {#retroalimentacion}

La guerra no es en contra de los usuarios, sino en contra de la tramposa industria pornográfica; una guerra que me gusta librar por la simple razón de que la disfruto. Cada vez que escucho acerca de un usuario que está escapando de la prisión, obtengo un sentimiento de inmenso placer. Pero este placer no se ha conseguido sin haber pasado primero por una considerable frustración, principalmente causada por dos tipos de usuario. A pesar de la advertencia que puse en capítulos anteriores, sigo continuamente sorprendido por el número de personas que lo encuentran fácil de dejar, y que, aun así, vuelven a engancharse y descubren que no pueden tener éxito la siguiente vez.

Es como encontrar a alguien en un pantano, con el agua hasta el cuello y a punto de hundirse por completo. Lo logras sacar de ahí y este te agradece de todo corazón, solo para que meses después vuelvas a pasar por el mismo pantano y encuentres a la misma persona a punto de dar un clavado dentro, de nuevo. Los usuarios que les parece sencillo dejarlo y empiezan de nuevo poseen un problema especial. Sin embargo, si consigues librarte de la adicción, **POR FAVOR, POR FAVOR NO COMETAS EL MISMO ERROR.** Estos usuarios creen que regresaron a la adicción porque siguen enganchados y que extrañan la dopamina. De hecho, confían en que parar es tan fácil que perderán su miedo a la pornografía. Piensan, _"puedo tener una sesión de vez en cuando, y si me engancho de nuevo, podré sencillamente dejarlo"_.

Me temo que no funciona así, es fácil dejar de ver pornografía, pero es imposible controlar la adicción. Lo esencial para detener tu consumo de porno es no usarlo.

El otro tipo frustrante de usuario es aquel que está muy asustado como para intentar controlar la adicción, o que cuando lo hace, le parece una gran lucha. La dificultad que este usuario experimenta puede residir en los siguientes factores:

**Tiene miedo al fracaso.** No hay vergüenza en el fracaso, y ni siquiera intentarlo es algo bastante estúpido. Velo de esta manera, te estás escondiendo de nada. La peor cosa que puede pasar es que falles, en cuyo caso no estarás en un peor estado que el de ahora. Solamente piensa en lo maravilloso que sería triunfar. Si no haces el intento, ya está garantizado tu fracaso.

**Tiene miedo al dolor y a ser miserable.** No te preocupes por eso, piensa: ¿qué sería lo peor que te pasaría si dejaras de ver pornografía? Absolutamente nada. _Pasarán cosas terribles_ si continúas, vuelve a leer las notas sobre la apuesta de Pascal. En cualquier caso, el pánico es causado por la dopamina, pánico que pronto desaparecerá. La mayor ganancia es deshacerse de este miedo. ¿De verdad crees que los usuarios están preparados para desarrollar disfunción, tener un desempeño sexual deplorable, o a tener el placer ilusorio que consiguen del porno? Si llegas a entrar en pánico, respira profundamente. Si estás con otras personas y estas te recuerdan que has escapado de la adicción, a la par de hacer que te deprimas por ello, aléjate de ellos y ve a algún garaje, a una oficina vacía o a cualquier lugar solitario.

Si tienes ganas de llorar, que no te dé vergüenza. Llorar es una forma natural de liberar tensión. No hay nadie que no se sienta mejor después de haber llorado. Una de las terribles cosas que hacemos nosotros los hombres jóvenes es condicionarnos a no llorar. De seguro has visto cómo algunos luchan consigo mismos para no llorar, y que a su vez puedes ver como sus mandíbulas están rechinando. Nos enseñamos a nosotros mismos a no mostrar emociones, cuando estas emociones no están destinadas a ser reprimidas en el interior. Grita, vocifera o suelta insultos al aire. Patea algo. Considera tu lucha como un combate de boxeo que no puedes perder. Nadie puede parar el tiempo, y cada momento que pasa ese pequeño monstruo dentro de ti, está agonizando. Disfruta de tu victoria inminente.

**No siguió las instrucciones.** Es increíble ver que algunos usuarios dicen que este método no funcionó para ellos. Solo para después comentar que no solo ignoraron una instrucción, sino todas las instrucciones. Para hacerlas más claras, estas instrucciones están resumidas en forma de lista al final de este capítulo.

**Malinterpretó las instrucciones.** Lo cual se expresa en los siguientes puntos:

* **"No puedo dejar de pensar en porno":** Por supuesto que no puedes, y si lo intentas, solo crearás una fobia, convirtiéndote en un desdichado. Es como intentar dormir en la noche; cuanto más lo intentas, más difícil se vuelve. No importa si piensas en porno el 90% de tu vida, lo que reflexionas al respecto es lo importante. Si piensas _"oh, amo ver porno"_ o _"¿cuándo seré libre?"_, serás miserable. Si en vez de eso piensas _"¡Estupendo! ¡Soy libre!"_, serás feliz.
* **"¿Cuándo morirá el pequeño monstruo?":** El flujo de dopamina saldrá de tu cuerpo muy rápidamente, sin embargo, es imposible discernir cuándo es que tu cuerpo dejará de saciar estas pequeñas dosis de dopamina. Este sentimiento de inseguridad es idéntico al del hambre, depresión o al estrés. Todo lo que hace el porno es incrementar el nivel de ese sentimiento. Es por eso que los usuarios que usan el método de fuerza de voluntad nunca están seguros si se deshicieron del monstruo, incluso después de que su cuerpo ha dejado de sufrir la abstinencia de dopamina. Si se sufre de hambre o estrés, el cerebro del usuario le seguirá diciendo que eso es una razón válida para poder tener una sesión. El punto es que no tienes que esperar a que el antojo se vaya, es tan leve que ni siquiera sabemos si está ahí, solo lo entendemos como un sentimiento de deseo. Cuando sales del dentista, ¿esperas a que tu mandíbula deje de doler? Por supuesto que no, sigues con tu vida. Incluso si tu mandíbula te sigue doliendo, sales del consultorio eufórico por haberte curado.  
No esperes a que se vayan los dolores de abstinencia, sino crearás dudas en ti mismo al preguntarte constantemente: _"¿Cuánto tiempo tomará esto? ¿Soy siquiera libre si no me siento diferente?"_ El miedo es una verdadera angustia, por lo tanto, esperar a que te pongas mejor después de renunciar solo creará dudas. La abstinencia es imperceptible a menos que le temas, y las mejoras neurológicas son lentas, así que, si esperas a que te sientas diferente, sentirás como si nada hubiera pasado, generando duda.
* **"El 'momento de la revelación' no ha llegado":** Si esperas este momento, solo estarás causando otra fobia. Una vez paré por tres semanas con el MFV. Y charlando con un viejo amigo, me preguntó cómo me estaba yendo. _"He sobrevivido tres semanas"_, respondí. Él contestó, _"¿A qué te refieres con que has 'sobrevivido' por tres semanas?"_, le clarifique, _"He pasado por tres semanas sin ver pornografía."_ Él dijo, _"¿Y qué vas a hacer ahora? ¿Sobrevivir por el resto de tu vida? ¿Qué esperas? Lo has conseguido, ya eres un no-usuario."_  
Pensé, _"Tiene toda la razón, ¿Qué estoy esperando?"_ Desafortunadamente, y debido a la falta de entendimiento de la trampa, estaba a punto de fallar en ese intento, pero entiendes el punto. Te conviertes en un no-usuario cuando cierras el navegador. Lo importante es ser un no-usuario feliz desde el principio.
* **"Sigo con el antojo de porno":** Entonces estás siendo estúpido. ¿Cómo puedes proclamar ser un no-usuario y entonces decir que quieres ver porno? Es una contradicción. Si dices que quieres ver pornografía, estás diciendo que quieres ser un usuario. Los no-usuarios no quieren visitar esos desagradables sitios. Ya sabías lo que querías ser, así que deja de castigarte a ti mismo.
* **"He optado por dejar de vivir":** ¿Por qué? Todo lo que tienes que hacer es dejar de matar a tu cuerpo y empezar a energizarte. No tienes que parar de vivir lo más mínimo. Es así de simple, solo tendrás un leve trauma en tu vida. El cuerpo sufrirá la agravación casi imperceptible de abstinencia, de demandas y reclamos por querer ese aumento de dopamina. Ahora, ten en cuenta lo siguiente: no eres peor de lo que eras antes. Este mal es por lo que has estado sufriendo durante toda tu vida, cada vez que has estado somnoliento, en la iglesia, en el supermercado o en la biblioteca. No parecía molestarte mientras eras un usuario y si no paras ahora, seguirás sufriendo esta angustia por toda tu vida.  
La pornografía y los orgasmos no crean ocasiones especiales, te privan de ellas. Incluso mientras tu cuerpo siga teniendo antojo de dopamina, las cenas y las reuniones sociales se volverán aún más maravillosas. La vida es así de maravillosa, solo sal con tus amigos, incluso si van a un bar _'striptease'_. Recuerda que tú no eres el que está privado de este tipo de ocasiones, sino los usuarios. Disfruta de ser el protagonista y centro de atención. Incluso, el detener la pornografía es un maravilloso tema de conversación, dado que obtuviste un placer secreto que otros no pueden obtener. Tus amigos y conocidos, quienes te consideraban como alguien triste y tímido, estarán sorprendidos de ver que ahora eres el más feliz y alegre del lugar. Disfrutarás de tu vida desde el principio, y ni siquiera habrá necesidad de envidiar a los _artistas del ligue_ cuando vayas a fiestas, estos te estarán envidiando a ti — si tan solo supieran.
* **"Soy infeliz e irritable":** Esto es por no seguir las instrucciones. Encuentra cuál de todas es. Algunas personas entienden y creen todo lo aquí escrito, pero aun así empiezan con una sensación de fatalidad y tristeza, como si algo terrible fuera a suceder. Anímate, no solo estás haciendo lo que te gustaría hacer, sino también lo que a cualquier usuario del planeta le gustaría. Como con cualquier otro método para dejarlo, el ex-usuario estará tratando de conseguir cierto estado de ánimo, por lo que cada pensamiento que tenga que ver con porno siempre es respondido con un _"WOW, SOY LIBRE"_. Si ese es tu objetivo, ¿por qué esperar? Empieza con un buen estado de ánimo ahora, y no lo pierdas. No hay de otra.
* **"Tuve una buena semana / un buen mes / unos buenos seis meses, pero aun así caí de nuevo en la trampa":** Haz memoria, el miedo es el dolor en sí. Entregarte al dolor solo genera más miedo, alimentando al ya debilitado monstruo pequeño, el cual termina por asustar al no-usuario, haciendo que piense que ya está enganchado de por vida. No es que hayan olvidado cómo funciona el lavado de cerebro, sino que le dieron espacio a su mente para pensar y extrañar la dopamina. Puede que hayan podido caer hacia adelante, pero siguen sin entender las instrucciones. Por lo cual, te dejo la ya mencionada lista. Léela y piensa cuál de las siguientes instrucciones falta de solidificarse en tu mente.

## Lista de verificación

Es imposible fallar si sigues las siguientes instrucciones:

* Haz un voto solemne de que nunca entrarás a la web para visitar tu harem favorito, NI por imágenes, NI por contenido erótico, NI por nada que contenga algún estímulo supranormal; y apégate a ese voto.
* Tenlo en claro: no hay nada a que rendirse. Y eso no significa que serás mejor persona si eres un no-usuario (eso ya lo sabes); ni que, a pesar de que no hay razón racional del por qué continúas tu adicción, obtienes algún tipo de placer o ayuda del porno, ya que de lo contrario no querrías dejarlo. Lo que significa que _**no hay placer o alivio genuino en consumir porno y masturbarte**_. Solamente es una ilusión, como chocar tu cabeza contra la pared para obtener el placer de detenerte.
* No hay tal cosa como un adicto de por vida. Solo eres uno de los cientos de millones que han caído en la trampa. Y como cualquiera de los millones de ex-adictos que una vez pensaron que no podrían escapar, ya has escapado.
* Si en algún momento de tu vida llegas a comparar los pros y contras de la adición, recuerda que la abrumadora conclusión siempre será _"¡deja de hacerlo, eres un tonto!"_ Nada cambiará eso. Siempre ha sido así y siempre lo será. Habiendo tomado lo que sabes que es la decisión correcta, no te tortures con la duda. La apuesta de Pascal aplica perfectamente con la adicción; no hay posibilidades de perder a lo grande, hay grandes posibilidades de ganar, y nada que perder en lo absoluto.
* No intentes no pensar en porno, y no te preocupes por estar pensando en porno constantemente. Cuando sea que lo estés pensando, sin importar el día, si lo piensas mañana, o el resto de tu vida, solo piensa **"GENIAL, SOY UN NO-USUARIO"**.
* **No uses ninguna** forma de sustituto. **No te retes** a ti mismo, al mantener tu laptop cerca mientras duermes. **No evadas ninguna** función de cine, ninguna película o revista. **No cambies tu estilo de vida** de ninguna manera solamente porque ya has dejado el porno. Si sigues las instrucciones de arriba, pronto experimentarás el "momento de revelación", pero:
* No esperes a que llegue el "momento de revelación". Solo sigue con tu vida, disfruta de los altibajos y de afrontar los malos momentos. Descubrirás que en poco tiempo llegará ese momento.
