# Ayuda a aquellos que se están hundiendo {#ayuda-a-aquellos-que-se-estan-hundiendo}

El pánico que los usuarios de porno sienten hoy en día sigue creciendo gradualmente, viendo como la percepción de hombres y mujeres respecto a la pornografía va cambiando, para mal. La naturaleza adictiva del porno está siendo estudiada cada vez más a menudo, dado a la diferencia que muchos notan respecto al porno de internet y el porno de antaño. La falta de esfuerzo y la gran disponibilidad para encontrarlo está alarmando hasta a los más empedernidos usuarios de porno. Incluso sienten que su cruzada por _la libertad de expresión y pensamiento_ está siendo secuestrada por varios elementos. Este "salvaje oeste", un internet sin ley hace casi imposible el hacer cumplir restricciones de edad a este "estímulo supranormal". Es desafortunado saber que esto no tendrá fin muy pronto, pero cientos de miles de usuarios ya están dejándolo, con muchos de los más adictos usuarios siendo conscientes de los estudios que muestran similitudes entre la pornografía y el abuso de sustancias. Cada vez que un usuario deja el barco hundiéndose, los que siguen a bordo se sienten incluso más miserables.

Cada usuario sabe instintivamente que es ridículo ponerse el pie a sí mismo, pasar tiempo en frente de píxeles bidimensionales, súper-estimulando su cerebro y en el proceso, desarrollando vías neurales que garantizan un pobre desempeño sexual. Si aún piensas que esto no es ridículo, solo párate en un puesto de revistas que esté en el centro de tu ciudad, busca y conversa con una revista pornográfica y pregúntate a ti mismo cuál es la diferencia. Solo nombra una. No puedes obtener el mismo calor y la misma intimidad placentera del sexo de esa manera. Si puedes dejar de comprar alcohol y cigarros cada vez que vas a un supermercado, definitivamente puedes dejar de visitar tu harem virtual. Los usuarios no pueden encontrar razones racionales para seguir viendo pornografía, pero no se sienten tan apenados si otras personas lo están haciendo también.

Los usuarios mienten descaradamente sobre su hábito, no solo a investigadores y a quienes los rodean, sino también a sí mismos. Tienen que hacerlo. El lavado de cerebro es esencial si quieren mantener un poco de respeto por su estado de usuarios. Sienten la necesidad de justificar su hábito no solo a sí mismos, pero también a los que no la usan. Van por la vida propagando las ventajas ilusorias de la pornografía de manera sutil.

Si un usuario detiene su consumo usando el MFV, se seguirá sintiendo despojado, cosa que lo tiende a convertir en una persona quejumbrosa. Y todo lo que hace esto es confirmar a otros usuarios el bien que hacen para sí mismos al seguir usándolo. Si el ex-usuario consigue dejar el hábito, estarán agradecidos de no tener que ir por la vida autosaboteando o gastando energía, y además, no tendrán la necesidad de autojustificarse. Pero recuerda, es el miedo el que mantiene al usuario con la cabeza en la arena, haciendo que solo cuestione su comportamiento después de haber dejado el hábito. Ayuda al usuario a remover esos miedos. Dile lo maravillosos que es no ir por la vida viviendo en una prisión, y qué tan maravilloso es despertarse en la mañana sintiéndose muy atlético y saludable, en lugar de amanecer sin energía y autodespreciándose. Dile qué maravilloso es ser libre de la esclavitud, el ser capaz de disfrutar su vida entera y librarse de esas sombras oscuras. O incluso mejor, haz que lean este libro.

Es esencial no menospreciar a alguien casado diciéndole que está deliberadamente destruyendo su relación, o que es una forma de infidelidad o una actividad sucia. Existe un concepto erróneo, que dicta que un ex-usuario es el más terco en este aspecto. La idea tiene fundamento, pero generalmente es gracias a que dejaron el hábito con el MFV que son así. Debido a que el ex-usuario (a pesar de haber dejado el hábito) todavía retiene un poco del lavado de cerebro y sigue creyendo que hizo un sacrificio. Se sienten vulnerables y su mecanismo de defensa natural es atacar al actual usuario de pornografía.

Esto podría alimentar el ego del ex-usuario, pero no le ayuda en nada al usuario actual. Todo lo que hace es arrinconar a este último, haciéndolo sentir incluso más miserable, y consecuentemente haciendo que su necesidad de pornografía sea más grande. A pesar de que el cambio en la actitud de las instituciones médicas respecto al porno en internet se mantiene como la razón por la cual muchos usuarios lo están dejando, esto no hace las cosas más fáciles. De hecho, hace que sea mucho más difícil. Muchos de los usuarios hoy en día creen que están dejándolo por razones meramente médicas. Cosa que no es enteramente cierta.

A pesar de que el enorme aumento de riesgo a la salud es obviamente la principal razón para dejarlo, los adictos ya han saboteado por años su virilidad, y el conocer ese riesgo no hará ni la más mínima diferencia. La razón principal del porqué los adictos están dejándola es porque la sociedad está empezando a ver la pornografía sin filtros, por lo que realmente es: una	drogadicción. La actitud de la sociedad está lentamente cambiando — lo más probable ahora es que tu pareja te pregunte por qué estás en tu laptop a altas horas de la noche. La prohibición total de la pornografía en algunos países o la indisponibilidad del internet son ejemplos clásicos del "dilema del usuario viajero". Generalmente, los usuarios tomarán la actitud de que les ayudará a reducir su consumo. Pero resulta que en lugar de ser un día o dos, ninguno de los cuales habrían disfrutado, se abstienen por una semana completa. Sin embargo, durante este forzado período de abstinencia, no solo se sentirán mentalmente privados, esperando por su premio, su cuerpo también estará ansiándolo. ¡Oh, cuán preciosa es la visita a ese harem cuando eventualmente se les permite!

Las abstinencias forzadas no reducen el consumo porque el usuario solo se inclina más a su adicción cuando por fin se le permite ser libre. Lo único que hace es arraigar en la mente del usuario cuán 'preciosa' es la pornografía en internet y cuán dependiente es de ella. Y el más engañoso aspecto de esta abstinencia forzada es su efecto en adolescentes. En primer lugar, permitimos que los secuestradores de la 'libertad de expresión', los productores de pornografía elijan como blanco a adolescentes desafortunados para engancharlos. Después, en el que probablemente sea el período más estresante en sus vidas, cuando sus engañadas mentes necesiten de pornografía sobre todas las cosas, los chantajeamos para dejarla, por el daño que se causan a sí mismos con ella.

Muchos son incapaces de dejarlo, y son forzados, sin ser realmente su culpa, a sufrir de un complejo de culpabilidad por el resto de sus vidas. Muchos consiguen dejarlo y se regocijan de ello, pensando, _"bien, lo dejaré solo por ahora, y para cuando termine este período, estaré curado de todas formas"_. Luego viene el dolor y el miedo de encontrar un trabajo y otros problemas de adultos, seguido del 'pico' más alto de sus vidas — encontrar un trabajo en cuestión. Y para cuando el dolor y el miedo se terminen, con estos usuarios sintiéndose seguros, sus viejos mecanismos neuronales vuelven a operar. Parte del lavado de cerebro sigue ahí después de todo, y para cuando el olor de la laptop nueva que su trabajo les proporcionó desaparezca, el usuario ya estará al umbral de su página favorita. La emoción que sienten por esta ocasión especial bloquea los sentimientos de culpa de su mente. No tienen la intención de engancharse de nuevo, pero una sola vez no los matará... ¡Demasiado tarde! Ya están enganchados de nuevo.

La vieja ansia del 'pequeño monstruo' comenzará otra vez, y aun si no se enganchan de inmediato, un período efímero pero agudo de depresión probablemente los enganche de nuevo. Es extraño que, aunque los adictos a la heroína sean criminales de ley, la sociedad sigue respondiendo a sus llamados de auxilio. Hay que adoptar la misma actitud hacia el pobre usuario de pornografía. No lo hacen porque quieran, sino porque piensan que tienen que hacerlo. Y a diferencia del adicto a la heroína, los usuarios de porno usualmente tendrán que sufrir año tras año de tortura mental y física. Siempre decimos que una muerte rápida es mejor que una lenta, así que no envidies al pobre usuario de pornografía. _**Merecen de tu lástima.**_
