# Consejos para los no-usuarios

## Ayuda a que tus compañeros usuarios lean este libro

Antes que nada, estudia todo el contenido de este libro y trata de ponerte en los zapatos de un usuario. No los fuerces a leer el libro, diciéndoles que están arruinando su salud o que están jugando con fuego. Ellos lo saben mucho mejor que tú. Los usuarios no dejan de usar pornografía porque la disfruten o porque quieran, eso se lo dicen a ellos mismos y a los demás en orden para mantener un poco de respeto por sí mismos. Lo hacen porque son dependientes de ella, porque creen que los relaja, que les da coraje y confianza (placer o apoyo) y porque sienten que la vida nunca será disfrutable sin “sexo” — o al menos, sin la visión de sexo que tienen ellos. Si intentas forzar a un usuario a detenerse, harás que se sienta como un animal enjaulado, deseando aún más su harem. A su vez, eso podría convertirlo en un usuario secreto, haciendo que la pornografía se vuelva todavía más preciada en su mente.
 
En vez de eso, trata de concentrarte en el otro lado de la moneda. Haz que entren en contacto con otros ex-usuarios (que entren a blogs, a foros, a YBOP, a NoFap en Reddit, etc.). Que lean cómo estas personas pensaban que estarían enganchados de por vida, y cómo mejoró su vida al convertirse en no-usuarios. Una vez que les hagas ver que detenerse es posible, sus mentes empezarán a abrirse. Entonces, empieza a explicarles la ilusión que los dolores de abstinencia crean. Hazles entender que no solo las constantes “dosis de dopamina” dejaron de tener efecto en sus cuerpos, sino que además están destruyéndose a sí mismos, haciéndose más irritables, flojos y destruyendo su confianza al mismo tiempo.
 
Para ese entonces, ya deberían estar listos para leer el libro, a pesar de que esperen leer páginas y páginas sobre historias de usuarios que desarrollaron disfunción, estudios sobre desensitización, disfunción inducida por pornografía, etc. Es importante que también les expliques que este método es completamente diferente, y que todos los aspectos biológicos sobre la pornografía abarcan una pequeña fracción del material en este libro.
 
En resumen, no dejes que el libro termine aquí. Cuéntaselo a tus amigos, pero no actúes raro sobre esto. Al querer ‘ganar’ en la conversación o debatir con ellos, sólo harás que se cierren al tema, e incrementarás sus miedos.
 
## ¿Debería contárselo a mi pareja?

_“¿Debería informarle a mi esposa, novia o pareja sobre mi hábito?”_ La intención que tienes al decirle es que te ayude a dejarlo, pero hay múltiples factores en juego.
 
Si ya fallaste en dejarlo usando el MFV, y, además, ya se lo dijiste a tu pareja, cuéntale sobre este nuevo método, y deja que se eduque a sí mismo/misma leyendo este libro. Estarán dispuestos a asistirte y motivarte durante el periodo de abstinencia, y te serán de apoyo cada que el pequeño monstruo intente hacerte tropezar.
 
Si apenas tomaste consciencia sobre la trampa del porno, y no has intentado detener tu consumo en el pasado, entonces empieza por acabar el EasyPeasy por tu cuenta. Como mencioné anteriormente, esto debería ser una experiencia disfrutable. Sin embargo, si te resulta difícil, entonces pide ayuda a tu pareja. Sé abierto y vulnerable con él/ella, y te aseguro que incluso se fortalecerá su relación.
 
De todas formas, siempre y cuando disfrutes del proceso y no lo encuentres complicado, no hay mucha razón en dejar que tu pareja lo sepa. Si tu consumo no resultaba un problema muy grande en el pasado, déjalo morir sin más. Ah, pero eso sí, ¡prepárate, porque tu pareja empezará a hacer demasiadas preguntas sobre porque te ves, te sientes y te comportas mucho mejor y más reluciente que antes!
 
## Mi pareja está dejando la pornografía

La pornografía es un perverso destructor de relaciones, y a pesar de que dejarlo puede ser instantáneo, cicatrizar las heridas toma tiempo. Hay muchos usuarios que, debido a las creencias irracionales generadas por su adicción, arremeten su ira contra sus parejas y seres queridos. Estos comportamientos son manifestados en _gaslighting_ (abuso psicológico), mentiras y manipulación. Esto no sucede con todos los usuarios, pero es una conducta que comúnmente se incrementa en etapas tardías de la enfermedad. Además de que estos comportamientos manipuladores puedan manifestarse por debajo de la mesa, por lo que es importante que te eduques sobre estos comportamientos y de reconocerlos, considera consultar a un terapeuta especializado en adicciones sexuales.
 
Si tu pareja se encuentra en el periodo de abstinencia, asume que están sufriendo, aún si están sufriendo de verdad o no. No intentes minimizar su estado, diciéndole que es fácil dejar la pornografía; tu pareja lo sabe, y puede hacerlo por cuenta propia. En vez de eso, trata de recordarle constantemente lo orgulloso/a que estás de él/ella, como mejora su aspecto con los días, lo dulce que es estar con él/ella ahora y lo fácil que resulta tratar con él/ella ahora. Es particularmente importante que lo hagas constantemente, ya que cuando un usuario empieza un intento por detener su consumo, la euforia por este intento y los halagos que recibe de su pareja le serán de inmensa ayuda. Sin embargo, puede que lo olvide rápidamente, así que no te detengas con los cumplidos.
 
Recuerda también que a pesar de que ya no mencione nada acerca sobre su consumo de pornografía o de pornografía en general, no significa que ya lo haya olvidado y que no quiere que se lo recuerdes. Usualmente, el caso es completamente opuesto a como es con el MFV, ya que es con este método donde los ex-usuarios tienden a obsesionarse con no pensar en pornografía y nada más. Así que no tengas miedo de traer de vuelta el tema. Sigue animando a tu pareja, él/ella te dirá si quiere o no que se lo recuerdes.
 
Haz todo lo posible por aliviar a tu pareja de la presión que tenga durante el periodo de abstinencia, y piensa en formas de hacer que su vida sea más interesante y disfrutable. Este período también puede ser difícil para los no-usuarios, quienes nunca han experimentado el sufrir de esta adicción. Si una persona en un grupo de amigos está irritable, puede transmitir esas malas vibras a los demás miembros. Así que anticipa los momentos en que el ahora ex-usuario pueda sentirse irritable, ya que puede que lo arremeta contra ti. Pero no lo tomes a mal, este es el periodo en donde más necesitan de elogios y simpatía. Y si llegas a sentirte irritable, trata de no mostrarlo.
 
Uno de los tantos trucos que un usuario que está intentando dejar el porno con el MFV usará cuando intente rendirse es el de hacer _rabietas_, con la esperanza de que su pareja o amigos digan: _"No soporto verte sufrir así. Por el amor de Dios, solo tomate tu veneno y ya"._ Así, el usuario no puede sentirse culpable; no está "renunciando", alguien le _ha dado permiso_ de hacerlo. Si tu pareja llega a usar esta táctica, no lo animes a recaer, bajo ninguna circunstancia. En su lugar, di algo como: _"Con que esto es lo que el porno te hace, ¿eh? Gracias a Dios, pronto serás libre. Es maravilloso que tuvieras el coraje para dejarlo"._
 
Y recuerda, hay dos lados de la moneda dentro de este viaje de recuperación. Cuando tu pareja está dejando la pornografía, es importante que TÚ también tengas tu propio sistema de apoyo; que tengas tus momentos y actividades de autocuidado y que pongas límites. Este proceso no ocurre de la noche a la mañana, requiere de confianza, comunicación y rendición de cuentas. Anotar tus observaciones en un diario, desarrollar tus propias pasiones y, lo más importante, ir terapia, ayudan a este proceso.
 
## Resbalones (recaída)

La existencia de esta sección debería servir como una advertencia para aquellos que ya abandonaron la trampa. Personalmente, nunca he recaído, pero voy a utilizar experiencias que recopilé a raíz de entrevistas con miembros de la comunidad y algunas herramientas de terapia cognitiva-conductual para ilustrar el tema.
 
Primero, llamarlo _recaída_ es contraproducente. Cuando uno recae es porque se ha resbalado; todo lo que este usuario hizo fue alimentar al pequeño monstruo, que a su vez puso en marcha el Gran Monstruo del lavado de cerebro. Los usuarios que se resbalan (cosa que al final del día, resulta ventajosa) suelen generar toda una gama de creencias irracionales:
 
* _"Jamás seré libre"_ — **Catastrofización**
* _"Debo / tengo que ejercitarme, estudiar y ser fructífero cada día de mi vida"_ (A.K.A musterbating)
* _"Acabo de masturbarme, ¿y de qué sirvió leer tantos libros y foros? Mi objetivo ni siquiera era dejar de masturbarme, pero aquí estoy - soy un fracasado, que terminó recayendo"._ — **Baja tolerancia a la frustración**
* _"Mis amigos / los usuarios de un foro / otros dejarán de usar porno durante (n) días, pero ni siquiera puedo hacerlo, porque soy un caso perdido. Me sentí bien ayer desde que estudié adecuadamente y aproveché mi día, pero hoy no me siento igual... Estoy yendo cuesta abajo"._ — **Compararse con otros**
* _"No debería tener pensamientos sexuales"_ — Estos usuarios mismos, sus padres y la sociedad en conjunto han instalado **rígidas creencias** sobre el sexo. Quiero que te cuestiones: ¿si la autoflagelación realmente ayuda a alcanzar tus objetivos, está garantizado que disfrutes del viaje también? _**¿De qué sirve alcanzar tus objetivos si el camino es tortuoso?**_
 
Los factores que conforman el lavado de cerebro de cada usuario son, aparentemente, infinitos. Y tú lo sabes mejor que nadie: los usuarios que recaen fallaron en entender las instrucciones. Este usuario volvió a darle valor al porno en su mente, pero ¿cómo lo hizo?
 
Lo que a menudo se pasa por alto es que revertir el lavado de cerebro toma tiempo. Esto no lo hace más difícil, pero casi todas las industrias (cine, música, publicidad, etc.) usan el sexo como un factor de venta, y contrarrestar activamente el lavado de cerebro es un proceso consciente (al menos al inicio), por lo que podría llevar tiempo solidificar completamente las lecciones contenidas aquí. Por lo tanto, recomiendo fuertemente releer el libro varias veces (puedes saltarte a los capítulos que todavía no entiendes al 100%), cosa que no debería tomarte mucho tiempo.
 
Una experiencia sorprendentemente común para los usuarios religiosos que dejan la trampa es la de querer que el proceso sea medianamente doloroso, a manera de expiación. Lo encuentran fácil de dejar, pero luego terminan sintiéndose culpables por sentir que fue fácil. Pero ¿por qué autosabotear tu proceso, y hacerlo conscientemente difícil? El pequeño monstruo es muy astuto en este sentido, y puedo aprovechar este hueco. Así que maneja este aspecto con cuidado. 
 
Disocia el pequeño monstruo de tu mente, el cual fue añadido hace mucho tiempo gracias a la industria de la pornografía. Imagina este monstruo como un bully que está haciendo rabietas en el patio de recreo de la escuela. ¿Qué le dices al bully? Si te rindes ante sus caprichos, le darás más fuerza. Algunos usuarios que dejaron el porno terminan alimentando los caprichos del bully, y aumentan su lavado de cerebro, a pesar de que su conceptualización de la trampa no ha cambiado. ¡Así que levántate, averigua dónde te equivocaste y disfruta de la libertad!
 
Tú no eres tus impulsos. La meditación _Mindfulness_ es la práctica de señalar el pensamiento en su propia naturaleza, y hay lecciones fundamentales acerca de la naturaleza de la mente que puedes encontrar en internet. Es muy recomendable que medites, en general, además de ser completamente compatible con cualquier práctica religiosa. No puedes luchar contigo mismo, ni con el pequeño monstruo. Tienes que amarte incondicionalmente; a ti mismo y al proceso.
 
Así que remueve la idea del fracaso de tu mente. Te dejo una sección de _"Meditaciones de un adicto a la pornografía"_ de Gulliaco (puedes encontrar este texto completo en la sección de recursos, al final del libro):
 
Ya que la pornografía te ofrece ningún beneficio, es algo que solo te lastima, y es extremadamente ridículo querer hacer algo así, lo comparo con el deseo de beber cloro. Así va la cosa:

> **El gran esfuerzo que conlleva no beber cloro:**  
¡Hola! Somos _NoBleach_ y organizamos desafíos en los que los participantes (_"Los Cloronautas"_) se abstienen de beber cloro durante un período de tiempo. Ya sea que tu objetivo sea participar de forma casual en un desafío mensual para probar tu autocontrol, o si el consumo excesivo de cloro se ha vuelto problemático en tu vida y deseas dejarlo durante un período de tiempo más largo, encontrarás una comunidad de apoyo y una cantidad extensa de recursos aquí.
> 
> * _"A veces me permito beber uno o dos vasos de cloro. Sé que lo de tener ‘una sola gota’ es una mentira, pero no creo que un vaso me haga daño. Uno solo no puede destruir todas las horas que he pasado sin tomar cloro"._
> * _"No tengo problemas para dejar de beber cloro, pero a veces voy por la calle y veo a alguien bebiendo agua, ya sabes, en un vaso, e imagino que el vaso tiene cloro. Entonces se me antoja y, después de debatir conmigo mismo sobre si debería hacerlo o no, finalmente cedo por la noche y bebo un vaso"._
> * _"Mira, mi problema es que a veces, cuando estoy solo en mi cocina, empiezo a ver los vasos, y a veces me tiento a mí mismo abriendo el cajón donde guardo el cloro; a veces lo huelo y… bueno, termino justo donde empecé. Estoy tan desesperado por detener esto, pero no estoy seguro de si alguna vez podré parar"._
> * _"Dejar de beber cloro es imposible para mí; quiero decir, siempre tengo mi boca encima, ¿sabes? ¿Cómo se supone que deba parar si siempre tengo una garganta que me recuerda que puedo tragar cloro?"_
> * _"Hombre, iba tan bien, 19 días enteros sin beberlo. ¡Lo importante es aprender del fracaso! Ahora sé qué debo evitar: mirar productos de limpieza en el supermercado. ¡Intentaré hacerlo por un mes entero! Voy a restablecer mi contador. ¡Deséenme suerte!"_
> 
> Si tienes deseo por beber cloro, ¡cálmate, bro! Recuerda lo que dice el hackbook:
> 
> _"Es difícil dejar de beber cloro por miedo de que nos estaremos privando de nuestro placer o apoyo. El temor de que ciertas situaciones agradables nunca volverán a ser las mismas. El miedo a no poder hacer frente a situaciones estresantes. En otras palabras, los efectos del lavado de cerebro nos engañan, haciéndonos creer que comprar cloro, y por extensión beberlo, es una necesidad para todos los seres humanos. Peor aún, es la creencia de que necesitamos cloro asequible inherentemente, y que cuando dejemos de beberlo nos estaremos negando un placer a nosotros mismos, y crearemos un vacío. Déjalo claro en tu mente: ¡el cloro no llena un vacío, lo crea!"_
> 
> Es aquí donde me digo a mí mismo: _"Supongamos que estás obligado a ver un vaso lleno de cloro, durante cinco minutos. Trata de recordar una de esas marcas u olores que tanto te gustaban. Tal vez éste recuerdo esté acompañado por algún sonido, o quizá solo recuerdes detalles específicos. El cloro está ahí, y no puedes cerrar los ojos ni girar la cabeza, porque el cloro no solo está frente a tus ojos: ahora está en tu mente también, es un recuerdo registrado en tu cabeza.  
¿No se te antojó un poco de cloro? ¿Sientes algún sabor en tu lengua o algún cambio en tu respiración? ¿Qué es lo que sientes al recordarlo? Identifica esos sentimientos, porque el cloro quiere nublarlos, hacerlos confusos y hacer que solo prestes atención a lo que quiere atraparte"._
 
Con lo anterior, no trato de hacer un lado tus sentimientos, mucho menos de decir algo como _"jaja, yo listo, tú tonto"_, sino de darte perspectiva, para que te des cuenta de lo ridículamente fácil que es (y lo ridículamente fácil que siempre será) superar esta adicción. Ver pornografía no es como un interruptor de encendido/apagado donde dices _"oh, bueno, estoy en X situación, voy a ver porno"_. ¡Eso es una fantasía! ¡Una mentira! ¿Con qué frecuencia te permites beber UN solo vaso de cloro? ¿Nunca? ¿Y por qué? ¡Porque es algo horrible, por eso no bebes cloro! ¿Cómo se supone que escaparás de tu adicción si no te das cuenta de que el ciclo de PMO es algo horrible para ti mismo?
 
## ¿Y qué hay con el ciclo de MO (masturbación y orgasmo)?

La gente ha estado masturbándose por eones sin ningún problema. Y para que quede claro, el porno es el problema.
 
Sin embargo, todavía puedes engancharte al MO por las mismas razones que con el porno. Por poner un ejemplo, cierta parte del lavado de cerebro que se obtiene con la masturbación es la de tener la mentalidad de _“El orgasmo es una necesidad inherentemente humana”_; el lavado de cerebro va desde la fantasía sexual, querer forzarte a tener relaciones sexuales o simplemente buscar placer hedonista.
 
Además, es extremadamente probable que la pornografía y la masturbación se hayan entrelazado profundamente en tu mente. Muchos usuarios descubren que terminan recayendo como resultado de masturbarse con fantasías inducidas por el porno. Y a medida que su cerebro se empieza a re-cablear, descubren que este lavado de cerebro eventualmente desaparece. Por lo que lo mejor es tomarse un descanso del ciclo de MO por un tiempo. También deberías buscar sexo real si quieres acelerar este proceso.
 
Esto no es una instrucción, pero te pido la evalúes. Por otro lado, ya se han reportado muchos beneficios sobre la retención de semen, los cuales son numerosos: obtienes una mayor concentración y energía, hay una eliminación de la "niebla mental" y hay un incremento en la confianza propia, junto con otra gran cantidad de múltiples beneficios. Por experiencia propia, puedo decirte que hay una clara diferencia, y todo se debe a cómo se transmuta esta energía acumulada.
 
Esta reflexión nace de la especulación, y a pesar de no tener un estricto conocimiento científico, puedo decirte que los beneficios podrían reducirse a un par de factores diferentes:

* Después del orgasmo, el cerebro libera prolactina, químico que inhibe la liberación adicional de dopamina.
* Privar a tu cerebro de la constante liberación de dopamina permite que tengas una mayor absorción de esta, al simplemente vivir tu vida.
* El semen es reabsorbido por el torrente sanguíneo después de ~78 días, y es uno de los mejores nutrientes que tu cuerpo puede obtener.
* Transmutando la energía sexual en hábitos productivos trae consigo una capa adicional de productividad.
 
Puede que también desees tener relaciones sexuales sin llegar a un orgasmo, como ya te he mencionado, lo cual es una experiencia sexual maravillosa. Puedes fortalecer tu capacidad de retención con ejercicios de Kegel. Por experiencia personal, puedo decirte que la forma más fácil y efectiva de ejercitar la próstata es deteniendo la orina a mitad de la micción. Además, la separación de las partes tántricas y propagativas del sexo resulta ser una de las muchas ventajas de escapar de la trampa del PMO (¡cosa que a mis parejas también les ha encantado!).
 
## Desviaciones del aconsejamiento estándar

Esta sección es nueva y está escrita de manera algo aprensiva; aun así, debe ser mencionada.
 
Algunas personas que utilizaron EasyPeasy se dieron cuenta de que su deseo de ver porno se redujo tanto que no pudieron tener una sesión final. **Eso está bien**, pero no subestimes el poder de tener una. Navegar conscientemente y solidificar lo poco que te agrada el PMO puede ser una herramienta realmente poderosa. Personalmente, lo encontré realmente útil y estaba feliz de lavarme las manos al finalizar esa sesión; genuinamente aliviado de no tener que hacerlo nunca más. Sin embargo, puede que tu experiencia varíe.
 
Así que, si ya has estado libre de la trampa durante un buen tiempo y acabas de remover el lavado de cerebro, no hay necesidad de alimentar al pequeño monstruo entonces, ya que podría molestarte. ¡Disfruta de la libertad en su lugar!
 
## Ayuda a poner fin a este escándalo

La pornografía en Internet es uno de los peligros de la sociedad libre. Es algo seguro que la base de la civilización — la razón por la que la especie humana ha avanzado hasta ahora — está fundamentada en el hecho de que somos capaces de comunicar nuestros conocimientos y experiencias, no solo entre nosotros, sino con las generaciones futuras. Incluso a los animales les resulta necesario advertir a sus hijos de las trampas de la vida.
 
Los productores de pornografía no están haciendo esto de buena fe, creyendo genuinamente que ayudan a la humanidad, especialmente ahora que la adicción al porno en Internet está ampliamente estudiada. Quizá en sus etapas iniciales la gente creía genuinamente que el porno educaba a la gente sobre la intimidad, pero las autoridades saben que eso es una falacia. Ningún harem en línea tiene realmente la misión de educar. Todo lo que investigan a fondo es la cualidad de shock, novedad y escalación que tienen sus productos.
 
¡Este aspecto de la sociedad es absurdamente hipócrita! Nos preocupamos por aspectos sociales como el bullying escolar y la objetificación del cuerpo. _Ah, pero ver porno no tiene nada de malo, los problemas que resultan de él son minúsculos._ Hay una cantidad inmensa de adictos que escalan a nuevas alturas cada año, pasando mucho más tiempo de calidad con imaginarias e ilusorias personas hechas de píxeles a expensas de su salud, virilidad, energía y tiempo. El porno es por mucho, el mayor asesino de relaciones; cientos de miles de vidas se arruinan cada año gracias a que se enganchan con él. Y los productores de pornografía en Internet ni siquiera se preocupan por anunciar sus productos en las redes sociales mainstream - ni siquiera lo necesitan. Son nuestros impulsos biológicos los que nos llevan a los umbrales de sus bien surtidos harems, quienes dan muestras gratis a diestra y siniestra en los rincones de Internet, tal como lo hacen los traficantes de droga. 
 
Ah, pero qué astucia la de las compañías pornográficas, quienes etiquetan su contenido con un sticker de _“para mayores de 18 años”_ como elemento disuasorio para los usuarios menores de edad. Y eso que hay algunas páginas que ni siquiera se molestan en ponerlo. El porno en Internet afecta **a todos y a todas las edades**. _"Te advertimos del peligro, tú decides"._ Es la actitud que toman. ¿Pero acaso toman alguna medida para verificar la edad del usuario? No, porque eso desalentaría a sus clientes. Aunque claro, de legislarse la verificación de edad, estas compañías buscarían otro país desde el cual operar. O, ¿acaso pagarán a la "élite" para escribir artículos sobre cómo la prohibición de la pornografía resultara en el contrabando ilegal y la creación de una mafia pornográfica? Da igual, porque la cuestión es convenientemente olvidada. Todos sabemos que la prohibición del alcohol no resultó en la reducción de las víctimas relacionadas con la bebida, así como del fracaso de las fuerzas del orden para controlar el crecimiento de la mafia.
 
Podemos abordar esto de manera diferente, educando a la generación más joven. Si pueden caminar a través de una licorería, sin sentir necesidad de comprar cigarros o vodka, pueden hacer lo mismo con la pornografía de Internet. Ya estamos viendo cambios sociales, solo mira los memes de _"No Nut November"_ y _"Coomer"_ que aparecen en el buscador de Google; nichos de internet que se están convirtiendo en algo _mainstream_. El usuario no tiene más opción que el adicto a la heroína. Los usuarios no deciden engancharse, son atraídos de manera sutil a la trampa. Y si tuvieran la opción, los únicos usuarios de mañana serían adolescentes que apenas comienzan, creyendo que podrían parar en cualquier momento si quisieran.
 
¿Por qué los estándares para el adicto al porno son tan falsos? ¿Por qué los adictos a la heroína son vistos como delincuentes, pero pueden registrarse como adictos y obtener metadona y el tratamiento médico adecuado para ayudarlos a salir de su adicción? Trata de ir con tu médico, dile que te de una prescripción para tratar con la adicción al porno, y lo más probable es que te diga: _“Deja de hacerlo tanto, trata de moderarte"_ cosa que ya sabes que no funcionará. Puede que hasta te receten medicamentos para abordar tu "depresión". Y peor aún, puede que te aconsejen buscar una pareja real. ¿En serio? ¿Conocerán de algún usuario que usa pornografía a escondidas de su pareja? Algunas personas simplemente no lo entienden.
 
Las campañas de miedo no ayudan a los usuarios a detenerse tampoco, lo hacen más difícil. Todo lo que hacen es asustar a los usuarios, lo que les hace querer ver aún más pornografía. Resulta que también ayudan a evitar que los adolescentes se enganchen. Pero a pesar de que los adolescentes saben que el porno debilita su libido, también saben que una _miradita no hará que se enganchen_. Y debido a que la adicción es un aspecto prevalente en los más jóvenes (ya que son bombardeados sexualmente hasta en la sopa), tarde o temprano el adolescente — ya sea por presión social o curiosidad — dará solo una visita a un harem. Recuerda que el porno gratis suele ser horrible, por lo que es probable que se enganchen a la primera.
 
¿Por qué permitimos que continúe este escándalo? ¿Por qué los gobiernos no incitan campañas adecuadas? ¿Por qué no se nos dice en la escuela que el porno en Internet es una droga y un veneno asesino, que no te relaja ni te da confianza, sino que destruye tus nervios, a la vuelta de una sola miradita? ¿Por qué no pueden hacer cumplir la verificación de edad solicitando tarjetas de crédito registradas, tal vez a través de un programa de terceros? Mindgeek, propietario de muchos de los principales sitios pornográficos, está intentando estafar a los gobiernos para que usen su propia solución patentada de verificación de edad, ¡pero no dejes que lo hagan! _The Time Machine_ - de H. G. Well habla sobre un incidente en un futuro lejano en el que un hombre cae en un río. Sus compañeros simplemente se sientan alrededor de él en la orilla, ajenos a los gritos de desesperación. Inhumano e inquietante, al igual que la apatía general de la sociedad hacia la crisis pornográfica.
 
Hay una luz de esperanza emergiendo en la sociedad. Una bola de nieve ha comenzado a rodar cuesta abajo y se espera que este libro ayude a convertirlo en una avalancha. Tú también puedes ayudar difundiendo el mensaje.
 
Puedes empezar de esta forma: si ves a alguien luchando con toda su fuerza de voluntad o alguien con la intención de dejar el porno, acércalo amablemente hacia este método. Sin embargo, recuerda que la verdadera tarea en cuestión es cambiar la narrativa en torno a la pornografía en general. Por favor, considera hacerte al hábito de educar a las personas que conozcas, ya sea que veas a alguien normalizando la pornografía en la vida real, o en línea.
 
Puede que obtengas una reacción negativa, pero a veces solo basta con que hagas un comentario. Como muchos antes que tú, puedes que llegues a recibir mensajes sorpresa de algunas personas, gratas de haberse librado de la trampa gracias a tu comentario. 
 
## Última advertencia 

Ahora puedes disfrutar del resto de tu vida como un no-usuario feliz. Y para asegurarte de que así sea, solo debes seguir estas sencillas instrucciones:
 
* Guarda la siguiente página en tus marcadores, o guarda el libro en tu biblioteca, e ingresa a estos recursos tanto como necesites.
* Si alguna vez empiezas a envidiar a un usuario, recuerda que son ellos los que te envidian. Tú no estás siendo privado de nada, ellos sí.
* Recuerda que no disfrutaste de ser un usuario. Por eso te detuviste. Te gusta no ser un usuario. Recuerda, no hay tal cosa como _una sola miradita_.
* Nunca dudes de tu decisión de nunca volver a ver porno. Sabes qué es lo correcto.
* Si tiene alguna dificultad, encuentra y ponte en contacto con un terapeuta especializado en adicción pornográfica. Puedes encontrar alguno de estos en línea.

