# Las instrucciones

* Sigue todas las instrucciones.
* Mantén una mente abierta.
* Empieza tu lectura con entusiasmo.
* Ignora todo consejo e influencia que entre en conflicto con lo que EasyPeasy te propone. 
* Resiste cualquier ‘dosis temporal.’ No existen las ocasiones especiales.
* Hazlo claro en tu mente: El porno no te proporciona nada, no es un placer ni un apoyo, y al dejarlo no estás haciendo un sacrificio. No hay nada a lo que renunciar y no hay razón por la que debas sentirte privado. 
* ¡No esperes a poder dejarlo, hazlo ahora!
* Toma la decisión de que nunca volverás a ver pornografía y nunca cuestiones dicha decisión. 
* Recuerda que no existe tal cosa como ‘solo una miradita’. El porno es una acción en cadena, y una cadena de por vida. 
* No vuelvas a ver porno, nunca más.

## Afirmaciones

* Soy libre de la esclavitud que la pornografía me impone. 
* Es ridículamente fácil ignorar mis pensamientos sobre pornografía. 
* Hasta nunca, pensamientos intrusivos. Hasta nunca, deseos por masturbarme. Vaya, por allá van mis ganas de querer ver porno…
* Concentro mi mente subconsciente en vencer mi adicción al porno.
* La pornografía roba mi tiempo, mi energía y mi vitalidad.
* Vencer la pornografía se pone exponencialmente más fácil cada día, y en cada aspecto. 
* Disfruto y valoro mi fuerte, ligero y feliz estilo de vida libre de porno.
* Si miro hacia atrás y pienso sobre mi progreso, me da demasiada alegría y me hace sentir orgulloso de mi mismo.
* Cada que veo a un usuario de pornografía me siento más motivado a verme a mí mismo romper la cadena del PMO. 
* Toda esa energía reprimida en mi ahora está sanando mi cuerpo y mente. Y ahora puedo trabajar de manera más productiva y retarme a hacer cosas que me acerquen a mis valores y metas.
* Mi cerebro está regresando a su forma correcta y sana, cosa que se ejercita al no hacer lo que hacía previamente. 
* Ahora, toda esa fuerza de voluntad que vivía reprimida en mi está siendo utilizada para lidiar con los leves estreses y jalones de la vida.
* ¡Genial! Ya no soy un esclavo. ¡Soy libre!

